# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'after_death.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QGroupBox, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QRadioButton,
    QSizePolicy, QTimeEdit, QWidget)

class Ui_after_death_MainWindow(object):
    def setupUi(self, after_death_MainWindow):
        if not after_death_MainWindow.objectName():
            after_death_MainWindow.setObjectName(u"after_death_MainWindow")
        after_death_MainWindow.resize(1270, 890)
        self.gb_service_type = QGroupBox(after_death_MainWindow)
        self.gb_service_type.setObjectName(u"gb_service_type")
        self.gb_service_type.setGeometry(QRect(20, 10, 601, 70))
        font = QFont()
        font.setPointSize(12)
        self.gb_service_type.setFont(font)
        self.rb_waste = QRadioButton(self.gb_service_type)
        self.rb_waste.setObjectName(u"rb_waste")
        self.rb_waste.setGeometry(QRect(20, 30, 150, 30))
        self.rb_waste.setFont(font)
        self.rb_waste.setChecked(True)
        self.rb_cremation = QRadioButton(self.gb_service_type)
        self.rb_cremation.setObjectName(u"rb_cremation")
        self.rb_cremation.setGeometry(QRect(180, 30, 150, 30))
        self.rb_cremation.setFont(font)
        self.rb_jewelry = QRadioButton(self.gb_service_type)
        self.rb_jewelry.setObjectName(u"rb_jewelry")
        self.rb_jewelry.setGeometry(QRect(340, 30, 150, 30))
        self.rb_jewelry.setFont(font)
        self.gb_lab_request = QGroupBox(after_death_MainWindow)
        self.gb_lab_request.setObjectName(u"gb_lab_request")
        self.gb_lab_request.setGeometry(QRect(20, 90, 600, 460))
        self.gb_lab_request.setFont(font)
        self.rb_incineration = QRadioButton(self.gb_lab_request)
        self.rb_incineration.setObjectName(u"rb_incineration")
        self.rb_incineration.setGeometry(QRect(20, 30, 350, 30))
        self.rb_incineration.setFont(font)
        self.le_incineration_kg = QLineEdit(self.gb_lab_request)
        self.le_incineration_kg.setObjectName(u"le_incineration_kg")
        self.le_incineration_kg.setGeometry(QRect(400, 30, 80, 30))
        self.le_incineration_kg.setFont(font)
        self.label_kg = QLabel(self.gb_lab_request)
        self.label_kg.setObjectName(u"label_kg")
        self.label_kg.setGeometry(QRect(490, 30, 40, 30))
        self.label_kg.setFont(font)
        self.rb_bone_storage = QRadioButton(self.gb_lab_request)
        self.rb_bone_storage.setObjectName(u"rb_bone_storage")
        self.rb_bone_storage.setGeometry(QRect(20, 70, 450, 30))
        self.rb_bone_storage.setFont(font)
        self.rb_ceremony = QRadioButton(self.gb_lab_request)
        self.rb_ceremony.setObjectName(u"rb_ceremony")
        self.rb_ceremony.setGeometry(QRect(20, 110, 450, 30))
        self.rb_ceremony.setFont(font)
        self.label_date = QLabel(self.gb_lab_request)
        self.label_date.setObjectName(u"label_date")
        self.label_date.setGeometry(QRect(40, 150, 80, 30))
        self.label_date.setFont(font)
        self.dateEdit = QDateEdit(self.gb_lab_request)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(130, 150, 130, 30))
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.label_time = QLabel(self.gb_lab_request)
        self.label_time.setObjectName(u"label_time")
        self.label_time.setGeometry(QRect(280, 150, 80, 30))
        self.label_time.setFont(font)
        self.timeEdit = QTimeEdit(self.gb_lab_request)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(370, 150, 120, 30))
        self.timeEdit.setFont(font)
        self.rb_diamond_mem = QRadioButton(self.gb_lab_request)
        self.rb_diamond_mem.setObjectName(u"rb_diamond_mem")
        self.rb_diamond_mem.setGeometry(QRect(20, 190, 350, 30))
        self.rb_diamond_mem.setFont(font)
        self.label_carcass_cond = QLabel(self.gb_lab_request)
        self.label_carcass_cond.setObjectName(u"label_carcass_cond")
        self.label_carcass_cond.setGeometry(QRect(20, 230, 250, 30))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_carcass_cond.setFont(font1)
        self.rb_fresh = QRadioButton(self.gb_lab_request)
        self.rb_fresh.setObjectName(u"rb_fresh")
        self.rb_fresh.setGeometry(QRect(20, 260, 150, 30))
        self.rb_fresh.setFont(font)
        self.rb_autolysis = QRadioButton(self.gb_lab_request)
        self.rb_autolysis.setObjectName(u"rb_autolysis")
        self.rb_autolysis.setGeometry(QRect(180, 260, 180, 30))
        self.rb_autolysis.setFont(font)
        self.rb_unknown = QRadioButton(self.gb_lab_request)
        self.rb_unknown.setObjectName(u"rb_unknown")
        self.rb_unknown.setGeometry(QRect(370, 260, 180, 30))
        self.rb_unknown.setFont(font)
        self.rb_other_cond = QRadioButton(self.gb_lab_request)
        self.rb_other_cond.setObjectName(u"rb_other_cond")
        self.rb_other_cond.setGeometry(QRect(20, 290, 60, 30))
        self.rb_other_cond.setFont(font)
        self.le_other_cond = QLineEdit(self.gb_lab_request)
        self.le_other_cond.setObjectName(u"le_other_cond")
        self.le_other_cond.setGeometry(QRect(90, 290, 480, 30))
        self.le_other_cond.setFont(font)
        self.label_place = QLabel(self.gb_lab_request)
        self.label_place.setObjectName(u"label_place")
        self.label_place.setGeometry(QRect(20, 330, 300, 30))
        self.label_place.setFont(font1)
        self.rb_necropsy = QRadioButton(self.gb_lab_request)
        self.rb_necropsy.setObjectName(u"rb_necropsy")
        self.rb_necropsy.setGeometry(QRect(20, 360, 400, 30))
        self.rb_necropsy.setFont(font)
        self.rb_place_opt1 = QRadioButton(self.gb_lab_request)
        self.rb_place_opt1.setObjectName(u"rb_place_opt1")
        self.rb_place_opt1.setGeometry(QRect(20, 390, 20, 30))
        self.le_place_opt1 = QLineEdit(self.gb_lab_request)
        self.le_place_opt1.setObjectName(u"le_place_opt1")
        self.le_place_opt1.setGeometry(QRect(50, 390, 520, 30))
        self.le_place_opt1.setFont(font)
        self.label_remark_lab = QLabel(self.gb_lab_request)
        self.label_remark_lab.setObjectName(u"label_remark_lab")
        self.label_remark_lab.setGeometry(QRect(20, 425, 100, 30))
        self.label_remark_lab.setFont(font1)
        self.le_remark_lab = QLineEdit(self.gb_lab_request)
        self.le_remark_lab.setObjectName(u"le_remark_lab")
        self.le_remark_lab.setGeometry(QRect(120, 425, 450, 30))
        self.le_remark_lab.setFont(font)
        self.gb_infectious = QGroupBox(after_death_MainWindow)
        self.gb_infectious.setObjectName(u"gb_infectious")
        self.gb_infectious.setGeometry(QRect(20, 560, 600, 320))
        self.gb_infectious.setFont(font)
        self.lb_inf_qty = QLabel(self.gb_infectious)
        self.lb_inf_qty.setObjectName(u"lb_inf_qty")
        self.lb_inf_qty.setGeometry(QRect(350, 20, 100, 30))
        self.lb_inf_qty.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_inf_weight = QLabel(self.gb_infectious)
        self.lb_inf_weight.setObjectName(u"lb_inf_weight")
        self.lb_inf_weight.setGeometry(QRect(480, 20, 100, 30))
        self.lb_inf_weight.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rb_tissues = QRadioButton(self.gb_infectious)
        self.rb_tissues.setObjectName(u"rb_tissues")
        self.rb_tissues.setGeometry(QRect(10, 50, 330, 30))
        self.le_tissues_qty = QLineEdit(self.gb_infectious)
        self.le_tissues_qty.setObjectName(u"le_tissues_qty")
        self.le_tissues_qty.setGeometry(QRect(350, 50, 110, 30))
        self.le_tissues_w = QLineEdit(self.gb_infectious)
        self.le_tissues_w.setObjectName(u"le_tissues_w")
        self.le_tissues_w.setGeometry(QRect(480, 50, 110, 30))
        self.rb_needle = QRadioButton(self.gb_infectious)
        self.rb_needle.setObjectName(u"rb_needle")
        self.rb_needle.setGeometry(QRect(10, 90, 330, 30))
        self.le_needle_qty = QLineEdit(self.gb_infectious)
        self.le_needle_qty.setObjectName(u"le_needle_qty")
        self.le_needle_qty.setGeometry(QRect(350, 90, 110, 30))
        self.le_needle_w = QLineEdit(self.gb_infectious)
        self.le_needle_w.setObjectName(u"le_needle_w")
        self.le_needle_w.setGeometry(QRect(480, 90, 110, 30))
        self.rb_syringe = QRadioButton(self.gb_infectious)
        self.rb_syringe.setObjectName(u"rb_syringe")
        self.rb_syringe.setGeometry(QRect(10, 130, 330, 30))
        self.le_syringe_qty = QLineEdit(self.gb_infectious)
        self.le_syringe_qty.setObjectName(u"le_syringe_qty")
        self.le_syringe_qty.setGeometry(QRect(350, 130, 110, 30))
        self.le_syringe_w = QLineEdit(self.gb_infectious)
        self.le_syringe_w.setObjectName(u"le_syringe_w")
        self.le_syringe_w.setGeometry(QRect(480, 130, 110, 30))
        self.rb_inf_other1 = QRadioButton(self.gb_infectious)
        self.rb_inf_other1.setObjectName(u"rb_inf_other1")
        self.rb_inf_other1.setGeometry(QRect(10, 170, 20, 30))
        self.le_inf_other1_name = QLineEdit(self.gb_infectious)
        self.le_inf_other1_name.setObjectName(u"le_inf_other1_name")
        self.le_inf_other1_name.setGeometry(QRect(40, 170, 290, 30))
        self.le_inf_other1_qty = QLineEdit(self.gb_infectious)
        self.le_inf_other1_qty.setObjectName(u"le_inf_other1_qty")
        self.le_inf_other1_qty.setGeometry(QRect(350, 170, 110, 30))
        self.le_inf_other1_w = QLineEdit(self.gb_infectious)
        self.le_inf_other1_w.setObjectName(u"le_inf_other1_w")
        self.le_inf_other1_w.setGeometry(QRect(480, 170, 110, 30))
        self.rb_inf_other2 = QRadioButton(self.gb_infectious)
        self.rb_inf_other2.setObjectName(u"rb_inf_other2")
        self.rb_inf_other2.setGeometry(QRect(10, 210, 20, 30))
        self.le_inf_other2_name = QLineEdit(self.gb_infectious)
        self.le_inf_other2_name.setObjectName(u"le_inf_other2_name")
        self.le_inf_other2_name.setGeometry(QRect(40, 210, 290, 30))
        self.le_inf_other2_qty = QLineEdit(self.gb_infectious)
        self.le_inf_other2_qty.setObjectName(u"le_inf_other2_qty")
        self.le_inf_other2_qty.setGeometry(QRect(350, 210, 110, 30))
        self.le_inf_other2_w = QLineEdit(self.gb_infectious)
        self.le_inf_other2_w.setObjectName(u"le_inf_other2_w")
        self.le_inf_other2_w.setGeometry(QRect(480, 210, 110, 30))
        self.lb_inf_remark = QLabel(self.gb_infectious)
        self.lb_inf_remark.setObjectName(u"lb_inf_remark")
        self.lb_inf_remark.setGeometry(QRect(10, 250, 100, 30))
        self.lb_inf_remark.setFont(font1)
        self.le_inf_remark = QLineEdit(self.gb_infectious)
        self.le_inf_remark.setObjectName(u"le_inf_remark")
        self.le_inf_remark.setGeometry(QRect(10, 280, 580, 30))
        self.gb_gem = QGroupBox(after_death_MainWindow)
        self.gb_gem.setObjectName(u"gb_gem")
        self.gb_gem.setGeometry(QRect(630, 10, 500, 871))
        self.gb_gem.setFont(font)
        self.lb_gem_qty = QLabel(self.gb_gem)
        self.lb_gem_qty.setObjectName(u"lb_gem_qty")
        self.lb_gem_qty.setGeometry(QRect(250, 20, 110, 30))
        self.lb_gem_qty.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_gem_w = QLabel(self.gb_gem)
        self.lb_gem_w.setObjectName(u"lb_gem_w")
        self.lb_gem_w.setGeometry(QRect(380, 20, 110, 30))
        self.lb_gem_w.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rb_gem_carcass = QRadioButton(self.gb_gem)
        self.rb_gem_carcass.setObjectName(u"rb_gem_carcass")
        self.rb_gem_carcass.setGeometry(QRect(10, 50, 230, 30))
        self.le_gem_carcass_qty = QLineEdit(self.gb_gem)
        self.le_gem_carcass_qty.setObjectName(u"le_gem_carcass_qty")
        self.le_gem_carcass_qty.setGeometry(QRect(250, 50, 110, 30))
        self.le_gem_carcass_qty.setFont(font)
        self.le_gem_carcass_w = QLineEdit(self.gb_gem)
        self.le_gem_carcass_w.setObjectName(u"le_gem_carcass_w")
        self.le_gem_carcass_w.setGeometry(QRect(380, 50, 110, 30))
        self.le_gem_carcass_w.setFont(font)
        self.rb_gem_bone = QRadioButton(self.gb_gem)
        self.rb_gem_bone.setObjectName(u"rb_gem_bone")
        self.rb_gem_bone.setGeometry(QRect(10, 90, 230, 30))
        self.le_gem_bone_qty = QLineEdit(self.gb_gem)
        self.le_gem_bone_qty.setObjectName(u"le_gem_bone_qty")
        self.le_gem_bone_qty.setGeometry(QRect(250, 90, 110, 30))
        self.le_gem_bone_qty.setFont(font)
        self.le_gem_bone_w = QLineEdit(self.gb_gem)
        self.le_gem_bone_w.setObjectName(u"le_gem_bone_w")
        self.le_gem_bone_w.setGeometry(QRect(380, 90, 110, 30))
        self.le_gem_bone_w.setFont(font)
        self.rb_gem_hair = QRadioButton(self.gb_gem)
        self.rb_gem_hair.setObjectName(u"rb_gem_hair")
        self.rb_gem_hair.setGeometry(QRect(10, 130, 230, 30))
        self.le_gem_hair_qty = QLineEdit(self.gb_gem)
        self.le_gem_hair_qty.setObjectName(u"le_gem_hair_qty")
        self.le_gem_hair_qty.setGeometry(QRect(250, 130, 110, 30))
        self.le_gem_hair_qty.setFont(font)
        self.le_gem_hair_w = QLineEdit(self.gb_gem)
        self.le_gem_hair_w.setObjectName(u"le_gem_hair_w")
        self.le_gem_hair_w.setGeometry(QRect(380, 130, 110, 30))
        self.le_gem_hair_w.setFont(font)
        self.rb_gem_other1 = QRadioButton(self.gb_gem)
        self.rb_gem_other1.setObjectName(u"rb_gem_other1")
        self.rb_gem_other1.setGeometry(QRect(10, 170, 20, 30))
        self.le_gem_other1_name = QLineEdit(self.gb_gem)
        self.le_gem_other1_name.setObjectName(u"le_gem_other1_name")
        self.le_gem_other1_name.setGeometry(QRect(40, 170, 190, 30))
        self.le_gem_other1_name.setFont(font)
        self.le_gem_other1_qty = QLineEdit(self.gb_gem)
        self.le_gem_other1_qty.setObjectName(u"le_gem_other1_qty")
        self.le_gem_other1_qty.setGeometry(QRect(250, 170, 110, 30))
        self.le_gem_other1_qty.setFont(font)
        self.le_gem_other1_w = QLineEdit(self.gb_gem)
        self.le_gem_other1_w.setObjectName(u"le_gem_other1_w")
        self.le_gem_other1_w.setGeometry(QRect(380, 170, 110, 30))
        self.le_gem_other1_w.setFont(font)
        self.rb_gem_other2 = QRadioButton(self.gb_gem)
        self.rb_gem_other2.setObjectName(u"rb_gem_other2")
        self.rb_gem_other2.setGeometry(QRect(10, 210, 20, 30))
        self.le_gem_other2_name = QLineEdit(self.gb_gem)
        self.le_gem_other2_name.setObjectName(u"le_gem_other2_name")
        self.le_gem_other2_name.setGeometry(QRect(40, 210, 190, 30))
        self.le_gem_other2_name.setFont(font)
        self.le_gem_other2_qty = QLineEdit(self.gb_gem)
        self.le_gem_other2_qty.setObjectName(u"le_gem_other2_qty")
        self.le_gem_other2_qty.setGeometry(QRect(250, 210, 110, 30))
        self.le_gem_other2_qty.setFont(font)
        self.le_gem_other2_w = QLineEdit(self.gb_gem)
        self.le_gem_other2_w.setObjectName(u"le_gem_other2_w")
        self.le_gem_other2_w.setGeometry(QRect(380, 210, 110, 30))
        self.le_gem_other2_w.setFont(font)
        self.label_size = QLabel(self.gb_gem)
        self.label_size.setObjectName(u"label_size")
        self.label_size.setGeometry(QRect(10, 250, 100, 30))
        self.label_size.setFont(font1)
        self.rb_size_lt1 = QRadioButton(self.gb_gem)
        self.rb_size_lt1.setObjectName(u"rb_size_lt1")
        self.rb_size_lt1.setGeometry(QRect(10, 280, 220, 30))
        self.rb_size_lt1.setFont(font)
        self.rb_size_1c = QRadioButton(self.gb_gem)
        self.rb_size_1c.setObjectName(u"rb_size_1c")
        self.rb_size_1c.setGeometry(QRect(240, 280, 250, 30))
        self.rb_size_1c.setFont(font)
        self.rb_size_2c = QRadioButton(self.gb_gem)
        self.rb_size_2c.setObjectName(u"rb_size_2c")
        self.rb_size_2c.setGeometry(QRect(10, 310, 220, 30))
        self.rb_size_2c.setFont(font)
        self.rb_size_3c = QRadioButton(self.gb_gem)
        self.rb_size_3c.setObjectName(u"rb_size_3c")
        self.rb_size_3c.setGeometry(QRect(240, 310, 250, 30))
        self.rb_size_3c.setFont(font)
        self.rb_size_4c = QRadioButton(self.gb_gem)
        self.rb_size_4c.setObjectName(u"rb_size_4c")
        self.rb_size_4c.setGeometry(QRect(10, 340, 220, 30))
        self.rb_size_4c.setFont(font)
        self.rb_size_5c = QRadioButton(self.gb_gem)
        self.rb_size_5c.setObjectName(u"rb_size_5c")
        self.rb_size_5c.setGeometry(QRect(240, 340, 250, 30))
        self.rb_size_5c.setFont(font)
        self.label_shape = QLabel(self.gb_gem)
        self.label_shape.setObjectName(u"label_shape")
        self.label_shape.setGeometry(QRect(10, 380, 100, 30))
        self.label_shape.setFont(font1)
        self.rb_shape_round = QRadioButton(self.gb_gem)
        self.rb_shape_round.setObjectName(u"rb_shape_round")
        self.rb_shape_round.setGeometry(QRect(10, 410, 220, 30))
        self.rb_shape_round.setFont(font)
        self.rb_shape_oval = QRadioButton(self.gb_gem)
        self.rb_shape_oval.setObjectName(u"rb_shape_oval")
        self.rb_shape_oval.setGeometry(QRect(240, 410, 220, 30))
        self.rb_shape_oval.setFont(font)
        self.rb_shape_cushion = QRadioButton(self.gb_gem)
        self.rb_shape_cushion.setObjectName(u"rb_shape_cushion")
        self.rb_shape_cushion.setGeometry(QRect(10, 440, 220, 30))
        self.rb_shape_cushion.setFont(font)
        self.rb_shape_princess = QRadioButton(self.gb_gem)
        self.rb_shape_princess.setObjectName(u"rb_shape_princess")
        self.rb_shape_princess.setGeometry(QRect(240, 440, 220, 30))
        self.rb_shape_princess.setFont(font)
        self.rb_shape_radiant = QRadioButton(self.gb_gem)
        self.rb_shape_radiant.setObjectName(u"rb_shape_radiant")
        self.rb_shape_radiant.setGeometry(QRect(10, 470, 220, 30))
        self.rb_shape_radiant.setFont(font)
        self.rb_shape_marquise = QRadioButton(self.gb_gem)
        self.rb_shape_marquise.setObjectName(u"rb_shape_marquise")
        self.rb_shape_marquise.setGeometry(QRect(240, 470, 220, 30))
        self.rb_shape_marquise.setFont(font)
        self.rb_shape_other = QRadioButton(self.gb_gem)
        self.rb_shape_other.setObjectName(u"rb_shape_other")
        self.rb_shape_other.setGeometry(QRect(10, 500, 60, 30))
        self.rb_shape_other.setFont(font)
        self.le_shape_other = QLineEdit(self.gb_gem)
        self.le_shape_other.setObjectName(u"le_shape_other")
        self.le_shape_other.setGeometry(QRect(70, 500, 420, 30))
        self.le_shape_other.setFont(font)
        self.label_accessories = QLabel(self.gb_gem)
        self.label_accessories.setObjectName(u"label_accessories")
        self.label_accessories.setGeometry(QRect(10, 540, 250, 30))
        self.label_accessories.setFont(font1)
        self.rb_acc_ring = QRadioButton(self.gb_gem)
        self.rb_acc_ring.setObjectName(u"rb_acc_ring")
        self.rb_acc_ring.setGeometry(QRect(10, 570, 150, 30))
        self.rb_acc_ring.setFont(font)
        self.lb_acc_code1 = QLabel(self.gb_gem)
        self.lb_acc_code1.setObjectName(u"lb_acc_code1")
        self.lb_acc_code1.setGeometry(QRect(170, 570, 80, 30))
        self.lb_acc_code1.setFont(font)
        self.le_acc_code1 = QLineEdit(self.gb_gem)
        self.le_acc_code1.setObjectName(u"le_acc_code1")
        self.le_acc_code1.setGeometry(QRect(260, 570, 230, 30))
        self.le_acc_code1.setFont(font)
        self.rb_acc_necklace = QRadioButton(self.gb_gem)
        self.rb_acc_necklace.setObjectName(u"rb_acc_necklace")
        self.rb_acc_necklace.setGeometry(QRect(10, 610, 150, 30))
        self.rb_acc_necklace.setFont(font)
        self.lb_acc_code2 = QLabel(self.gb_gem)
        self.lb_acc_code2.setObjectName(u"lb_acc_code2")
        self.lb_acc_code2.setGeometry(QRect(170, 610, 80, 30))
        self.lb_acc_code2.setFont(font)
        self.le_acc_code2 = QLineEdit(self.gb_gem)
        self.le_acc_code2.setObjectName(u"le_acc_code2")
        self.le_acc_code2.setGeometry(QRect(260, 610, 230, 30))
        self.le_acc_code2.setFont(font)
        self.rb_acc_earing = QRadioButton(self.gb_gem)
        self.rb_acc_earing.setObjectName(u"rb_acc_earing")
        self.rb_acc_earing.setGeometry(QRect(10, 650, 150, 30))
        self.rb_acc_earing.setFont(font)
        self.lb_acc_code3 = QLabel(self.gb_gem)
        self.lb_acc_code3.setObjectName(u"lb_acc_code3")
        self.lb_acc_code3.setGeometry(QRect(170, 650, 80, 30))
        self.lb_acc_code3.setFont(font)
        self.le_acc_code3 = QLineEdit(self.gb_gem)
        self.le_acc_code3.setObjectName(u"le_acc_code3")
        self.le_acc_code3.setGeometry(QRect(260, 650, 230, 30))
        self.le_acc_code3.setFont(font)
        self.lb_color = QLabel(self.gb_gem)
        self.lb_color.setObjectName(u"lb_color")
        self.lb_color.setGeometry(QRect(10, 690, 80, 30))
        self.lb_color.setFont(font)
        self.le_color = QLineEdit(self.gb_gem)
        self.le_color.setObjectName(u"le_color")
        self.le_color.setGeometry(QRect(100, 690, 390, 30))
        self.le_color.setFont(font)
        self.lb_price = QLabel(self.gb_gem)
        self.lb_price.setObjectName(u"lb_price")
        self.lb_price.setGeometry(QRect(10, 730, 80, 30))
        self.lb_price.setFont(font)
        self.le_price = QLineEdit(self.gb_gem)
        self.le_price.setObjectName(u"le_price")
        self.le_price.setGeometry(QRect(100, 730, 390, 30))
        self.le_price.setFont(font)
        self.label_remark_gem = QLabel(self.gb_gem)
        self.label_remark_gem.setObjectName(u"label_remark_gem")
        self.label_remark_gem.setGeometry(QRect(10, 770, 80, 20))
        self.label_remark_gem.setFont(font1)
        self.pte_remark_gem = QPlainTextEdit(self.gb_gem)
        self.pte_remark_gem.setObjectName(u"pte_remark_gem")
        self.pte_remark_gem.setGeometry(QRect(9, 795, 481, 61))
        self.pte_remark_gem.setFont(font)
        self.btn_save = QPushButton(after_death_MainWindow)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(1139, 20, 131, 50))
        self.btn_save.setFont(font)
        self.btn_cancel = QPushButton(after_death_MainWindow)
        self.btn_cancel.setObjectName(u"btn_cancel")
        self.btn_cancel.setGeometry(QRect(1140, 80, 131, 50))
        self.btn_cancel.setFont(font)

        self.retranslateUi(after_death_MainWindow)

        QMetaObject.connectSlotsByName(after_death_MainWindow)
    # setupUi

    def retranslateUi(self, after_death_MainWindow):
        after_death_MainWindow.setWindowTitle(QCoreApplication.translate("after_death_MainWindow", u"Service Request Form", None))
        after_death_MainWindow.setStyleSheet("")
        self.gb_service_type.setTitle(QCoreApplication.translate("after_death_MainWindow", u"\u0e07\u0e32\u0e19\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e2b\u0e25\u0e31\u0e07\u0e04\u0e27\u0e32\u0e21\u0e15\u0e32\u0e22", None))
        self.rb_waste.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.rb_cremation.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e1c\u0e32\u0e0b\u0e32\u0e01", None))
        self.rb_jewelry.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35", None))
        self.gb_lab_request.setTitle(QCoreApplication.translate("after_death_MainWindow", u"LABORATORY REQUEST", None))
        self.rb_incineration.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e1c\u0e32\u0e0b\u0e32\u0e01(Incineration) \u0e23\u0e32\u0e04\u0e32 400/40x", None))
        self.label_kg.setText(QCoreApplication.translate("after_death_MainWindow", u"KG", None))
        self.rb_bone_storage.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e01\u0e47\u0e1a\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01 (Incineration and bone/ash storage)(200)", None))
        self.rb_ceremony.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e17\u0e33\u0e1e\u0e34\u0e18\u0e35\u0e17\u0e32\u0e07\u0e28\u0e32\u0e2a\u0e19\u0e32(Cremation ceremony)", None))
        self.label_date.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48(DATE)", None))
        self.label_time.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e27\u0e25\u0e32(TIME)", None))
        self.rb_diamond_mem.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e17\u0e33\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35 (Daimond of memory)", None))
        self.label_carcass_cond.setText(QCoreApplication.translate("after_death_MainWindow", u"CARCASS CONDITION", None))
        self.rb_fresh.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e0b\u0e32\u0e01\u0e2a\u0e14 (Fresh)", None))
        self.rb_autolysis.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e0b\u0e32\u0e01\u0e40\u0e19\u0e48\u0e32 (Autolysis)", None))
        self.rb_unknown.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a (Unknown)", None))
        self.rb_other_cond.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.label_place.setText(QCoreApplication.translate("after_death_MainWindow", u"PLACE OF CARCASS", None))
        self.rb_necropsy.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e01\u0e47\u0e1a\u0e0b\u0e32\u0e01\u0e17\u0e35\u0e48\u0e2b\u0e49\u0e2d\u0e07\u0e1c\u0e48\u0e32\u0e0b\u0e32\u0e01 (-20 Necropsy Hall)", None))
        self.rb_place_opt1.setText("")
        self.label_remark_lab.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2b\u0e21\u0e32\u0e22\u0e40\u0e2b\u0e15\u0e38", None))
        self.gb_infectious.setTitle(QCoreApplication.translate("after_death_MainWindow", u"\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.lb_inf_qty.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.lb_inf_weight.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01(KG)", None))
        self.rb_tissues.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e19\u0e37\u0e49\u0e2d\u0e40\u0e22\u0e37\u0e48\u0e2d\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectious Tissues)", None))
        self.rb_needle.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e02\u0e47\u0e21\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectious Needle)", None))
        self.rb_syringe.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e44\u0e0b\u0e23\u0e34\u0e07\u0e04\u0e4c\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectious Syringe)", None))
        self.rb_inf_other1.setText("")
        self.rb_inf_other2.setText("")
        self.lb_inf_remark.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2b\u0e21\u0e32\u0e22\u0e40\u0e2b\u0e15\u0e38", None))
        self.gb_gem.setTitle(QCoreApplication.translate("after_death_MainWindow", u"\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35", None))
        self.lb_gem_qty.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.lb_gem_w.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01(KG)", None))
        self.rb_gem_carcass.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e0b\u0e32\u0e01\u0e2a\u0e31\u0e15\u0e27\u0e4c(Carcass)", None))
        self.rb_gem_bone.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01\u0e2a\u0e31\u0e15\u0e27\u0e4c(Bone)", None))
        self.rb_gem_hair.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e02\u0e19\u0e2a\u0e31\u0e15\u0e27\u0e4c(Hair/feather)", None))
        self.rb_gem_other1.setText("")
        self.rb_gem_other2.setText("")
        self.label_size.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e02\u0e19\u0e32\u0e14", None))
        self.rb_size_lt1.setText(QCoreApplication.translate("after_death_MainWindow", u"<1 carat (4700)", None))
        self.rb_size_1c.setText(QCoreApplication.translate("after_death_MainWindow", u"1 carat 6.4 mm (5800)", None))
        self.rb_size_2c.setText(QCoreApplication.translate("after_death_MainWindow", u"2 carat 8.1 mm (6800)", None))
        self.rb_size_3c.setText(QCoreApplication.translate("after_death_MainWindow", u"3 carat 9.3 mm (7900)", None))
        self.rb_size_4c.setText(QCoreApplication.translate("after_death_MainWindow", u"4 carat 10.2 mm (9000)", None))
        self.rb_size_5c.setText(QCoreApplication.translate("after_death_MainWindow", u"5 carat 11.0 mm (10100)", None))
        self.label_shape.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e39\u0e1b\u0e17\u0e23\u0e07", None))
        self.rb_shape_round.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e01\u0e25\u0e21(round)", None))
        self.rb_shape_oval.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e35(oval)", None))
        self.rb_shape_cushion.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e17\u0e23\u0e07\u0e2b\u0e21\u0e2d\u0e19(cushion)", None))
        self.rb_shape_princess.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2a\u0e35\u0e48\u0e40\u0e2b\u0e25\u0e35\u0e48\u0e22\u0e21(princess)", None))
        self.rb_shape_radiant.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2a\u0e35\u0e48\u0e40\u0e2b\u0e25\u0e35\u0e48\u0e22\u0e21\u0e1c\u0e37\u0e19\u0e1c\u0e49\u0e32(radiant)", None))
        self.rb_shape_marquise.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e17\u0e23\u0e07\u0e21\u0e32\u0e23\u0e4c\u0e04\u0e35\u0e22\u0e4c(marquise)", None))
        self.rb_shape_other.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.label_accessories.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e1b\u0e23\u0e30\u0e14\u0e31\u0e1a(Accessories)", None))
        self.rb_acc_ring.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e41\u0e2b\u0e27\u0e19 (ring)", None))
        self.lb_acc_code1.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.rb_acc_necklace.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2a\u0e23\u0e49\u0e2d\u0e22\u0e04\u0e2d (necklace)", None))
        self.lb_acc_code2.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.rb_acc_earing.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e15\u0e48\u0e32\u0e07\u0e2b\u0e39 (earing)", None))
        self.lb_acc_code3.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.lb_color.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e2a\u0e35(color)", None))
        self.lb_price.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e23\u0e32\u0e04\u0e32(price)", None))
        self.label_remark_gem.setText(QCoreApplication.translate("after_death_MainWindow", u"REMARK", None))
        self.btn_save.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.btn_cancel.setText(QCoreApplication.translate("after_death_MainWindow", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
    # retranslateUi

