# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'edit_employee.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QTreeWidget, QTreeWidgetItem, QWidget)

class Ui_edit_employee_MainWindow(object):
    def setupUi(self, edit_employee_MainWindow):
        if not edit_employee_MainWindow.objectName():
            edit_employee_MainWindow.setObjectName(u"edit_employee_MainWindow")
        edit_employee_MainWindow.resize(1270, 890)
        edit_employee_MainWindow.setMinimumSize(QSize(1270, 890))
        edit_employee_MainWindow.setMaximumSize(QSize(1270, 890))
        self.centralwidget = QWidget(edit_employee_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1270, 440))
        self.frame.setMinimumSize(QSize(1270, 440))
        self.frame.setMaximumSize(QSize(1270, 440))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.employee_search_label = QLabel(self.frame)
        self.employee_search_label.setObjectName(u"employee_search_label")
        self.employee_search_label.setGeometry(QRect(10, 10, 250, 40))
        self.employee_search_label.setMinimumSize(QSize(250, 40))
        self.employee_search_label.setMaximumSize(QSize(250, 40))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        self.employee_search_label.setFont(font)
        self.employee_search_lineEdit = QLineEdit(self.frame)
        self.employee_search_lineEdit.setObjectName(u"employee_search_lineEdit")
        self.employee_search_lineEdit.setGeometry(QRect(280, 10, 790, 40))
        self.employee_search_lineEdit.setMinimumSize(QSize(790, 40))
        self.employee_search_lineEdit.setMaximumSize(QSize(790, 40))
        self.employee_search_lineEdit.setFont(font)
        self.employee_search_pushButton = QPushButton(self.frame)
        self.employee_search_pushButton.setObjectName(u"employee_search_pushButton")
        self.employee_search_pushButton.setGeometry(QRect(1090, 10, 170, 40))
        self.employee_search_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_search_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_search_pushButton.setFont(font)
        self.employee_new_pushButton = QPushButton(self.frame)
        self.employee_new_pushButton.setObjectName(u"employee_new_pushButton")
        self.employee_new_pushButton.setGeometry(QRect(1090, 70, 170, 40))
        self.employee_new_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_new_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_new_pushButton.setFont(font)
        self.employee_edit_pushButton = QPushButton(self.frame)
        self.employee_edit_pushButton.setObjectName(u"employee_edit_pushButton")
        self.employee_edit_pushButton.setGeometry(QRect(1090, 130, 170, 40))
        self.employee_edit_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_edit_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_edit_pushButton.setFont(font)
        self.employee_delete_pushButton = QPushButton(self.frame)
        self.employee_delete_pushButton.setObjectName(u"employee_delete_pushButton")
        self.employee_delete_pushButton.setGeometry(QRect(1090, 190, 170, 40))
        self.employee_delete_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_delete_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_delete_pushButton.setFont(font)
        self.employee_back_pushButton = QPushButton(self.frame)
        self.employee_back_pushButton.setObjectName(u"employee_back_pushButton")
        self.employee_back_pushButton.setGeometry(QRect(1090, 390, 170, 40))
        self.employee_back_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_back_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_back_pushButton.setFont(font)
        self.employee_treeWidget = QTreeWidget(self.frame)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setFont(2, font);
        __qtreewidgetitem.setFont(1, font);
        __qtreewidgetitem.setFont(0, font);
        self.employee_treeWidget.setHeaderItem(__qtreewidgetitem)
        self.employee_treeWidget.setObjectName(u"employee_treeWidget")
        self.employee_treeWidget.setGeometry(QRect(10, 70, 1060, 360))
        self.employee_treeWidget.setMinimumSize(QSize(1060, 360))
        self.employee_treeWidget.setMaximumSize(QSize(1060, 360))
        self.employee_treeWidget.setFont(font)
        self.employee_treeWidget.header().setCascadingSectionResizes(False)
        self.employee_treeWidget.header().setMinimumSectionSize(100)
        self.employee_treeWidget.header().setDefaultSectionSize(350)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 440, 1270, 440))
        self.frame_2.setMinimumSize(QSize(1270, 440))
        self.frame_2.setMaximumSize(QSize(1270, 440))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.employee_edit_signature_pushButton = QPushButton(self.frame_2)
        self.employee_edit_signature_pushButton.setObjectName(u"employee_edit_signature_pushButton")
        self.employee_edit_signature_pushButton.setGeometry(QRect(1090, 10, 170, 40))
        self.employee_edit_signature_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_edit_signature_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_edit_signature_pushButton.setFont(font)
        self.employee_save_pushButton = QPushButton(self.frame_2)
        self.employee_save_pushButton.setObjectName(u"employee_save_pushButton")
        self.employee_save_pushButton.setGeometry(QRect(1090, 390, 170, 40))
        self.employee_save_pushButton.setMinimumSize(QSize(170, 40))
        self.employee_save_pushButton.setMaximumSize(QSize(170, 40))
        self.employee_save_pushButton.setFont(font)
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(600, 10, 470, 410))
        self.frame_3.setMinimumSize(QSize(470, 410))
        self.frame_3.setMaximumSize(QSize(470, 410))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.employee_signature_frame = QFrame(self.frame_2)
        self.employee_signature_frame.setObjectName(u"employee_signature_frame")
        self.employee_signature_frame.setGeometry(QRect(600, 20, 470, 410))
        self.employee_signature_frame.setMinimumSize(QSize(470, 410))
        self.employee_signature_frame.setMaximumSize(QSize(470, 410))
        self.employee_signature_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.employee_signature_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.employee_title_label = QLabel(self.frame_2)
        self.employee_title_label.setObjectName(u"employee_title_label")
        self.employee_title_label.setGeometry(QRect(10, 20, 110, 40))
        self.employee_title_label.setMinimumSize(QSize(110, 40))
        self.employee_title_label.setMaximumSize(QSize(110, 40))
        self.employee_title_label.setFont(font)
        self.employee_title_lineEdit = QLineEdit(self.frame_2)
        self.employee_title_lineEdit.setObjectName(u"employee_title_lineEdit")
        self.employee_title_lineEdit.setGeometry(QRect(130, 20, 450, 40))
        self.employee_title_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_title_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_title_lineEdit.setFont(font)
        self.employee_name_label = QLabel(self.frame_2)
        self.employee_name_label.setObjectName(u"employee_name_label")
        self.employee_name_label.setGeometry(QRect(10, 80, 110, 40))
        self.employee_name_label.setMinimumSize(QSize(110, 40))
        self.employee_name_label.setMaximumSize(QSize(110, 40))
        self.employee_name_label.setFont(font)
        self.employee_surname_label = QLabel(self.frame_2)
        self.employee_surname_label.setObjectName(u"employee_surname_label")
        self.employee_surname_label.setGeometry(QRect(10, 140, 110, 40))
        self.employee_surname_label.setMinimumSize(QSize(110, 40))
        self.employee_surname_label.setMaximumSize(QSize(110, 40))
        self.employee_surname_label.setFont(font)
        self.employee_email_label = QLabel(self.frame_2)
        self.employee_email_label.setObjectName(u"employee_email_label")
        self.employee_email_label.setGeometry(QRect(10, 200, 110, 40))
        self.employee_email_label.setMinimumSize(QSize(110, 40))
        self.employee_email_label.setMaximumSize(QSize(110, 40))
        self.employee_email_label.setFont(font)
        self.employee_username_label = QLabel(self.frame_2)
        self.employee_username_label.setObjectName(u"employee_username_label")
        self.employee_username_label.setGeometry(QRect(10, 260, 110, 40))
        self.employee_username_label.setMinimumSize(QSize(110, 40))
        self.employee_username_label.setMaximumSize(QSize(110, 40))
        self.employee_username_label.setFont(font)
        self.employee_password_label = QLabel(self.frame_2)
        self.employee_password_label.setObjectName(u"employee_password_label")
        self.employee_password_label.setGeometry(QRect(10, 320, 110, 40))
        self.employee_password_label.setMinimumSize(QSize(110, 40))
        self.employee_password_label.setMaximumSize(QSize(110, 40))
        self.employee_password_label.setFont(font)
        self.employee_position_label = QLabel(self.frame_2)
        self.employee_position_label.setObjectName(u"employee_position_label")
        self.employee_position_label.setGeometry(QRect(10, 380, 110, 40))
        self.employee_position_label.setMinimumSize(QSize(110, 40))
        self.employee_position_label.setMaximumSize(QSize(110, 40))
        self.employee_position_label.setFont(font)
        self.employee_name_lineEdit = QLineEdit(self.frame_2)
        self.employee_name_lineEdit.setObjectName(u"employee_name_lineEdit")
        self.employee_name_lineEdit.setGeometry(QRect(130, 80, 450, 40))
        self.employee_name_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_name_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_name_lineEdit.setFont(font)
        self.employee_surname_lineEdit = QLineEdit(self.frame_2)
        self.employee_surname_lineEdit.setObjectName(u"employee_surname_lineEdit")
        self.employee_surname_lineEdit.setGeometry(QRect(130, 140, 450, 40))
        self.employee_surname_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_surname_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_surname_lineEdit.setFont(font)
        self.employee_email_lineEdit = QLineEdit(self.frame_2)
        self.employee_email_lineEdit.setObjectName(u"employee_email_lineEdit")
        self.employee_email_lineEdit.setGeometry(QRect(130, 200, 450, 40))
        self.employee_email_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_email_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_email_lineEdit.setFont(font)
        self.employee_username_lineEdit = QLineEdit(self.frame_2)
        self.employee_username_lineEdit.setObjectName(u"employee_username_lineEdit")
        self.employee_username_lineEdit.setGeometry(QRect(130, 260, 450, 40))
        self.employee_username_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_username_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_username_lineEdit.setFont(font)
        self.employee_password_lineEdit = QLineEdit(self.frame_2)
        self.employee_password_lineEdit.setObjectName(u"employee_password_lineEdit")
        self.employee_password_lineEdit.setGeometry(QRect(130, 320, 450, 40))
        self.employee_password_lineEdit.setMinimumSize(QSize(450, 40))
        self.employee_password_lineEdit.setMaximumSize(QSize(450, 40))
        self.employee_password_lineEdit.setFont(font)
        self.employee_position_comboBox = QComboBox(self.frame_2)
        self.employee_position_comboBox.setObjectName(u"employee_position_comboBox")
        self.employee_position_comboBox.setGeometry(QRect(130, 380, 300, 40))
        self.employee_position_comboBox.setMinimumSize(QSize(300, 40))
        self.employee_position_comboBox.setMaximumSize(QSize(300, 40))
        self.employee_position_comboBox.setFont(font)
        edit_employee_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(edit_employee_MainWindow)

        QMetaObject.connectSlotsByName(edit_employee_MainWindow)
    # setupUi

    def retranslateUi(self, edit_employee_MainWindow):
        edit_employee_MainWindow.setWindowTitle(QCoreApplication.translate("edit_employee_MainWindow", u"MainWindow", None))
        self.employee_search_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d\u0e2b\u0e23\u0e37\u0e2d\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e04\u0e49\u0e19\u0e2b\u0e32", None))
        self.employee_search_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e04\u0e49\u0e19\u0e2b\u0e32", None))
        self.employee_new_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e1a\u0e38\u0e04\u0e25\u0e32\u0e01\u0e23\u0e43\u0e2b\u0e21\u0e48", None))
        self.employee_edit_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e41\u0e01\u0e49\u0e44\u0e02\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.employee_delete_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e25\u0e1a\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.employee_back_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e01\u0e25\u0e31\u0e1a\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        ___qtreewidgetitem = self.employee_treeWidget.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("edit_employee_MainWindow", u"\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("edit_employee_MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("edit_employee_MainWindow", u"\u0e04\u0e33\u0e19\u0e33\u0e2b\u0e19\u0e49\u0e32\u0e0a\u0e37\u0e48\u0e2d", None));
        self.employee_edit_signature_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e41\u0e01\u0e49\u0e44\u0e02\u0e25\u0e32\u0e22\u0e40\u0e0b\u0e47\u0e19", None))
        self.employee_save_pushButton.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.employee_title_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e04\u0e33\u0e19\u0e33\u0e2b\u0e19\u0e49\u0e32\u0e0a\u0e37\u0e48\u0e2d", None))
        self.employee_name_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d", None))
        self.employee_surname_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None))
        self.employee_email_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"Email", None))
        self.employee_username_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"Username", None))
        self.employee_password_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"Password", None))
        self.employee_position_label.setText(QCoreApplication.translate("edit_employee_MainWindow", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07", None))
    # retranslateUi

