# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'molecular_biology.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QWidget)

class Ui_molecular_biology_MainWindow(object):
    def setupUi(self, molecular_biology_MainWindow):
        if not molecular_biology_MainWindow.objectName():
            molecular_biology_MainWindow.setObjectName(u"molecular_biology_MainWindow")
        molecular_biology_MainWindow.resize(1270, 890)
        self.centralwidget = QWidget(molecular_biology_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.l_av_t = QLabel(self.centralwidget)
        self.l_av_t.setObjectName(u"l_av_t")
        self.l_av_t.setGeometry(QRect(10, 8, 230, 30))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.l_av_t.setFont(font)
        self.l_av_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_av_t.setFrameShape(QFrame.Shape.Box)
        self.l_av_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_av_s = QLabel(self.centralwidget)
        self.l_av_s.setObjectName(u"l_av_s")
        self.l_av_s.setGeometry(QRect(240, 8, 100, 30))
        self.l_av_s.setFont(font)
        self.l_av_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_av_s.setFrameShape(QFrame.Shape.Box)
        self.l_av_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_av = QFrame(self.centralwidget)
        self.box_av.setObjectName(u"box_av")
        self.box_av.setGeometry(QRect(10, 40, 330, 381))
        self.box_av.setFrameShape(QFrame.Shape.Box)
        self.c_av1 = QCheckBox(self.box_av)
        self.c_av1.setObjectName(u"c_av1")
        self.c_av1.setGeometry(QRect(10, 10, 230, 25))
        self.c_av1.setFont(font)
        self.e_av1 = QLineEdit(self.box_av)
        self.e_av1.setObjectName(u"e_av1")
        self.e_av1.setGeometry(QRect(250, 10, 70, 25))
        self.c_av2 = QCheckBox(self.box_av)
        self.c_av2.setObjectName(u"c_av2")
        self.c_av2.setGeometry(QRect(10, 40, 230, 25))
        self.c_av2.setFont(font)
        self.e_av2 = QLineEdit(self.box_av)
        self.e_av2.setObjectName(u"e_av2")
        self.e_av2.setGeometry(QRect(250, 40, 70, 25))
        self.c_av3 = QCheckBox(self.box_av)
        self.c_av3.setObjectName(u"c_av3")
        self.c_av3.setGeometry(QRect(10, 70, 230, 25))
        self.c_av3.setFont(font)
        self.e_av3 = QLineEdit(self.box_av)
        self.e_av3.setObjectName(u"e_av3")
        self.e_av3.setGeometry(QRect(250, 70, 70, 25))
        self.c_av4 = QCheckBox(self.box_av)
        self.c_av4.setObjectName(u"c_av4")
        self.c_av4.setGeometry(QRect(10, 100, 230, 25))
        self.c_av4.setFont(font)
        self.e_av4 = QLineEdit(self.box_av)
        self.e_av4.setObjectName(u"e_av4")
        self.e_av4.setGeometry(QRect(250, 100, 70, 25))
        self.c_av5 = QCheckBox(self.box_av)
        self.c_av5.setObjectName(u"c_av5")
        self.c_av5.setGeometry(QRect(10, 130, 230, 25))
        self.c_av5.setFont(font)
        self.e_av5 = QLineEdit(self.box_av)
        self.e_av5.setObjectName(u"e_av5")
        self.e_av5.setGeometry(QRect(250, 130, 70, 25))
        self.c_av6 = QCheckBox(self.box_av)
        self.c_av6.setObjectName(u"c_av6")
        self.c_av6.setGeometry(QRect(10, 160, 230, 25))
        self.c_av6.setFont(font)
        self.e_av6 = QLineEdit(self.box_av)
        self.e_av6.setObjectName(u"e_av6")
        self.e_av6.setGeometry(QRect(250, 160, 70, 25))
        self.c_av7 = QCheckBox(self.box_av)
        self.c_av7.setObjectName(u"c_av7")
        self.c_av7.setGeometry(QRect(10, 190, 230, 25))
        self.c_av7.setFont(font)
        self.e_av7 = QLineEdit(self.box_av)
        self.e_av7.setObjectName(u"e_av7")
        self.e_av7.setGeometry(QRect(250, 190, 70, 25))
        self.c_av8 = QCheckBox(self.box_av)
        self.c_av8.setObjectName(u"c_av8")
        self.c_av8.setGeometry(QRect(10, 220, 230, 25))
        self.c_av8.setFont(font)
        self.e_av8 = QLineEdit(self.box_av)
        self.e_av8.setObjectName(u"e_av8")
        self.e_av8.setGeometry(QRect(250, 220, 70, 25))
        self.c_av9 = QCheckBox(self.box_av)
        self.c_av9.setObjectName(u"c_av9")
        self.c_av9.setGeometry(QRect(10, 250, 230, 25))
        self.c_av9.setFont(font)
        self.e_av9 = QLineEdit(self.box_av)
        self.e_av9.setObjectName(u"e_av9")
        self.e_av9.setGeometry(QRect(250, 250, 70, 25))
        self.c_av10 = QCheckBox(self.box_av)
        self.c_av10.setObjectName(u"c_av10")
        self.c_av10.setGeometry(QRect(10, 280, 230, 25))
        self.c_av10.setFont(font)
        self.e_av10 = QLineEdit(self.box_av)
        self.e_av10.setObjectName(u"e_av10")
        self.e_av10.setGeometry(QRect(250, 280, 70, 25))
        self.c_av11 = QCheckBox(self.box_av)
        self.c_av11.setObjectName(u"c_av11")
        self.c_av11.setGeometry(QRect(10, 310, 230, 25))
        self.c_av11.setFont(font)
        self.e_av11 = QLineEdit(self.box_av)
        self.e_av11.setObjectName(u"e_av11")
        self.e_av11.setGeometry(QRect(250, 310, 70, 25))
        self.c_av12 = QCheckBox(self.box_av)
        self.c_av12.setObjectName(u"c_av12")
        self.c_av12.setGeometry(QRect(10, 340, 230, 25))
        self.c_av12.setFont(font)
        self.e_av12 = QLineEdit(self.box_av)
        self.e_av12.setObjectName(u"e_av12")
        self.e_av12.setGeometry(QRect(250, 340, 70, 25))
        self.l_fel_t = QLabel(self.centralwidget)
        self.l_fel_t.setObjectName(u"l_fel_t")
        self.l_fel_t.setGeometry(QRect(10, 428, 230, 30))
        self.l_fel_t.setFont(font)
        self.l_fel_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_fel_t.setFrameShape(QFrame.Shape.Box)
        self.l_fel_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_fel_s = QLabel(self.centralwidget)
        self.l_fel_s.setObjectName(u"l_fel_s")
        self.l_fel_s.setGeometry(QRect(240, 428, 100, 30))
        self.l_fel_s.setFont(font)
        self.l_fel_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_fel_s.setFrameShape(QFrame.Shape.Box)
        self.l_fel_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_fel = QFrame(self.centralwidget)
        self.box_fel.setObjectName(u"box_fel")
        self.box_fel.setGeometry(QRect(10, 460, 330, 141))
        self.box_fel.setFrameShape(QFrame.Shape.Box)
        self.c_fe1 = QCheckBox(self.box_fel)
        self.c_fe1.setObjectName(u"c_fe1")
        self.c_fe1.setGeometry(QRect(10, 10, 230, 25))
        self.c_fe1.setFont(font)
        self.e_fe1 = QLineEdit(self.box_fel)
        self.e_fe1.setObjectName(u"e_fe1")
        self.e_fe1.setGeometry(QRect(250, 10, 70, 25))
        self.c_fe2 = QCheckBox(self.box_fel)
        self.c_fe2.setObjectName(u"c_fe2")
        self.c_fe2.setGeometry(QRect(10, 40, 230, 25))
        self.c_fe2.setFont(font)
        self.e_fe2 = QLineEdit(self.box_fel)
        self.e_fe2.setObjectName(u"e_fe2")
        self.e_fe2.setGeometry(QRect(250, 40, 70, 25))
        self.c_fe3 = QCheckBox(self.box_fel)
        self.c_fe3.setObjectName(u"c_fe3")
        self.c_fe3.setGeometry(QRect(10, 70, 230, 25))
        self.c_fe3.setFont(font)
        self.e_fe3 = QLineEdit(self.box_fel)
        self.e_fe3.setObjectName(u"e_fe3")
        self.e_fe3.setGeometry(QRect(250, 70, 70, 25))
        self.c_fe4 = QCheckBox(self.box_fel)
        self.c_fe4.setObjectName(u"c_fe4")
        self.c_fe4.setGeometry(QRect(10, 100, 230, 25))
        self.c_fe4.setFont(font)
        self.e_fe4 = QLineEdit(self.box_fel)
        self.e_fe4.setObjectName(u"e_fe4")
        self.e_fe4.setGeometry(QRect(250, 100, 70, 25))
        self.l_can_t = QLabel(self.centralwidget)
        self.l_can_t.setObjectName(u"l_can_t")
        self.l_can_t.setGeometry(QRect(10, 618, 230, 30))
        self.l_can_t.setFont(font)
        self.l_can_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_can_t.setFrameShape(QFrame.Shape.Box)
        self.l_can_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_can_s = QLabel(self.centralwidget)
        self.l_can_s.setObjectName(u"l_can_s")
        self.l_can_s.setGeometry(QRect(240, 618, 100, 30))
        self.l_can_s.setFont(font)
        self.l_can_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_can_s.setFrameShape(QFrame.Shape.Box)
        self.l_can_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_can = QFrame(self.centralwidget)
        self.box_can.setObjectName(u"box_can")
        self.box_can.setGeometry(QRect(10, 650, 330, 81))
        self.box_can.setFrameShape(QFrame.Shape.Box)
        self.c_cn1 = QCheckBox(self.box_can)
        self.c_cn1.setObjectName(u"c_cn1")
        self.c_cn1.setGeometry(QRect(10, 10, 230, 25))
        self.c_cn1.setFont(font)
        self.e_cn1 = QLineEdit(self.box_can)
        self.e_cn1.setObjectName(u"e_cn1")
        self.e_cn1.setGeometry(QRect(250, 10, 70, 25))
        self.c_cn2 = QCheckBox(self.box_can)
        self.c_cn2.setObjectName(u"c_cn2")
        self.c_cn2.setGeometry(QRect(10, 40, 230, 25))
        self.c_cn2.setFont(font)
        self.e_cn2 = QLineEdit(self.box_can)
        self.e_cn2.setObjectName(u"e_cn2")
        self.e_cn2.setGeometry(QRect(250, 40, 70, 25))
        self.l_eq_t = QLabel(self.centralwidget)
        self.l_eq_t.setObjectName(u"l_eq_t")
        self.l_eq_t.setGeometry(QRect(10, 738, 230, 30))
        self.l_eq_t.setFont(font)
        self.l_eq_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_eq_t.setFrameShape(QFrame.Shape.Box)
        self.l_eq_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_eq_s = QLabel(self.centralwidget)
        self.l_eq_s.setObjectName(u"l_eq_s")
        self.l_eq_s.setGeometry(QRect(240, 738, 100, 30))
        self.l_eq_s.setFont(font)
        self.l_eq_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_eq_s.setFrameShape(QFrame.Shape.Box)
        self.l_eq_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_eq = QFrame(self.centralwidget)
        self.box_eq.setObjectName(u"box_eq")
        self.box_eq.setGeometry(QRect(10, 770, 330, 91))
        self.box_eq.setFrameShape(QFrame.Shape.Box)
        self.c_eq1 = QCheckBox(self.box_eq)
        self.c_eq1.setObjectName(u"c_eq1")
        self.c_eq1.setGeometry(QRect(10, 10, 230, 25))
        self.c_eq1.setFont(font)
        self.e_eq1 = QLineEdit(self.box_eq)
        self.e_eq1.setObjectName(u"e_eq1")
        self.e_eq1.setGeometry(QRect(250, 10, 70, 25))
        self.c_eq2 = QCheckBox(self.box_eq)
        self.c_eq2.setObjectName(u"c_eq2")
        self.c_eq2.setGeometry(QRect(10, 40, 230, 25))
        self.c_eq2.setFont(font)
        self.e_eq2 = QLineEdit(self.box_eq)
        self.e_eq2.setObjectName(u"e_eq2")
        self.e_eq2.setGeometry(QRect(250, 40, 70, 25))
        self.l_bp1_t = QLabel(self.centralwidget)
        self.l_bp1_t.setObjectName(u"l_bp1_t")
        self.l_bp1_t.setGeometry(QRect(355, 8, 230, 30))
        self.l_bp1_t.setFont(font)
        self.l_bp1_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bp1_t.setFrameShape(QFrame.Shape.Box)
        self.l_bp1_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_bp1_s = QLabel(self.centralwidget)
        self.l_bp1_s.setObjectName(u"l_bp1_s")
        self.l_bp1_s.setGeometry(QRect(585, 8, 100, 30))
        self.l_bp1_s.setFont(font)
        self.l_bp1_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bp1_s.setFrameShape(QFrame.Shape.Box)
        self.l_bp1_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_bp1 = QFrame(self.centralwidget)
        self.box_bp1.setObjectName(u"box_bp1")
        self.box_bp1.setGeometry(QRect(355, 40, 330, 271))
        self.box_bp1.setFrameShape(QFrame.Shape.Box)
        self.c_bp1_1 = QCheckBox(self.box_bp1)
        self.c_bp1_1.setObjectName(u"c_bp1_1")
        self.c_bp1_1.setGeometry(QRect(10, 10, 230, 25))
        self.c_bp1_1.setFont(font)
        self.e_bp1_1 = QLineEdit(self.box_bp1)
        self.e_bp1_1.setObjectName(u"e_bp1_1")
        self.e_bp1_1.setGeometry(QRect(250, 10, 70, 25))
        self.c_bp1_2 = QCheckBox(self.box_bp1)
        self.c_bp1_2.setObjectName(u"c_bp1_2")
        self.c_bp1_2.setGeometry(QRect(10, 40, 230, 25))
        self.c_bp1_2.setFont(font)
        self.e_bp1_2 = QLineEdit(self.box_bp1)
        self.e_bp1_2.setObjectName(u"e_bp1_2")
        self.e_bp1_2.setGeometry(QRect(250, 40, 70, 25))
        self.c_bp1_3 = QCheckBox(self.box_bp1)
        self.c_bp1_3.setObjectName(u"c_bp1_3")
        self.c_bp1_3.setGeometry(QRect(10, 70, 230, 25))
        self.c_bp1_3.setFont(font)
        self.e_bp1_3 = QLineEdit(self.box_bp1)
        self.e_bp1_3.setObjectName(u"e_bp1_3")
        self.e_bp1_3.setGeometry(QRect(250, 70, 70, 25))
        self.c_bp1_4 = QCheckBox(self.box_bp1)
        self.c_bp1_4.setObjectName(u"c_bp1_4")
        self.c_bp1_4.setGeometry(QRect(10, 100, 230, 25))
        self.c_bp1_4.setFont(font)
        self.e_bp1_4 = QLineEdit(self.box_bp1)
        self.e_bp1_4.setObjectName(u"e_bp1_4")
        self.e_bp1_4.setGeometry(QRect(250, 100, 70, 25))
        self.c_bp1_5 = QCheckBox(self.box_bp1)
        self.c_bp1_5.setObjectName(u"c_bp1_5")
        self.c_bp1_5.setGeometry(QRect(10, 130, 230, 25))
        self.c_bp1_5.setFont(font)
        self.e_bp1_5 = QLineEdit(self.box_bp1)
        self.e_bp1_5.setObjectName(u"e_bp1_5")
        self.e_bp1_5.setGeometry(QRect(250, 130, 70, 25))
        self.c_bp1_6 = QCheckBox(self.box_bp1)
        self.c_bp1_6.setObjectName(u"c_bp1_6")
        self.c_bp1_6.setGeometry(QRect(10, 160, 230, 25))
        self.c_bp1_6.setFont(font)
        self.e_bp1_6 = QLineEdit(self.box_bp1)
        self.e_bp1_6.setObjectName(u"e_bp1_6")
        self.e_bp1_6.setGeometry(QRect(250, 160, 70, 25))
        self.c_bp1_7 = QCheckBox(self.box_bp1)
        self.c_bp1_7.setObjectName(u"c_bp1_7")
        self.c_bp1_7.setGeometry(QRect(10, 190, 230, 25))
        self.c_bp1_7.setFont(font)
        self.e_bp1_7 = QLineEdit(self.box_bp1)
        self.e_bp1_7.setObjectName(u"e_bp1_7")
        self.e_bp1_7.setGeometry(QRect(250, 190, 70, 25))
        self.c_bp1_8 = QCheckBox(self.box_bp1)
        self.c_bp1_8.setObjectName(u"c_bp1_8")
        self.c_bp1_8.setGeometry(QRect(10, 220, 230, 25))
        self.c_bp1_8.setFont(font)
        self.e_bp1_8 = QLineEdit(self.box_bp1)
        self.e_bp1_8.setObjectName(u"e_bp1_8")
        self.e_bp1_8.setGeometry(QRect(250, 220, 70, 25))
        self.l_bp2_t = QLabel(self.centralwidget)
        self.l_bp2_t.setObjectName(u"l_bp2_t")
        self.l_bp2_t.setGeometry(QRect(355, 333, 230, 30))
        self.l_bp2_t.setFont(font)
        self.l_bp2_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bp2_t.setFrameShape(QFrame.Shape.Box)
        self.l_bp2_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_bp2_s = QLabel(self.centralwidget)
        self.l_bp2_s.setObjectName(u"l_bp2_s")
        self.l_bp2_s.setGeometry(QRect(585, 333, 100, 30))
        self.l_bp2_s.setFont(font)
        self.l_bp2_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bp2_s.setFrameShape(QFrame.Shape.Box)
        self.l_bp2_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_bp2 = QFrame(self.centralwidget)
        self.box_bp2.setObjectName(u"box_bp2")
        self.box_bp2.setGeometry(QRect(355, 365, 330, 271))
        self.box_bp2.setFrameShape(QFrame.Shape.Box)
        self.c_bp2_1 = QCheckBox(self.box_bp2)
        self.c_bp2_1.setObjectName(u"c_bp2_1")
        self.c_bp2_1.setGeometry(QRect(10, 10, 230, 25))
        self.c_bp2_1.setFont(font)
        self.e_bp2_1 = QLineEdit(self.box_bp2)
        self.e_bp2_1.setObjectName(u"e_bp2_1")
        self.e_bp2_1.setGeometry(QRect(250, 10, 70, 25))
        self.c_bp2_2 = QCheckBox(self.box_bp2)
        self.c_bp2_2.setObjectName(u"c_bp2_2")
        self.c_bp2_2.setGeometry(QRect(10, 40, 230, 25))
        self.c_bp2_2.setFont(font)
        self.e_bp2_2 = QLineEdit(self.box_bp2)
        self.e_bp2_2.setObjectName(u"e_bp2_2")
        self.e_bp2_2.setGeometry(QRect(250, 40, 70, 25))
        self.c_bp2_3 = QCheckBox(self.box_bp2)
        self.c_bp2_3.setObjectName(u"c_bp2_3")
        self.c_bp2_3.setGeometry(QRect(10, 70, 230, 25))
        self.c_bp2_3.setFont(font)
        self.e_bp2_3 = QLineEdit(self.box_bp2)
        self.e_bp2_3.setObjectName(u"e_bp2_3")
        self.e_bp2_3.setGeometry(QRect(250, 70, 70, 25))
        self.c_bp2_4 = QCheckBox(self.box_bp2)
        self.c_bp2_4.setObjectName(u"c_bp2_4")
        self.c_bp2_4.setGeometry(QRect(10, 100, 230, 25))
        self.c_bp2_4.setFont(font)
        self.e_bp2_4 = QLineEdit(self.box_bp2)
        self.e_bp2_4.setObjectName(u"e_bp2_4")
        self.e_bp2_4.setGeometry(QRect(250, 100, 70, 25))
        self.c_bp2_5 = QCheckBox(self.box_bp2)
        self.c_bp2_5.setObjectName(u"c_bp2_5")
        self.c_bp2_5.setGeometry(QRect(10, 130, 230, 25))
        self.c_bp2_5.setFont(font)
        self.e_bp2_5 = QLineEdit(self.box_bp2)
        self.e_bp2_5.setObjectName(u"e_bp2_5")
        self.e_bp2_5.setGeometry(QRect(250, 130, 70, 25))
        self.c_bp2_6 = QCheckBox(self.box_bp2)
        self.c_bp2_6.setObjectName(u"c_bp2_6")
        self.c_bp2_6.setGeometry(QRect(10, 160, 230, 25))
        self.c_bp2_6.setFont(font)
        self.e_bp2_6 = QLineEdit(self.box_bp2)
        self.e_bp2_6.setObjectName(u"e_bp2_6")
        self.e_bp2_6.setGeometry(QRect(250, 160, 70, 25))
        self.c_bp2_7 = QCheckBox(self.box_bp2)
        self.c_bp2_7.setObjectName(u"c_bp2_7")
        self.c_bp2_7.setGeometry(QRect(10, 190, 230, 25))
        self.c_bp2_7.setFont(font)
        self.e_bp2_7 = QLineEdit(self.box_bp2)
        self.e_bp2_7.setObjectName(u"e_bp2_7")
        self.e_bp2_7.setGeometry(QRect(250, 190, 70, 25))
        self.c_bp2_8 = QCheckBox(self.box_bp2)
        self.c_bp2_8.setObjectName(u"c_bp2_8")
        self.c_bp2_8.setGeometry(QRect(10, 220, 230, 25))
        self.c_bp2_8.setFont(font)
        self.e_bp2_8 = QLineEdit(self.box_bp2)
        self.e_bp2_8.setObjectName(u"e_bp2_8")
        self.e_bp2_8.setGeometry(QRect(250, 220, 70, 25))
        self.l_ele_t = QLabel(self.centralwidget)
        self.l_ele_t.setObjectName(u"l_ele_t")
        self.l_ele_t.setGeometry(QRect(355, 658, 230, 30))
        self.l_ele_t.setFont(font)
        self.l_ele_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_ele_t.setFrameShape(QFrame.Shape.Box)
        self.l_ele_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_ele_s = QLabel(self.centralwidget)
        self.l_ele_s.setObjectName(u"l_ele_s")
        self.l_ele_s.setGeometry(QRect(585, 658, 100, 30))
        self.l_ele_s.setFont(font)
        self.l_ele_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_ele_s.setFrameShape(QFrame.Shape.Box)
        self.l_ele_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_ele = QFrame(self.centralwidget)
        self.box_ele.setObjectName(u"box_ele")
        self.box_ele.setGeometry(QRect(355, 690, 330, 171))
        self.box_ele.setFrameShape(QFrame.Shape.Box)
        self.c_el1 = QCheckBox(self.box_ele)
        self.c_el1.setObjectName(u"c_el1")
        self.c_el1.setGeometry(QRect(10, 10, 230, 25))
        self.c_el1.setFont(font)
        self.e_el1 = QLineEdit(self.box_ele)
        self.e_el1.setObjectName(u"e_el1")
        self.e_el1.setGeometry(QRect(250, 10, 70, 25))
        self.c_el2 = QCheckBox(self.box_ele)
        self.c_el2.setObjectName(u"c_el2")
        self.c_el2.setGeometry(QRect(10, 40, 230, 25))
        self.c_el2.setFont(font)
        self.e_el2 = QLineEdit(self.box_ele)
        self.e_el2.setObjectName(u"e_el2")
        self.e_el2.setGeometry(QRect(250, 40, 70, 25))
        self.c_el3 = QCheckBox(self.box_ele)
        self.c_el3.setObjectName(u"c_el3")
        self.c_el3.setGeometry(QRect(10, 70, 230, 25))
        self.c_el3.setFont(font)
        self.e_el3 = QLineEdit(self.box_ele)
        self.e_el3.setObjectName(u"e_el3")
        self.e_el3.setGeometry(QRect(250, 70, 70, 25))
        self.c_el4 = QCheckBox(self.box_ele)
        self.c_el4.setObjectName(u"c_el4")
        self.c_el4.setGeometry(QRect(10, 100, 230, 25))
        self.c_el4.setFont(font)
        self.e_el4 = QLineEdit(self.box_ele)
        self.e_el4.setObjectName(u"e_el4")
        self.e_el4.setGeometry(QRect(250, 100, 70, 25))
        self.c_el5 = QCheckBox(self.box_ele)
        self.c_el5.setObjectName(u"c_el5")
        self.c_el5.setGeometry(QRect(10, 130, 230, 25))
        self.c_el5.setFont(font)
        self.e_el5 = QLineEdit(self.box_ele)
        self.e_el5.setObjectName(u"e_el5")
        self.e_el5.setGeometry(QRect(250, 130, 70, 25))
        self.l_oth_t = QLabel(self.centralwidget)
        self.l_oth_t.setObjectName(u"l_oth_t")
        self.l_oth_t.setGeometry(QRect(700, 8, 230, 30))
        self.l_oth_t.setFont(font)
        self.l_oth_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_oth_t.setFrameShape(QFrame.Shape.Box)
        self.l_oth_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_oth_s = QLabel(self.centralwidget)
        self.l_oth_s.setObjectName(u"l_oth_s")
        self.l_oth_s.setGeometry(QRect(930, 8, 100, 30))
        self.l_oth_s.setFont(font)
        self.l_oth_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_oth_s.setFrameShape(QFrame.Shape.Box)
        self.l_oth_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_oth = QFrame(self.centralwidget)
        self.box_oth.setObjectName(u"box_oth")
        self.box_oth.setGeometry(QRect(700, 40, 330, 491))
        self.box_oth.setFrameShape(QFrame.Shape.Box)
        self.c_ot1 = QCheckBox(self.box_oth)
        self.c_ot1.setObjectName(u"c_ot1")
        self.c_ot1.setGeometry(QRect(10, 10, 230, 25))
        self.c_ot1.setFont(font)
        self.e_ot1 = QLineEdit(self.box_oth)
        self.e_ot1.setObjectName(u"e_ot1")
        self.e_ot1.setGeometry(QRect(250, 10, 70, 25))
        self.c_ot2 = QCheckBox(self.box_oth)
        self.c_ot2.setObjectName(u"c_ot2")
        self.c_ot2.setGeometry(QRect(10, 40, 230, 25))
        self.c_ot2.setFont(font)
        self.e_ot2 = QLineEdit(self.box_oth)
        self.e_ot2.setObjectName(u"e_ot2")
        self.e_ot2.setGeometry(QRect(250, 40, 70, 25))
        self.c_ot3 = QCheckBox(self.box_oth)
        self.c_ot3.setObjectName(u"c_ot3")
        self.c_ot3.setGeometry(QRect(10, 70, 230, 25))
        self.c_ot3.setFont(font)
        self.e_ot3 = QLineEdit(self.box_oth)
        self.e_ot3.setObjectName(u"e_ot3")
        self.e_ot3.setGeometry(QRect(250, 70, 70, 25))
        self.c_ot4 = QCheckBox(self.box_oth)
        self.c_ot4.setObjectName(u"c_ot4")
        self.c_ot4.setGeometry(QRect(10, 100, 230, 25))
        self.c_ot4.setFont(font)
        self.e_ot4 = QLineEdit(self.box_oth)
        self.e_ot4.setObjectName(u"e_ot4")
        self.e_ot4.setGeometry(QRect(250, 100, 70, 25))
        self.c_ot5 = QCheckBox(self.box_oth)
        self.c_ot5.setObjectName(u"c_ot5")
        self.c_ot5.setGeometry(QRect(10, 130, 230, 25))
        self.c_ot5.setFont(font)
        self.e_ot5 = QLineEdit(self.box_oth)
        self.e_ot5.setObjectName(u"e_ot5")
        self.e_ot5.setGeometry(QRect(250, 130, 70, 25))
        self.c_ot6 = QCheckBox(self.box_oth)
        self.c_ot6.setObjectName(u"c_ot6")
        self.c_ot6.setGeometry(QRect(10, 160, 230, 25))
        self.c_ot6.setFont(font)
        self.e_ot6 = QLineEdit(self.box_oth)
        self.e_ot6.setObjectName(u"e_ot6")
        self.e_ot6.setGeometry(QRect(250, 160, 70, 25))
        self.c_ot7 = QCheckBox(self.box_oth)
        self.c_ot7.setObjectName(u"c_ot7")
        self.c_ot7.setGeometry(QRect(10, 190, 230, 25))
        self.c_ot7.setFont(font)
        self.e_ot7 = QLineEdit(self.box_oth)
        self.e_ot7.setObjectName(u"e_ot7")
        self.e_ot7.setGeometry(QRect(250, 190, 70, 25))
        self.c_ot8 = QCheckBox(self.box_oth)
        self.c_ot8.setObjectName(u"c_ot8")
        self.c_ot8.setGeometry(QRect(10, 220, 230, 25))
        self.c_ot8.setFont(font)
        self.e_ot8 = QLineEdit(self.box_oth)
        self.e_ot8.setObjectName(u"e_ot8")
        self.e_ot8.setGeometry(QRect(250, 220, 70, 25))
        self.c_ot9 = QCheckBox(self.box_oth)
        self.c_ot9.setObjectName(u"c_ot9")
        self.c_ot9.setGeometry(QRect(10, 250, 230, 25))
        self.c_ot9.setFont(font)
        self.e_ot9 = QLineEdit(self.box_oth)
        self.e_ot9.setObjectName(u"e_ot9")
        self.e_ot9.setGeometry(QRect(250, 250, 70, 25))
        self.c_ot10 = QCheckBox(self.box_oth)
        self.c_ot10.setObjectName(u"c_ot10")
        self.c_ot10.setGeometry(QRect(10, 280, 230, 25))
        self.c_ot10.setFont(font)
        self.e_ot10 = QLineEdit(self.box_oth)
        self.e_ot10.setObjectName(u"e_ot10")
        self.e_ot10.setGeometry(QRect(250, 280, 70, 25))
        self.c_ot11 = QCheckBox(self.box_oth)
        self.c_ot11.setObjectName(u"c_ot11")
        self.c_ot11.setGeometry(QRect(10, 310, 230, 25))
        self.c_ot11.setFont(font)
        self.e_ot11 = QLineEdit(self.box_oth)
        self.e_ot11.setObjectName(u"e_ot11")
        self.e_ot11.setGeometry(QRect(250, 310, 70, 25))
        self.c_ot12 = QCheckBox(self.box_oth)
        self.c_ot12.setObjectName(u"c_ot12")
        self.c_ot12.setGeometry(QRect(10, 350, 20, 25))
        self.e_ot12_n = QLineEdit(self.box_oth)
        self.e_ot12_n.setObjectName(u"e_ot12_n")
        self.e_ot12_n.setGeometry(QRect(50, 350, 140, 25))
        self.l_pr1 = QLabel(self.box_oth)
        self.l_pr1.setObjectName(u"l_pr1")
        self.l_pr1.setGeometry(QRect(10, 380, 40, 25))
        self.l_pr1.setFont(font)
        self.e_ot12_p = QLineEdit(self.box_oth)
        self.e_ot12_p.setObjectName(u"e_ot12_p")
        self.e_ot12_p.setGeometry(QRect(50, 380, 90, 25))
        self.c_ot13 = QCheckBox(self.box_oth)
        self.c_ot13.setObjectName(u"c_ot13")
        self.c_ot13.setGeometry(QRect(10, 420, 20, 25))
        self.e_ot13_n = QLineEdit(self.box_oth)
        self.e_ot13_n.setObjectName(u"e_ot13_n")
        self.e_ot13_n.setGeometry(QRect(50, 420, 140, 25))
        self.l_pr2 = QLabel(self.box_oth)
        self.l_pr2.setObjectName(u"l_pr2")
        self.l_pr2.setGeometry(QRect(10, 450, 40, 25))
        self.l_pr2.setFont(font)
        self.e_ot13_p = QLineEdit(self.box_oth)
        self.e_ot13_p.setObjectName(u"e_ot13_p")
        self.e_ot13_p.setGeometry(QRect(50, 450, 90, 25))
        self.e_ot11_2 = QLineEdit(self.box_oth)
        self.e_ot11_2.setObjectName(u"e_ot11_2")
        self.e_ot11_2.setGeometry(QRect(250, 350, 70, 25))
        self.e_ot11_3 = QLineEdit(self.box_oth)
        self.e_ot11_3.setObjectName(u"e_ot11_3")
        self.e_ot11_3.setGeometry(QRect(250, 420, 70, 25))
        self.e_ot13_p.raise_()
        self.e_ot13_n.raise_()
        self.e_ot12_p.raise_()
        self.e_ot12_n.raise_()
        self.c_ot1.raise_()
        self.e_ot1.raise_()
        self.c_ot2.raise_()
        self.e_ot2.raise_()
        self.c_ot3.raise_()
        self.e_ot3.raise_()
        self.c_ot4.raise_()
        self.e_ot4.raise_()
        self.c_ot5.raise_()
        self.e_ot5.raise_()
        self.c_ot6.raise_()
        self.e_ot6.raise_()
        self.c_ot7.raise_()
        self.e_ot7.raise_()
        self.c_ot8.raise_()
        self.e_ot8.raise_()
        self.c_ot9.raise_()
        self.e_ot9.raise_()
        self.c_ot10.raise_()
        self.e_ot10.raise_()
        self.c_ot11.raise_()
        self.e_ot11.raise_()
        self.e_ot11_2.raise_()
        self.e_ot11_3.raise_()
        self.c_ot12.raise_()
        self.c_ot13.raise_()
        self.l_pr1.raise_()
        self.l_pr2.raise_()
        self.l_bov_t = QLabel(self.centralwidget)
        self.l_bov_t.setObjectName(u"l_bov_t")
        self.l_bov_t.setGeometry(QRect(700, 538, 230, 30))
        self.l_bov_t.setFont(font)
        self.l_bov_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bov_t.setFrameShape(QFrame.Shape.Box)
        self.l_bov_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_bov_s = QLabel(self.centralwidget)
        self.l_bov_s.setObjectName(u"l_bov_s")
        self.l_bov_s.setGeometry(QRect(930, 538, 100, 30))
        self.l_bov_s.setFont(font)
        self.l_bov_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_bov_s.setFrameShape(QFrame.Shape.Box)
        self.l_bov_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_bov = QFrame(self.centralwidget)
        self.box_bov.setObjectName(u"box_bov")
        self.box_bov.setGeometry(QRect(700, 570, 330, 141))
        self.box_bov.setFrameShape(QFrame.Shape.Box)
        self.c_bv1 = QCheckBox(self.box_bov)
        self.c_bv1.setObjectName(u"c_bv1")
        self.c_bv1.setGeometry(QRect(10, 10, 230, 25))
        self.c_bv1.setFont(font)
        self.e_bv1 = QLineEdit(self.box_bov)
        self.e_bv1.setObjectName(u"e_bv1")
        self.e_bv1.setGeometry(QRect(250, 10, 70, 25))
        self.c_bv2 = QCheckBox(self.box_bov)
        self.c_bv2.setObjectName(u"c_bv2")
        self.c_bv2.setGeometry(QRect(10, 40, 230, 25))
        self.c_bv2.setFont(font)
        self.e_bv2 = QLineEdit(self.box_bov)
        self.e_bv2.setObjectName(u"e_bv2")
        self.e_bv2.setGeometry(QRect(250, 40, 70, 25))
        self.c_bv3 = QCheckBox(self.box_bov)
        self.c_bv3.setObjectName(u"c_bv3")
        self.c_bv3.setGeometry(QRect(10, 70, 230, 25))
        self.c_bv3.setFont(font)
        self.e_bv3 = QLineEdit(self.box_bov)
        self.e_bv3.setObjectName(u"e_bv3")
        self.e_bv3.setGeometry(QRect(250, 70, 70, 25))
        self.c_bv4 = QCheckBox(self.box_bov)
        self.c_bv4.setObjectName(u"c_bv4")
        self.c_bv4.setGeometry(QRect(10, 100, 230, 25))
        self.c_bv4.setFont(font)
        self.e_bv4 = QLineEdit(self.box_bov)
        self.e_bv4.setObjectName(u"e_bv4")
        self.e_bv4.setGeometry(QRect(250, 100, 70, 25))
        self.l_aq_t = QLabel(self.centralwidget)
        self.l_aq_t.setObjectName(u"l_aq_t")
        self.l_aq_t.setGeometry(QRect(700, 718, 230, 30))
        self.l_aq_t.setFont(font)
        self.l_aq_t.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_aq_t.setFrameShape(QFrame.Shape.Box)
        self.l_aq_t.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_aq_s = QLabel(self.centralwidget)
        self.l_aq_s.setObjectName(u"l_aq_s")
        self.l_aq_s.setGeometry(QRect(930, 718, 100, 30))
        self.l_aq_s.setFont(font)
        self.l_aq_s.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.l_aq_s.setFrameShape(QFrame.Shape.Box)
        self.l_aq_s.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.box_aq = QFrame(self.centralwidget)
        self.box_aq.setObjectName(u"box_aq")
        self.box_aq.setGeometry(QRect(700, 750, 330, 111))
        self.box_aq.setFrameShape(QFrame.Shape.Box)
        self.c_aq1 = QCheckBox(self.box_aq)
        self.c_aq1.setObjectName(u"c_aq1")
        self.c_aq1.setGeometry(QRect(10, 10, 230, 25))
        self.c_aq1.setFont(font)
        self.e_aq1 = QLineEdit(self.box_aq)
        self.e_aq1.setObjectName(u"e_aq1")
        self.e_aq1.setGeometry(QRect(250, 10, 70, 25))
        self.c_aq2 = QCheckBox(self.box_aq)
        self.c_aq2.setObjectName(u"c_aq2")
        self.c_aq2.setGeometry(QRect(10, 40, 230, 25))
        self.c_aq2.setFont(font)
        self.e_aq2 = QLineEdit(self.box_aq)
        self.e_aq2.setObjectName(u"e_aq2")
        self.e_aq2.setGeometry(QRect(250, 40, 70, 25))
        self.c_aq3 = QCheckBox(self.box_aq)
        self.c_aq3.setObjectName(u"c_aq3")
        self.c_aq3.setGeometry(QRect(10, 70, 230, 25))
        self.c_aq3.setFont(font)
        self.e_aq3 = QLineEdit(self.box_aq)
        self.e_aq3.setObjectName(u"e_aq3")
        self.e_aq3.setGeometry(QRect(250, 70, 70, 25))
        self.l_main = QLabel(self.centralwidget)
        self.l_main.setObjectName(u"l_main")
        self.l_main.setGeometry(QRect(1050, 10, 201, 30))
        self.l_main.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.l_req = QLabel(self.centralwidget)
        self.l_req.setObjectName(u"l_req")
        self.l_req.setGeometry(QRect(1050, 43, 201, 35))
        self.l_req.setFont(font)
        self.l_req.setFrameShape(QFrame.Shape.Box)
        self.l_req.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gb_pcr = QGroupBox(self.centralwidget)
        self.gb_pcr.setObjectName(u"gb_pcr")
        self.gb_pcr.setGeometry(QRect(1050, 80, 201, 111))
        self.r_c = QRadioButton(self.gb_pcr)
        self.r_c.setObjectName(u"r_c")
        self.r_c.setGeometry(QRect(10, 10, 181, 30))
        self.r_c.setFont(font)
        self.r_q = QRadioButton(self.gb_pcr)
        self.r_q.setObjectName(u"r_q")
        self.r_q.setGeometry(QRect(10, 40, 181, 30))
        self.r_q.setFont(font)
        self.r_e = QRadioButton(self.gb_pcr)
        self.r_e.setObjectName(u"r_e")
        self.r_e.setGeometry(QRect(10, 70, 181, 30))
        self.r_e.setFont(font)
        self.l_cnt = QLabel(self.centralwidget)
        self.l_cnt.setObjectName(u"l_cnt")
        self.l_cnt.setGeometry(QRect(1050, 260, 201, 30))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.l_cnt.setFont(font1)
        self.e_cnt = QLineEdit(self.centralwidget)
        self.e_cnt.setObjectName(u"e_cnt")
        self.e_cnt.setGeometry(QRect(1050, 290, 131, 30))
        self.l_u1 = QLabel(self.centralwidget)
        self.l_u1.setObjectName(u"l_u1")
        self.l_u1.setGeometry(QRect(1190, 290, 61, 30))
        self.l_u1.setFont(font1)
        self.l_cst = QLabel(self.centralwidget)
        self.l_cst.setObjectName(u"l_cst")
        self.l_cst.setGeometry(QRect(1050, 330, 201, 30))
        self.l_cst.setFont(font1)
        self.e_cst = QLineEdit(self.centralwidget)
        self.e_cst.setObjectName(u"e_cst")
        self.e_cst.setGeometry(QRect(1050, 360, 131, 30))
        self.l_u2 = QLabel(self.centralwidget)
        self.l_u2.setObjectName(u"l_u2")
        self.l_u2.setGeometry(QRect(1190, 360, 61, 30))
        self.l_u2.setFont(font1)
        self.back_pushButton = QPushButton(self.centralwidget)
        self.back_pushButton.setObjectName(u"back_pushButton")
        self.back_pushButton.setGeometry(QRect(1050, 483, 211, 51))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(True)
        self.back_pushButton.setFont(font2)
        self.back_pushButton.setTabletTracking(False)
        self.save_pushButton = QPushButton(self.centralwidget)
        self.save_pushButton.setObjectName(u"save_pushButton")
        self.save_pushButton.setGeometry(QRect(1050, 420, 211, 51))
        self.save_pushButton.setFont(font2)
        self.save_pushButton.setTabletTracking(False)
        self.cal_pushButton = QPushButton(self.centralwidget)
        self.cal_pushButton.setObjectName(u"cal_pushButton")
        self.cal_pushButton.setGeometry(QRect(1050, 200, 201, 51))
        self.cal_pushButton.setFont(font2)
        self.cal_pushButton.setTabletTracking(False)
        molecular_biology_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(molecular_biology_MainWindow)

        QMetaObject.connectSlotsByName(molecular_biology_MainWindow)
    # setupUi

    def retranslateUi(self, molecular_biology_MainWindow):
        molecular_biology_MainWindow.setWindowTitle(QCoreApplication.translate("molecular_biology_MainWindow", u"Molecular Biology Laboratory Request", None))
        molecular_biology_MainWindow.setStyleSheet("")
        self.l_av_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"AVIAN", None))
        self.l_av_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_av.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_av1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"AI; type A, H5/H7/H9 - cPCR (700)", None))
        self.c_av2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"AI; type A, H5/H7/H9 - qPCR (1200)", None))
        self.c_av3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"IBV (700)", None))
        self.c_av4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"IBDV (700)", None))
        self.c_av5.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av5.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"ILT (600)", None))
        self.c_av6.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av6.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"NDV - cPCR (700)", None))
        self.c_av7.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av7.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"NDV - qPCR (1200)", None))
        self.c_av8.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av8.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"PDD (700)", None))
        self.c_av9.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av9.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"PBFDV (600)", None))
        self.c_av10.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av10.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Chlamydia psittaci (600)", None))
        self.c_av11.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av11.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Pasteurella multocida (600)", None))
        self.c_av12.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_av12.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"MG (600)", None))
        self.l_fel_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Feline", None))
        self.l_fel_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_fel.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_fe1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_fe1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"FeLV (600)", None))
        self.c_fe2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_fe2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"FIP (800)", None))
        self.c_fe3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_fe3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"FIV (600)", None))
        self.c_fe4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_fe4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Panleukopenia (600)", None))
        self.l_can_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"CANINE", None))
        self.l_can_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_can.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_cn1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_cn1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"CDV (700)", None))
        self.c_cn2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_cn2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"CPV (600)", None))
        self.l_eq_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Equine", None))
        self.l_eq_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_eq.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_eq1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_eq1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EHV [1,4] (700)", None))
        self.c_eq2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_eq2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"AHS (700)", None))
        self.l_bp1_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Blood parasite", None))
        self.l_bp1_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_bp1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_bp1_1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Anaplasma spp. (500)", None))
        self.c_bp1_2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Babesia spp. (500)", None))
        self.c_bp1_3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Ehrlichia canis (500)", None))
        self.c_bp1_4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Theileria spp. (500)", None))
        self.c_bp1_5.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_5.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Haemobartonella spp.(600)", None))
        self.c_bp1_6.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_6.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"E.canis Babesia (600)", None))
        self.c_bp1_7.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_7.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Leishmania spp. (700)", None))
        self.c_bp1_8.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp1_8.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Trypanosoma evansi(500)", None))
        self.l_bp2_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Blood parasite", None))
        self.l_bp2_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_bp2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_bp2_1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"ASF-cPCR (400)", None))
        self.c_bp2_2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"ASF-qPCR (800)", None))
        self.c_bp2_3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"ASF-qPCR (1000)", None))
        self.c_bp2_4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"CSF (700)", None))
        self.c_bp2_5.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_5.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"HP-PRRSV (700)", None))
        self.c_bp2_6.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_6.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"PRRSV (800)", None))
        self.c_bp2_7.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_7.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"PCV-2 (600)", None))
        self.c_bp2_8.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bp2_8.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"PED (700)", None))
        self.l_ele_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Elephant", None))
        self.l_ele_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_ele.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_el1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_el1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EEHV1A/4 (600)", None))
        self.c_el2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_el2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EEHV1A - cPCR (700)", None))
        self.c_el3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_el3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EEHV1A - qPCR (1200)", None))
        self.c_el4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_el4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EEHV4 - cPCR (700)", None))
        self.c_el5.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_el5.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"EEHV4 - qPCR (1200)", None))
        self.l_oth_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Others", None))
        self.l_oth_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_oth.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_ot1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Bird sexing (300)", None))
        self.c_ot2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Bird sexing (350)", None))
        self.c_ot3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Clostridial toxins (700)", None))
        self.c_ot4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Leptospirosis (600)", None))
        self.c_ot5.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot5.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Toxoplasma gondii (600)", None))
        self.c_ot6.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot6.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Melioidosis (700)", None))
        self.c_ot7.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot7.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Mycobacterium spp.(600)", None))
        self.c_ot8.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot8.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"M.avium (600)", None))
        self.c_ot9.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot9.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"M.bovis (600)", None))
        self.c_ot10.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot10.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"M.tuberculosis (600)", None))
        self.c_ot11.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_ot11.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"AHS qPCR (1200)", None))
        self.c_ot12.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.l_pr1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.l_pr1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e23\u0e32\u0e04\u0e32", None))
        self.c_ot13.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.l_pr2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.l_pr2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e23\u0e32\u0e04\u0e32", None))
        self.l_bov_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Bovine", None))
        self.l_bov_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_bov.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_bv1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bv1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"BLV (700)", None))
        self.c_bv2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bv2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"FMDV (700)", None))
        self.c_bv3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bv3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"LSDV (600)", None))
        self.c_bv4.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_bv4.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"BVD (700)", None))
        self.l_aq_t.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Aquatic animal", None))
        self.l_aq_s.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"SAMPLE", None))
        self.box_aq.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black; background-color: white;", None))
        self.c_aq1.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_aq1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"KHV (600)", None))
        self.c_aq2.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_aq2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"TiLV (700)", None))
        self.c_aq3.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.c_aq3.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"CEV (600)", None))
        self.l_main.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Molecular Biology", None))
        self.l_req.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Laboratory Request", None))
        self.gb_pcr.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: 1px solid black;", None))
        self.gb_pcr.setTitle("")
        self.r_c.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.r_c.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"cPCR", None))
        self.r_q.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.r_q.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"qPCR", None))
        self.r_e.setStyleSheet(QCoreApplication.translate("molecular_biology_MainWindow", u"border: none;", None))
        self.r_e.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"Extraction", None))
        self.l_cnt.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e01\u0e32\u0e23\u0e15\u0e23\u0e27\u0e08", None))
        self.l_u1.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.l_cst.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.l_u2.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e1a\u0e32\u0e17", None))
        self.back_pushButton.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e01\u0e25\u0e31\u0e1a\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        self.save_pushButton.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.cal_pushButton.setText(QCoreApplication.translate("molecular_biology_MainWindow", u"\u0e04\u0e33\u0e19\u0e27\u0e13\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
    # retranslateUi

