# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bacteria.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPlainTextEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_bacteria_MainWindow(object):
    def setupUi(self, bacteria_MainWindow):
        if not bacteria_MainWindow.objectName():
            bacteria_MainWindow.setObjectName(u"bacteria_MainWindow")
        bacteria_MainWindow.resize(1270, 890)
        bacteria_MainWindow.setMinimumSize(QSize(1270, 890))
        bacteria_MainWindow.setMaximumSize(QSize(1270, 890))
        self.centralwidget = QWidget(bacteria_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.bacteria_sample_frame = QFrame(self.centralwidget)
        self.bacteria_sample_frame.setObjectName(u"bacteria_sample_frame")
        self.bacteria_sample_frame.setGeometry(QRect(10, 70, 320, 810))
        self.bacteria_sample_frame.setMinimumSize(QSize(320, 810))
        self.bacteria_sample_frame.setMaximumSize(QSize(320, 810))
        self.bacteria_sample_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_sample_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.bacteria_swabLT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_swabLT_checkBox.setObjectName(u"bacteria_swabLT_checkBox")
        self.bacteria_swabLT_checkBox.setGeometry(QRect(10, 10, 130, 20))
        self.bacteria_swabLT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_swabLT_checkBox.setMaximumSize(QSize(130, 20))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        self.bacteria_swabLT_checkBox.setFont(font)
        self.bacteria_swabRT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_swabRT_checkBox.setObjectName(u"bacteria_swabRT_checkBox")
        self.bacteria_swabRT_checkBox.setGeometry(QRect(10, 48, 130, 20))
        self.bacteria_swabRT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_swabRT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_swabRT_checkBox.setFont(font)
        self.bacteria_wound_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_wound_checkBox.setObjectName(u"bacteria_wound_checkBox")
        self.bacteria_wound_checkBox.setGeometry(QRect(10, 86, 130, 20))
        self.bacteria_wound_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_wound_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_wound_checkBox.setFont(font)
        self.bacteria_aspirateLT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_aspirateLT_checkBox.setObjectName(u"bacteria_aspirateLT_checkBox")
        self.bacteria_aspirateLT_checkBox.setGeometry(QRect(10, 124, 130, 20))
        self.bacteria_aspirateLT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_aspirateLT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_aspirateLT_checkBox.setFont(font)
        self.bacteria_catheterization_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_catheterization_checkBox.setObjectName(u"bacteria_catheterization_checkBox")
        self.bacteria_catheterization_checkBox.setGeometry(QRect(10, 276, 150, 20))
        self.bacteria_catheterization_checkBox.setMinimumSize(QSize(150, 20))
        self.bacteria_catheterization_checkBox.setMaximumSize(QSize(150, 20))
        self.bacteria_catheterization_checkBox.setFont(font)
        self.bacteria_urine_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_urine_checkBox.setObjectName(u"bacteria_urine_checkBox")
        self.bacteria_urine_checkBox.setGeometry(QRect(10, 200, 130, 20))
        self.bacteria_urine_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_urine_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_urine_checkBox.setFont(font)
        self.bacteria_tissuesLT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_tissuesLT_checkBox.setObjectName(u"bacteria_tissuesLT_checkBox")
        self.bacteria_tissuesLT_checkBox.setGeometry(QRect(10, 352, 130, 20))
        self.bacteria_tissuesLT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_tissuesLT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_tissuesLT_checkBox.setFont(font)
        self.bacteria_feces_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_feces_checkBox.setObjectName(u"bacteria_feces_checkBox")
        self.bacteria_feces_checkBox.setGeometry(QRect(10, 618, 130, 20))
        self.bacteria_feces_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_feces_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_feces_checkBox.setFont(font)
        self.bacteria_aspirateRT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_aspirateRT_checkBox.setObjectName(u"bacteria_aspirateRT_checkBox")
        self.bacteria_aspirateRT_checkBox.setGeometry(QRect(10, 162, 130, 20))
        self.bacteria_aspirateRT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_aspirateRT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_aspirateRT_checkBox.setFont(font)
        self.bacteria_blood_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_blood_checkBox.setObjectName(u"bacteria_blood_checkBox")
        self.bacteria_blood_checkBox.setGeometry(QRect(10, 694, 130, 20))
        self.bacteria_blood_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_blood_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_blood_checkBox.setFont(font)
        self.bacteria_csf_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_csf_checkBox.setObjectName(u"bacteria_csf_checkBox")
        self.bacteria_csf_checkBox.setGeometry(QRect(10, 580, 130, 20))
        self.bacteria_csf_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_csf_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_csf_checkBox.setFont(font)
        self.bacteria_bodyFluidLT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_bodyFluidLT_checkBox.setObjectName(u"bacteria_bodyFluidLT_checkBox")
        self.bacteria_bodyFluidLT_checkBox.setGeometry(QRect(10, 504, 150, 20))
        self.bacteria_bodyFluidLT_checkBox.setMinimumSize(QSize(150, 20))
        self.bacteria_bodyFluidLT_checkBox.setMaximumSize(QSize(150, 20))
        self.bacteria_bodyFluidLT_checkBox.setFont(font)
        self.bacteria_skinScaping_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_skinScaping_checkBox.setObjectName(u"bacteria_skinScaping_checkBox")
        self.bacteria_skinScaping_checkBox.setGeometry(QRect(10, 770, 130, 20))
        self.bacteria_skinScaping_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_skinScaping_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_skinScaping_checkBox.setFont(font)
        self.bacteria_midstream_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_midstream_checkBox.setObjectName(u"bacteria_midstream_checkBox")
        self.bacteria_midstream_checkBox.setGeometry(QRect(10, 238, 130, 20))
        self.bacteria_midstream_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_midstream_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_midstream_checkBox.setFont(font)
        self.bacteria_biopsyLT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_biopsyLT_checkBox.setObjectName(u"bacteria_biopsyLT_checkBox")
        self.bacteria_biopsyLT_checkBox.setGeometry(QRect(10, 428, 130, 20))
        self.bacteria_biopsyLT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_biopsyLT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_biopsyLT_checkBox.setFont(font)
        self.bacteria_tissuesRT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_tissuesRT_checkBox.setObjectName(u"bacteria_tissuesRT_checkBox")
        self.bacteria_tissuesRT_checkBox.setGeometry(QRect(10, 390, 130, 20))
        self.bacteria_tissuesRT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_tissuesRT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_tissuesRT_checkBox.setFont(font)
        self.bacteria_cystocentesis_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_cystocentesis_checkBox.setObjectName(u"bacteria_cystocentesis_checkBox")
        self.bacteria_cystocentesis_checkBox.setGeometry(QRect(10, 314, 130, 20))
        self.bacteria_cystocentesis_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_cystocentesis_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_cystocentesis_checkBox.setFont(font)
        self.bacteria_pus_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_pus_checkBox.setObjectName(u"bacteria_pus_checkBox")
        self.bacteria_pus_checkBox.setGeometry(QRect(10, 656, 130, 20))
        self.bacteria_pus_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_pus_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_pus_checkBox.setFont(font)
        self.bacteria_bodyFluidRT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_bodyFluidRT_checkBox.setObjectName(u"bacteria_bodyFluidRT_checkBox")
        self.bacteria_bodyFluidRT_checkBox.setGeometry(QRect(10, 542, 150, 20))
        self.bacteria_bodyFluidRT_checkBox.setMinimumSize(QSize(150, 20))
        self.bacteria_bodyFluidRT_checkBox.setMaximumSize(QSize(150, 20))
        self.bacteria_bodyFluidRT_checkBox.setFont(font)
        self.bacteria_bloodAgar_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_bloodAgar_checkBox.setObjectName(u"bacteria_bloodAgar_checkBox")
        self.bacteria_bloodAgar_checkBox.setGeometry(QRect(10, 732, 130, 20))
        self.bacteria_bloodAgar_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_bloodAgar_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_bloodAgar_checkBox.setFont(font)
        self.bacteria_biopsyRT_checkBox = QCheckBox(self.bacteria_sample_frame)
        self.bacteria_biopsyRT_checkBox.setObjectName(u"bacteria_biopsyRT_checkBox")
        self.bacteria_biopsyRT_checkBox.setGeometry(QRect(10, 466, 130, 20))
        self.bacteria_biopsyRT_checkBox.setMinimumSize(QSize(130, 20))
        self.bacteria_biopsyRT_checkBox.setMaximumSize(QSize(130, 20))
        self.bacteria_biopsyRT_checkBox.setFont(font)
        self.bacteria_swabLT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_swabLT_lineEdit.setObjectName(u"bacteria_swabLT_lineEdit")
        self.bacteria_swabLT_lineEdit.setGeometry(QRect(210, 8, 100, 35))
        self.bacteria_swabLT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_swabLT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_swabLT_lineEdit.setFont(font)
        self.bacteria_swabRT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_swabRT_lineEdit.setObjectName(u"bacteria_swabRT_lineEdit")
        self.bacteria_swabRT_lineEdit.setGeometry(QRect(210, 46, 100, 35))
        self.bacteria_swabRT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_swabRT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_swabRT_lineEdit.setFont(font)
        self.bacteria_aspirateLT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_aspirateLT_lineEdit.setObjectName(u"bacteria_aspirateLT_lineEdit")
        self.bacteria_aspirateLT_lineEdit.setGeometry(QRect(210, 122, 100, 35))
        self.bacteria_aspirateLT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_aspirateLT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_aspirateLT_lineEdit.setFont(font)
        self.bacteria_wound_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_wound_lineEdit.setObjectName(u"bacteria_wound_lineEdit")
        self.bacteria_wound_lineEdit.setGeometry(QRect(210, 84, 100, 35))
        self.bacteria_wound_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_wound_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_wound_lineEdit.setFont(font)
        self.bacteria_urine_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_urine_lineEdit.setObjectName(u"bacteria_urine_lineEdit")
        self.bacteria_urine_lineEdit.setGeometry(QRect(210, 198, 100, 35))
        self.bacteria_urine_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_urine_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_urine_lineEdit.setFont(font)
        self.bacteria_midstream_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_midstream_lineEdit.setObjectName(u"bacteria_midstream_lineEdit")
        self.bacteria_midstream_lineEdit.setGeometry(QRect(210, 236, 100, 35))
        self.bacteria_midstream_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_midstream_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_midstream_lineEdit.setFont(font)
        self.bacteria_catheterization_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_catheterization_lineEdit.setObjectName(u"bacteria_catheterization_lineEdit")
        self.bacteria_catheterization_lineEdit.setGeometry(QRect(210, 274, 100, 35))
        self.bacteria_catheterization_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_catheterization_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_catheterization_lineEdit.setFont(font)
        self.bacteria_aspirateRT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_aspirateRT_lineEdit.setObjectName(u"bacteria_aspirateRT_lineEdit")
        self.bacteria_aspirateRT_lineEdit.setGeometry(QRect(210, 160, 100, 35))
        self.bacteria_aspirateRT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_aspirateRT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_aspirateRT_lineEdit.setFont(font)
        self.bacteria_tissuesLT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_tissuesLT_lineEdit.setObjectName(u"bacteria_tissuesLT_lineEdit")
        self.bacteria_tissuesLT_lineEdit.setGeometry(QRect(210, 350, 100, 35))
        self.bacteria_tissuesLT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_tissuesLT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_tissuesLT_lineEdit.setFont(font)
        self.bacteria_csf_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_csf_lineEdit.setObjectName(u"bacteria_csf_lineEdit")
        self.bacteria_csf_lineEdit.setGeometry(QRect(210, 578, 100, 35))
        self.bacteria_csf_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_csf_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_csf_lineEdit.setFont(font)
        self.bacteria_tissuesRT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_tissuesRT_lineEdit.setObjectName(u"bacteria_tissuesRT_lineEdit")
        self.bacteria_tissuesRT_lineEdit.setGeometry(QRect(210, 388, 100, 35))
        self.bacteria_tissuesRT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_tissuesRT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_tissuesRT_lineEdit.setFont(font)
        self.bacteria_biopsyLT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_biopsyLT_lineEdit.setObjectName(u"bacteria_biopsyLT_lineEdit")
        self.bacteria_biopsyLT_lineEdit.setGeometry(QRect(210, 426, 100, 35))
        self.bacteria_biopsyLT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_biopsyLT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_biopsyLT_lineEdit.setFont(font)
        self.bacteria_biopsyRT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_biopsyRT_lineEdit.setObjectName(u"bacteria_biopsyRT_lineEdit")
        self.bacteria_biopsyRT_lineEdit.setGeometry(QRect(210, 464, 100, 35))
        self.bacteria_biopsyRT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_biopsyRT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_biopsyRT_lineEdit.setFont(font)
        self.bacteria_cystocentesis_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_cystocentesis_lineEdit.setObjectName(u"bacteria_cystocentesis_lineEdit")
        self.bacteria_cystocentesis_lineEdit.setGeometry(QRect(210, 312, 100, 35))
        self.bacteria_cystocentesis_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_cystocentesis_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_cystocentesis_lineEdit.setFont(font)
        self.bacteria_bodyFluidLT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_bodyFluidLT_lineEdit.setObjectName(u"bacteria_bodyFluidLT_lineEdit")
        self.bacteria_bodyFluidLT_lineEdit.setGeometry(QRect(210, 502, 100, 35))
        self.bacteria_bodyFluidLT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_bodyFluidLT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_bodyFluidLT_lineEdit.setFont(font)
        self.bacteria_bodyFluidRT_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_bodyFluidRT_lineEdit.setObjectName(u"bacteria_bodyFluidRT_lineEdit")
        self.bacteria_bodyFluidRT_lineEdit.setGeometry(QRect(210, 540, 100, 35))
        self.bacteria_bodyFluidRT_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_bodyFluidRT_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_bodyFluidRT_lineEdit.setFont(font)
        self.bacteria_pus_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_pus_lineEdit.setObjectName(u"bacteria_pus_lineEdit")
        self.bacteria_pus_lineEdit.setGeometry(QRect(210, 654, 100, 35))
        self.bacteria_pus_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_pus_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_pus_lineEdit.setFont(font)
        self.bacteria_blood_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_blood_lineEdit.setObjectName(u"bacteria_blood_lineEdit")
        self.bacteria_blood_lineEdit.setGeometry(QRect(210, 692, 100, 35))
        self.bacteria_blood_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_blood_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_blood_lineEdit.setFont(font)
        self.bacteria_bloodAgar_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_bloodAgar_lineEdit.setObjectName(u"bacteria_bloodAgar_lineEdit")
        self.bacteria_bloodAgar_lineEdit.setGeometry(QRect(210, 730, 100, 35))
        self.bacteria_bloodAgar_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_bloodAgar_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_bloodAgar_lineEdit.setFont(font)
        self.bacteria_skinScaping_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_skinScaping_lineEdit.setObjectName(u"bacteria_skinScaping_lineEdit")
        self.bacteria_skinScaping_lineEdit.setGeometry(QRect(210, 768, 100, 35))
        self.bacteria_skinScaping_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_skinScaping_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_skinScaping_lineEdit.setFont(font)
        self.bacteria_feces_lineEdit = QLineEdit(self.bacteria_sample_frame)
        self.bacteria_feces_lineEdit.setObjectName(u"bacteria_feces_lineEdit")
        self.bacteria_feces_lineEdit.setGeometry(QRect(210, 616, 100, 35))
        self.bacteria_feces_lineEdit.setMinimumSize(QSize(100, 35))
        self.bacteria_feces_lineEdit.setMaximumSize(QSize(100, 35))
        self.bacteria_feces_lineEdit.setFont(font)
        self.bacteria_preparation_label = QLabel(self.centralwidget)
        self.bacteria_preparation_label.setObjectName(u"bacteria_preparation_label")
        self.bacteria_preparation_label.setGeometry(QRect(10, 20, 210, 50))
        self.bacteria_preparation_label.setMinimumSize(QSize(210, 50))
        self.bacteria_preparation_label.setMaximumSize(QSize(210, 50))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.bacteria_preparation_label.setFont(font1)
        self.bacteria_preparation_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_preparation_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_sample_label = QLabel(self.centralwidget)
        self.bacteria_sample_label.setObjectName(u"bacteria_sample_label")
        self.bacteria_sample_label.setGeometry(QRect(219, 20, 110, 50))
        self.bacteria_sample_label.setMinimumSize(QSize(110, 50))
        self.bacteria_sample_label.setMaximumSize(QSize(110, 50))
        self.bacteria_sample_label.setFont(font1)
        self.bacteria_sample_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_sample_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_sensitivity_label = QLabel(self.centralwidget)
        self.bacteria_sensitivity_label.setObjectName(u"bacteria_sensitivity_label")
        self.bacteria_sensitivity_label.setGeometry(QRect(340, 20, 580, 50))
        self.bacteria_sensitivity_label.setMinimumSize(QSize(580, 50))
        self.bacteria_sensitivity_label.setMaximumSize(QSize(580, 50))
        self.bacteria_sensitivity_label.setFont(font1)
        self.bacteria_sensitivity_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_sensitivity_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_sensitivity_frame = QFrame(self.centralwidget)
        self.bacteria_sensitivity_frame.setObjectName(u"bacteria_sensitivity_frame")
        self.bacteria_sensitivity_frame.setGeometry(QRect(340, 70, 580, 430))
        self.bacteria_sensitivity_frame.setMinimumSize(QSize(580, 430))
        self.bacteria_sensitivity_frame.setMaximumSize(QSize(580, 430))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        self.bacteria_sensitivity_frame.setFont(font2)
        self.bacteria_sensitivity_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_sensitivity_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.bacteria_amikacin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_amikacin_checkBox.setObjectName(u"bacteria_amikacin_checkBox")
        self.bacteria_amikacin_checkBox.setGeometry(QRect(20, 10, 170, 20))
        self.bacteria_amikacin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_amikacin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_amikacin_checkBox.setFont(font)
        self.bacteria_ampicillin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_ampicillin_checkBox.setObjectName(u"bacteria_ampicillin_checkBox")
        self.bacteria_ampicillin_checkBox.setGeometry(QRect(20, 40, 170, 20))
        self.bacteria_ampicillin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_ampicillin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_ampicillin_checkBox.setFont(font)
        self.bacteria_ceftazidime_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_ceftazidime_checkBox.setObjectName(u"bacteria_ceftazidime_checkBox")
        self.bacteria_ceftazidime_checkBox.setGeometry(QRect(20, 70, 170, 20))
        self.bacteria_ceftazidime_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_ceftazidime_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_ceftazidime_checkBox.setFont(font)
        self.bacteria_cephalexin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_cephalexin_checkBox.setObjectName(u"bacteria_cephalexin_checkBox")
        self.bacteria_cephalexin_checkBox.setGeometry(QRect(20, 100, 170, 20))
        self.bacteria_cephalexin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_cephalexin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_cephalexin_checkBox.setFont(font)
        self.bacteria_chloramphenicol_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_chloramphenicol_checkBox.setObjectName(u"bacteria_chloramphenicol_checkBox")
        self.bacteria_chloramphenicol_checkBox.setGeometry(QRect(20, 130, 170, 20))
        self.bacteria_chloramphenicol_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_chloramphenicol_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_chloramphenicol_checkBox.setFont(font)
        self.bacteria_enrofloxacin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_enrofloxacin_checkBox.setObjectName(u"bacteria_enrofloxacin_checkBox")
        self.bacteria_enrofloxacin_checkBox.setGeometry(QRect(20, 190, 170, 20))
        self.bacteria_enrofloxacin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_enrofloxacin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_enrofloxacin_checkBox.setFont(font)
        self.bacteria_gentamycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_gentamycin_checkBox.setObjectName(u"bacteria_gentamycin_checkBox")
        self.bacteria_gentamycin_checkBox.setGeometry(QRect(20, 220, 170, 20))
        self.bacteria_gentamycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_gentamycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_gentamycin_checkBox.setFont(font)
        self.bacteria_cloxacillin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_cloxacillin_checkBox.setObjectName(u"bacteria_cloxacillin_checkBox")
        self.bacteria_cloxacillin_checkBox.setGeometry(QRect(20, 160, 170, 20))
        self.bacteria_cloxacillin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_cloxacillin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_cloxacillin_checkBox.setFont(font)
        self.bacteria_polymyxcinB_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_polymyxcinB_checkBox.setObjectName(u"bacteria_polymyxcinB_checkBox")
        self.bacteria_polymyxcinB_checkBox.setGeometry(QRect(20, 340, 170, 20))
        self.bacteria_polymyxcinB_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_polymyxcinB_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_polymyxcinB_checkBox.setFont(font)
        self.bacteria_oxacillin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_oxacillin_checkBox.setObjectName(u"bacteria_oxacillin_checkBox")
        self.bacteria_oxacillin_checkBox.setGeometry(QRect(20, 310, 170, 20))
        self.bacteria_oxacillin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_oxacillin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_oxacillin_checkBox.setFont(font)
        self.bacteria_vancomycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_vancomycin_checkBox.setObjectName(u"bacteria_vancomycin_checkBox")
        self.bacteria_vancomycin_checkBox.setGeometry(QRect(20, 400, 170, 20))
        self.bacteria_vancomycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_vancomycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_vancomycin_checkBox.setFont(font)
        self.bacteria_sulfa_trimetroprom_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_sulfa_trimetroprom_checkBox.setObjectName(u"bacteria_sulfa_trimetroprom_checkBox")
        self.bacteria_sulfa_trimetroprom_checkBox.setGeometry(QRect(20, 370, 220, 20))
        self.bacteria_sulfa_trimetroprom_checkBox.setMinimumSize(QSize(220, 20))
        self.bacteria_sulfa_trimetroprom_checkBox.setMaximumSize(QSize(220, 20))
        self.bacteria_sulfa_trimetroprom_checkBox.setFont(font)
        self.bacteria_lincomycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_lincomycin_checkBox.setObjectName(u"bacteria_lincomycin_checkBox")
        self.bacteria_lincomycin_checkBox.setGeometry(QRect(20, 250, 170, 20))
        self.bacteria_lincomycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_lincomycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_lincomycin_checkBox.setFont(font)
        self.bacteria_norfloxacin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_norfloxacin_checkBox.setObjectName(u"bacteria_norfloxacin_checkBox")
        self.bacteria_norfloxacin_checkBox.setGeometry(QRect(20, 280, 170, 20))
        self.bacteria_norfloxacin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_norfloxacin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_norfloxacin_checkBox.setFont(font)
        self.bacteria_ciprofloxacin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_ciprofloxacin_checkBox.setObjectName(u"bacteria_ciprofloxacin_checkBox")
        self.bacteria_ciprofloxacin_checkBox.setGeometry(QRect(240, 130, 170, 20))
        self.bacteria_ciprofloxacin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_ciprofloxacin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_ciprofloxacin_checkBox.setFont(font)
        self.bacteria_colistin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_colistin_checkBox.setObjectName(u"bacteria_colistin_checkBox")
        self.bacteria_colistin_checkBox.setGeometry(QRect(240, 160, 170, 20))
        self.bacteria_colistin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_colistin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_colistin_checkBox.setFont(font)
        self.bacteria_oxytetracycline_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_oxytetracycline_checkBox.setObjectName(u"bacteria_oxytetracycline_checkBox")
        self.bacteria_oxytetracycline_checkBox.setGeometry(QRect(240, 310, 170, 20))
        self.bacteria_oxytetracycline_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_oxytetracycline_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_oxytetracycline_checkBox.setFont(font)
        self.bacteria_imipenem_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_imipenem_checkBox.setObjectName(u"bacteria_imipenem_checkBox")
        self.bacteria_imipenem_checkBox.setGeometry(QRect(240, 220, 170, 20))
        self.bacteria_imipenem_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_imipenem_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_imipenem_checkBox.setFont(font)
        self.bacteria_erythromycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_erythromycin_checkBox.setObjectName(u"bacteria_erythromycin_checkBox")
        self.bacteria_erythromycin_checkBox.setGeometry(QRect(240, 190, 170, 20))
        self.bacteria_erythromycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_erythromycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_erythromycin_checkBox.setFont(font)
        self.bacteria_amoxycillin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_amoxycillin_checkBox.setObjectName(u"bacteria_amoxycillin_checkBox")
        self.bacteria_amoxycillin_checkBox.setGeometry(QRect(240, 10, 170, 20))
        self.bacteria_amoxycillin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_amoxycillin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_amoxycillin_checkBox.setFont(font)
        self.bacteria_novobiocin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_novobiocin_checkBox.setObjectName(u"bacteria_novobiocin_checkBox")
        self.bacteria_novobiocin_checkBox.setGeometry(QRect(240, 280, 170, 20))
        self.bacteria_novobiocin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_novobiocin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_novobiocin_checkBox.setFont(font)
        self.bacteria_tetracycline_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_tetracycline_checkBox.setObjectName(u"bacteria_tetracycline_checkBox")
        self.bacteria_tetracycline_checkBox.setGeometry(QRect(240, 370, 170, 20))
        self.bacteria_tetracycline_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_tetracycline_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_tetracycline_checkBox.setFont(font)
        self.bacteria_ceftiofur_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_ceftiofur_checkBox.setObjectName(u"bacteria_ceftiofur_checkBox")
        self.bacteria_ceftiofur_checkBox.setGeometry(QRect(240, 70, 170, 20))
        self.bacteria_ceftiofur_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_ceftiofur_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_ceftiofur_checkBox.setFont(font)
        self.bacteria_cephalothin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_cephalothin_checkBox.setObjectName(u"bacteria_cephalothin_checkBox")
        self.bacteria_cephalothin_checkBox.setGeometry(QRect(240, 100, 170, 20))
        self.bacteria_cephalothin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_cephalothin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_cephalothin_checkBox.setFont(font)
        self.bacteria_rifampicin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_rifampicin_checkBox.setObjectName(u"bacteria_rifampicin_checkBox")
        self.bacteria_rifampicin_checkBox.setGeometry(QRect(240, 340, 170, 20))
        self.bacteria_rifampicin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_rifampicin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_rifampicin_checkBox.setFont(font)
        self.bacteria_neomycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_neomycin_checkBox.setObjectName(u"bacteria_neomycin_checkBox")
        self.bacteria_neomycin_checkBox.setGeometry(QRect(240, 250, 170, 20))
        self.bacteria_neomycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_neomycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_neomycin_checkBox.setFont(font)
        self.bacteria_bactracin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_bactracin_checkBox.setObjectName(u"bacteria_bactracin_checkBox")
        self.bacteria_bactracin_checkBox.setGeometry(QRect(240, 40, 170, 20))
        self.bacteria_bactracin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_bactracin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_bactracin_checkBox.setFont(font)
        self.bacteria_doxycycline_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_doxycycline_checkBox.setObjectName(u"bacteria_doxycycline_checkBox")
        self.bacteria_doxycycline_checkBox.setGeometry(QRect(420, 160, 170, 20))
        self.bacteria_doxycycline_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_doxycycline_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_doxycycline_checkBox.setFont(font)
        self.bacteria_optocin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_optocin_checkBox.setObjectName(u"bacteria_optocin_checkBox")
        self.bacteria_optocin_checkBox.setGeometry(QRect(420, 280, 170, 20))
        self.bacteria_optocin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_optocin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_optocin_checkBox.setFont(font)
        self.bacteria_tobramycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_tobramycin_checkBox.setObjectName(u"bacteria_tobramycin_checkBox")
        self.bacteria_tobramycin_checkBox.setGeometry(QRect(420, 370, 170, 20))
        self.bacteria_tobramycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_tobramycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_tobramycin_checkBox.setFont(font)
        self.bacteria_kanamycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_kanamycin_checkBox.setObjectName(u"bacteria_kanamycin_checkBox")
        self.bacteria_kanamycin_checkBox.setGeometry(QRect(420, 220, 170, 20))
        self.bacteria_kanamycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_kanamycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_kanamycin_checkBox.setFont(font)
        self.bacteria_nitrofurantoin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_nitrofurantoin_checkBox.setObjectName(u"bacteria_nitrofurantoin_checkBox")
        self.bacteria_nitrofurantoin_checkBox.setGeometry(QRect(420, 250, 170, 20))
        self.bacteria_nitrofurantoin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_nitrofurantoin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_nitrofurantoin_checkBox.setFont(font)
        self.bacteria_cephazolin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_cephazolin_checkBox.setObjectName(u"bacteria_cephazolin_checkBox")
        self.bacteria_cephazolin_checkBox.setGeometry(QRect(420, 100, 170, 20))
        self.bacteria_cephazolin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_cephazolin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_cephazolin_checkBox.setFont(font)
        self.bacteria_penicillin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_penicillin_checkBox.setObjectName(u"bacteria_penicillin_checkBox")
        self.bacteria_penicillin_checkBox.setGeometry(QRect(420, 310, 170, 20))
        self.bacteria_penicillin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_penicillin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_penicillin_checkBox.setFont(font)
        self.bacteria_clindamicin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_clindamicin_checkBox.setObjectName(u"bacteria_clindamicin_checkBox")
        self.bacteria_clindamicin_checkBox.setGeometry(QRect(420, 130, 170, 20))
        self.bacteria_clindamicin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_clindamicin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_clindamicin_checkBox.setFont(font)
        self.bacteria_fosfomycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_fosfomycin_checkBox.setObjectName(u"bacteria_fosfomycin_checkBox")
        self.bacteria_fosfomycin_checkBox.setGeometry(QRect(420, 190, 170, 20))
        self.bacteria_fosfomycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_fosfomycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_fosfomycin_checkBox.setFont(font)
        self.bacteria_amoxy_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_amoxy_checkBox.setObjectName(u"bacteria_amoxy_checkBox")
        self.bacteria_amoxy_checkBox.setGeometry(QRect(420, 10, 170, 20))
        self.bacteria_amoxy_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_amoxy_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_amoxy_checkBox.setFont(font)
        self.bacteria_streptomycin_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_streptomycin_checkBox.setObjectName(u"bacteria_streptomycin_checkBox")
        self.bacteria_streptomycin_checkBox.setGeometry(QRect(420, 340, 170, 20))
        self.bacteria_streptomycin_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_streptomycin_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_streptomycin_checkBox.setFont(font)
        self.bacteria_clav_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_clav_checkBox.setObjectName(u"bacteria_clav_checkBox")
        self.bacteria_clav_checkBox.setGeometry(QRect(420, 40, 170, 20))
        self.bacteria_clav_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_clav_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_clav_checkBox.setFont(font)
        self.bacteria_ceftriaxone_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_ceftriaxone_checkBox.setObjectName(u"bacteria_ceftriaxone_checkBox")
        self.bacteria_ceftriaxone_checkBox.setGeometry(QRect(420, 70, 170, 20))
        self.bacteria_ceftriaxone_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_ceftriaxone_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_ceftriaxone_checkBox.setFont(font)
        self.bacteria_other_sen_checkBox = QCheckBox(self.bacteria_sensitivity_frame)
        self.bacteria_other_sen_checkBox.setObjectName(u"bacteria_other_sen_checkBox")
        self.bacteria_other_sen_checkBox.setGeometry(QRect(240, 400, 170, 20))
        self.bacteria_other_sen_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_other_sen_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_other_sen_checkBox.setFont(font)
        self.bacteria_other_sen_lineEdit = QLineEdit(self.bacteria_sensitivity_frame)
        self.bacteria_other_sen_lineEdit.setObjectName(u"bacteria_other_sen_lineEdit")
        self.bacteria_other_sen_lineEdit.setGeometry(QRect(280, 400, 300, 20))
        self.bacteria_other_sen_lineEdit.setMinimumSize(QSize(300, 20))
        self.bacteria_other_sen_lineEdit.setMaximumSize(QSize(300, 20))
        self.bacteria_other_sen_lineEdit.setFont(font)
        self.bacteria_request_label = QLabel(self.centralwidget)
        self.bacteria_request_label.setObjectName(u"bacteria_request_label")
        self.bacteria_request_label.setGeometry(QRect(929, 20, 330, 50))
        self.bacteria_request_label.setMinimumSize(QSize(330, 50))
        self.bacteria_request_label.setMaximumSize(QSize(330, 50))
        self.bacteria_request_label.setFont(font1)
        self.bacteria_request_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_request_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_request_frame = QFrame(self.centralwidget)
        self.bacteria_request_frame.setObjectName(u"bacteria_request_frame")
        self.bacteria_request_frame.setGeometry(QRect(929, 70, 330, 331))
        self.bacteria_request_frame.setMinimumSize(QSize(330, 0))
        self.bacteria_request_frame.setMaximumSize(QSize(330, 16777215))
        self.bacteria_request_frame.setFont(font2)
        self.bacteria_request_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_request_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.bacteria_VITEK2_checkBox = QCheckBox(self.bacteria_request_frame)
        self.bacteria_VITEK2_checkBox.setObjectName(u"bacteria_VITEK2_checkBox")
        self.bacteria_VITEK2_checkBox.setGeometry(QRect(10, 210, 320, 20))
        self.bacteria_VITEK2_checkBox.setMinimumSize(QSize(320, 20))
        self.bacteria_VITEK2_checkBox.setMaximumSize(QSize(320, 20))
        self.bacteria_VITEK2_checkBox.setFont(font)
        self.bacteria_MIC_checkBox = QCheckBox(self.bacteria_request_frame)
        self.bacteria_MIC_checkBox.setObjectName(u"bacteria_MIC_checkBox")
        self.bacteria_MIC_checkBox.setGeometry(QRect(10, 270, 320, 20))
        self.bacteria_MIC_checkBox.setMinimumSize(QSize(320, 20))
        self.bacteria_MIC_checkBox.setMaximumSize(QSize(320, 20))
        self.bacteria_MIC_checkBox.setFont(font)
        self.bacteria_Identification_and_sensitive__checkBox = QCheckBox(self.bacteria_request_frame)
        self.bacteria_Identification_and_sensitive__checkBox.setObjectName(u"bacteria_Identification_and_sensitive__checkBox")
        self.bacteria_Identification_and_sensitive__checkBox.setGeometry(QRect(10, 65, 311, 61))
        self.bacteria_Identification_and_sensitive__checkBox.setMinimumSize(QSize(10, 20))
        self.bacteria_Identification_and_sensitive__checkBox.setMaximumSize(QSize(320, 100))
        self.bacteria_Identification_and_sensitive__checkBox.setFont(font)
        self.bacteria_Identification_and_sensitive__checkBox.setAutoFillBackground(False)
        self.bacteria_fungal_checkBox = QCheckBox(self.bacteria_request_frame)
        self.bacteria_fungal_checkBox.setObjectName(u"bacteria_fungal_checkBox")
        self.bacteria_fungal_checkBox.setGeometry(QRect(10, 15, 320, 20))
        self.bacteria_fungal_checkBox.setMinimumSize(QSize(320, 20))
        self.bacteria_fungal_checkBox.setMaximumSize(QSize(320, 20))
        self.bacteria_fungal_checkBox.setFont(font)
        self.bacteria_VITEK2_MIC_checkBox = QCheckBox(self.bacteria_request_frame)
        self.bacteria_VITEK2_MIC_checkBox.setObjectName(u"bacteria_VITEK2_MIC_checkBox")
        self.bacteria_VITEK2_MIC_checkBox.setGeometry(QRect(10, 150, 320, 20))
        self.bacteria_VITEK2_MIC_checkBox.setMinimumSize(QSize(320, 20))
        self.bacteria_VITEK2_MIC_checkBox.setMaximumSize(QSize(320, 20))
        self.bacteria_VITEK2_MIC_checkBox.setFont(font)
        self.bacteria_identification_frame = QFrame(self.centralwidget)
        self.bacteria_identification_frame.setObjectName(u"bacteria_identification_frame")
        self.bacteria_identification_frame.setGeometry(QRect(340, 550, 580, 160))
        self.bacteria_identification_frame.setMinimumSize(QSize(580, 160))
        self.bacteria_identification_frame.setMaximumSize(QSize(580, 160))
        self.bacteria_identification_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_identification_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.bacteria_klebsiella_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_klebsiella_checkBox.setObjectName(u"bacteria_klebsiella_checkBox")
        self.bacteria_klebsiella_checkBox.setGeometry(QRect(20, 90, 170, 20))
        self.bacteria_klebsiella_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_klebsiella_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_klebsiella_checkBox.setFont(font)
        self.bacteria_streptococcus_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_streptococcus_checkBox.setObjectName(u"bacteria_streptococcus_checkBox")
        self.bacteria_streptococcus_checkBox.setGeometry(QRect(20, 128, 170, 20))
        self.bacteria_streptococcus_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_streptococcus_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_streptococcus_checkBox.setFont(font)
        self.bacteria_actinobacillus_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_actinobacillus_checkBox.setObjectName(u"bacteria_actinobacillus_checkBox")
        self.bacteria_actinobacillus_checkBox.setGeometry(QRect(20, 14, 170, 20))
        self.bacteria_actinobacillus_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_actinobacillus_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_actinobacillus_checkBox.setFont(font)
        self.bacteria_corynebacterium_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_corynebacterium_checkBox.setObjectName(u"bacteria_corynebacterium_checkBox")
        self.bacteria_corynebacterium_checkBox.setGeometry(QRect(20, 52, 190, 20))
        self.bacteria_corynebacterium_checkBox.setMinimumSize(QSize(190, 20))
        self.bacteria_corynebacterium_checkBox.setMaximumSize(QSize(190, 20))
        self.bacteria_corynebacterium_checkBox.setFont(font)
        self.bacteria_staphylococcus_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_staphylococcus_checkBox.setObjectName(u"bacteria_staphylococcus_checkBox")
        self.bacteria_staphylococcus_checkBox.setGeometry(QRect(220, 128, 190, 20))
        self.bacteria_staphylococcus_checkBox.setMinimumSize(QSize(190, 20))
        self.bacteria_staphylococcus_checkBox.setMaximumSize(QSize(190, 20))
        self.bacteria_staphylococcus_checkBox.setFont(font)
        self.bacteria_aeromonas_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_aeromonas_checkBox.setObjectName(u"bacteria_aeromonas_checkBox")
        self.bacteria_aeromonas_checkBox.setGeometry(QRect(220, 14, 170, 20))
        self.bacteria_aeromonas_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_aeromonas_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_aeromonas_checkBox.setFont(font)
        self.bacteria_enterobacter_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_enterobacter_checkBox.setObjectName(u"bacteria_enterobacter_checkBox")
        self.bacteria_enterobacter_checkBox.setGeometry(QRect(220, 52, 170, 20))
        self.bacteria_enterobacter_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_enterobacter_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_enterobacter_checkBox.setFont(font)
        self.bacteria_pasteurella_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_pasteurella_checkBox.setObjectName(u"bacteria_pasteurella_checkBox")
        self.bacteria_pasteurella_checkBox.setGeometry(QRect(220, 90, 170, 20))
        self.bacteria_pasteurella_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_pasteurella_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_pasteurella_checkBox.setFont(font)
        self.bacteria_bordetella_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_bordetella_checkBox.setObjectName(u"bacteria_bordetella_checkBox")
        self.bacteria_bordetella_checkBox.setGeometry(QRect(420, 14, 170, 20))
        self.bacteria_bordetella_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_bordetella_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_bordetella_checkBox.setFont(font)
        self.bacteria_escherichia_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_escherichia_checkBox.setObjectName(u"bacteria_escherichia_checkBox")
        self.bacteria_escherichia_checkBox.setGeometry(QRect(420, 52, 170, 20))
        self.bacteria_escherichia_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_escherichia_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_escherichia_checkBox.setFont(font)
        self.bacteria_salmonella_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_salmonella_checkBox.setObjectName(u"bacteria_salmonella_checkBox")
        self.bacteria_salmonella_checkBox.setGeometry(QRect(420, 90, 170, 20))
        self.bacteria_salmonella_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_salmonella_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_salmonella_checkBox.setFont(font)
        self.bacteria_other_iden_checkBox = QCheckBox(self.bacteria_identification_frame)
        self.bacteria_other_iden_checkBox.setObjectName(u"bacteria_other_iden_checkBox")
        self.bacteria_other_iden_checkBox.setGeometry(QRect(420, 128, 170, 20))
        self.bacteria_other_iden_checkBox.setMinimumSize(QSize(170, 20))
        self.bacteria_other_iden_checkBox.setMaximumSize(QSize(170, 20))
        self.bacteria_other_iden_checkBox.setFont(font)
        self.bacteria_other_iden_lineEdit = QLineEdit(self.bacteria_identification_frame)
        self.bacteria_other_iden_lineEdit.setObjectName(u"bacteria_other_iden_lineEdit")
        self.bacteria_other_iden_lineEdit.setGeometry(QRect(450, 120, 130, 35))
        self.bacteria_other_iden_lineEdit.setMinimumSize(QSize(130, 35))
        self.bacteria_other_iden_lineEdit.setMaximumSize(QSize(130, 35))
        font3 = QFont()
        font3.setPointSize(20)
        self.bacteria_other_iden_lineEdit.setFont(font3)
        self.bacteria_identification_label = QLabel(self.centralwidget)
        self.bacteria_identification_label.setObjectName(u"bacteria_identification_label")
        self.bacteria_identification_label.setGeometry(QRect(340, 500, 580, 50))
        self.bacteria_identification_label.setMinimumSize(QSize(580, 50))
        self.bacteria_identification_label.setMaximumSize(QSize(580, 50))
        self.bacteria_identification_label.setFont(font1)
        self.bacteria_identification_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_identification_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_remark_frame = QFrame(self.centralwidget)
        self.bacteria_remark_frame.setObjectName(u"bacteria_remark_frame")
        self.bacteria_remark_frame.setGeometry(QRect(340, 759, 580, 120))
        self.bacteria_remark_frame.setMinimumSize(QSize(580, 120))
        self.bacteria_remark_frame.setMaximumSize(QSize(580, 120))
        self.bacteria_remark_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_remark_frame.setFrameShadow(QFrame.Shadow.Raised)
        self._bacteria_remark_plainTextEdit = QPlainTextEdit(self.bacteria_remark_frame)
        self._bacteria_remark_plainTextEdit.setObjectName(u"_bacteria_remark_plainTextEdit")
        self._bacteria_remark_plainTextEdit.setGeometry(QRect(10, 10, 560, 100))
        self._bacteria_remark_plainTextEdit.setMinimumSize(QSize(560, 100))
        self._bacteria_remark_plainTextEdit.setMaximumSize(QSize(560, 100))
        self._bacteria_remark_plainTextEdit.setFont(font)
        self.bacteria_remark_label = QLabel(self.centralwidget)
        self.bacteria_remark_label.setObjectName(u"bacteria_remark_label")
        self.bacteria_remark_label.setGeometry(QRect(339, 710, 580, 50))
        self.bacteria_remark_label.setMinimumSize(QSize(580, 50))
        self.bacteria_remark_label.setMaximumSize(QSize(580, 50))
        self.bacteria_remark_label.setFont(font1)
        self.bacteria_remark_label.setFrameShape(QFrame.Shape.Box)
        self.bacteria_remark_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bacteria_pay_frame = QFrame(self.centralwidget)
        self.bacteria_pay_frame.setObjectName(u"bacteria_pay_frame")
        self.bacteria_pay_frame.setGeometry(QRect(930, 409, 330, 471))
        self.bacteria_pay_frame.setMinimumSize(QSize(330, 0))
        self.bacteria_pay_frame.setMaximumSize(QSize(330, 16777215))
        self.bacteria_pay_frame.setFont(font2)
        self.bacteria_pay_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.bacteria_pay_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.bacteria_cal_pushButton = QPushButton(self.bacteria_pay_frame)
        self.bacteria_cal_pushButton.setObjectName(u"bacteria_cal_pushButton")
        self.bacteria_cal_pushButton.setGeometry(QRect(10, 10, 310, 60))
        self.bacteria_cal_pushButton.setMinimumSize(QSize(310, 60))
        self.bacteria_cal_pushButton.setMaximumSize(QSize(310, 60))
        self.bacteria_cal_pushButton.setFont(font)
        self.bacteria_cancel_pushButton = QPushButton(self.bacteria_pay_frame)
        self.bacteria_cancel_pushButton.setObjectName(u"bacteria_cancel_pushButton")
        self.bacteria_cancel_pushButton.setGeometry(QRect(10, 400, 310, 60))
        self.bacteria_cancel_pushButton.setMinimumSize(QSize(310, 60))
        self.bacteria_cancel_pushButton.setMaximumSize(QSize(310, 60))
        self.bacteria_cancel_pushButton.setFont(font)
        self.bacteria_save_pushButton = QPushButton(self.bacteria_pay_frame)
        self.bacteria_save_pushButton.setObjectName(u"bacteria_save_pushButton")
        self.bacteria_save_pushButton.setGeometry(QRect(10, 330, 310, 60))
        self.bacteria_save_pushButton.setMinimumSize(QSize(310, 60))
        self.bacteria_save_pushButton.setMaximumSize(QSize(310, 60))
        self.bacteria_save_pushButton.setFont(font)
        self.bacteria_num_lineEdit = QLineEdit(self.bacteria_pay_frame)
        self.bacteria_num_lineEdit.setObjectName(u"bacteria_num_lineEdit")
        self.bacteria_num_lineEdit.setGeometry(QRect(10, 150, 200, 40))
        self.bacteria_num_lineEdit.setMinimumSize(QSize(200, 40))
        self.bacteria_num_lineEdit.setMaximumSize(QSize(200, 40))
        self.bacteria_num_lineEdit.setFont(font)
        self.bacteria_num_label = QLabel(self.bacteria_pay_frame)
        self.bacteria_num_label.setObjectName(u"bacteria_num_label")
        self.bacteria_num_label.setGeometry(QRect(10, 110, 80, 40))
        self.bacteria_num_label.setMinimumSize(QSize(80, 40))
        self.bacteria_num_label.setMaximumSize(QSize(80, 40))
        self.bacteria_num_label.setFont(font)
        self.bacteria_list_label = QLabel(self.bacteria_pay_frame)
        self.bacteria_list_label.setObjectName(u"bacteria_list_label")
        self.bacteria_list_label.setGeometry(QRect(220, 150, 90, 40))
        self.bacteria_list_label.setMinimumSize(QSize(90, 40))
        self.bacteria_list_label.setMaximumSize(QSize(90, 40))
        self.bacteria_list_label.setFont(font)
        self.bacteria_baht_label = QLabel(self.bacteria_pay_frame)
        self.bacteria_baht_label.setObjectName(u"bacteria_baht_label")
        self.bacteria_baht_label.setGeometry(QRect(220, 260, 90, 40))
        self.bacteria_baht_label.setMinimumSize(QSize(90, 40))
        self.bacteria_baht_label.setMaximumSize(QSize(90, 40))
        self.bacteria_baht_label.setFont(font)
        self.bacteria_cost_label = QLabel(self.bacteria_pay_frame)
        self.bacteria_cost_label.setObjectName(u"bacteria_cost_label")
        self.bacteria_cost_label.setGeometry(QRect(10, 220, 80, 40))
        self.bacteria_cost_label.setMinimumSize(QSize(80, 40))
        self.bacteria_cost_label.setMaximumSize(QSize(80, 40))
        self.bacteria_cost_label.setFont(font)
        self.bacteria_cost_lineEdit = QLineEdit(self.bacteria_pay_frame)
        self.bacteria_cost_lineEdit.setObjectName(u"bacteria_cost_lineEdit")
        self.bacteria_cost_lineEdit.setGeometry(QRect(10, 260, 200, 40))
        self.bacteria_cost_lineEdit.setMinimumSize(QSize(200, 40))
        self.bacteria_cost_lineEdit.setMaximumSize(QSize(200, 40))
        self.bacteria_cost_lineEdit.setFont(font)
        bacteria_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(bacteria_MainWindow)

        QMetaObject.connectSlotsByName(bacteria_MainWindow)
    # setupUi

    def retranslateUi(self, bacteria_MainWindow):
        bacteria_MainWindow.setWindowTitle(QCoreApplication.translate("bacteria_MainWindow", u"MainWindow", None))
        self.bacteria_swabLT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Swab [LT]", None))
        self.bacteria_swabRT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Swab [RT]", None))
        self.bacteria_wound_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Wound", None))
        self.bacteria_aspirateLT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Aspirate [LT]", None))
        self.bacteria_catheterization_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Catheterization", None))
        self.bacteria_urine_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Urine", None))
        self.bacteria_tissuesLT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Tissues [LT]", None))
        self.bacteria_feces_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Feces", None))
        self.bacteria_aspirateRT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Aspirate [RT]", None))
        self.bacteria_blood_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Blood", None))
        self.bacteria_csf_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"CSF", None))
        self.bacteria_bodyFluidLT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Body fluid [LT]", None))
        self.bacteria_skinScaping_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Skin scraping", None))
        self.bacteria_midstream_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Midstream", None))
        self.bacteria_biopsyLT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"biopsy [LT]", None))
        self.bacteria_tissuesRT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Tissues [RT]", None))
        self.bacteria_cystocentesis_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Cystocentesis", None))
        self.bacteria_pus_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"PUS", None))
        self.bacteria_bodyFluidRT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Body fluid [RT]", None))
        self.bacteria_bloodAgar_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Blood agar", None))
        self.bacteria_biopsyRT_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"biopsy [RT]", None))
        self.bacteria_preparation_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"SAMPLE PREPARATION", None))
        self.bacteria_sample_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"SAMPLE", None))
        self.bacteria_sensitivity_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"DRUG SENSITIVITY (6-8 DRUGS)", None))
        self.bacteria_amikacin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Amikacin(AK)", None))
        self.bacteria_ampicillin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Ampicillin(AMP)", None))
        self.bacteria_ceftazidime_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Ceftazidime(CAZ)", None))
        self.bacteria_cephalexin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Cephalexin(CL)", None))
        self.bacteria_chloramphenicol_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Chloramphenicol(C)", None))
        self.bacteria_enrofloxacin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Enrofloxacin(ENR)", None))
        self.bacteria_gentamycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Gentamycin(CN)", None))
        self.bacteria_cloxacillin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Cloxacillin(OB)", None))
        self.bacteria_polymyxcinB_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"PolymyxcinB(PB)", None))
        self.bacteria_oxacillin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Oxacillin(OX)", None))
        self.bacteria_vancomycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Vancomycin(VA)", None))
        self.bacteria_sulfa_trimetroprom_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Sulfa-Trimetroprom(SXT)", None))
        self.bacteria_lincomycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Lincomycin(MY)", None))
        self.bacteria_norfloxacin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Norfloxacin(NOR)", None))
        self.bacteria_ciprofloxacin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Ciprofloxacin(CIP)", None))
        self.bacteria_colistin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Colistin(CT)", None))
        self.bacteria_oxytetracycline_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Oxytetracycline(OT)", None))
        self.bacteria_imipenem_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Imipenem(IPM)", None))
        self.bacteria_erythromycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Erythromycin(E)", None))
        self.bacteria_amoxycillin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Amoxycillin(AML)", None))
        self.bacteria_novobiocin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Novobiocin(NV)", None))
        self.bacteria_tetracycline_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Tetracycline(TE)", None))
        self.bacteria_ceftiofur_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Ceftiofur(EFT)", None))
        self.bacteria_cephalothin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Cephalothin(KF)", None))
        self.bacteria_rifampicin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Rifampicin(RD)", None))
        self.bacteria_neomycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Neomycin(N)", None))
        self.bacteria_bactracin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Bactracin(B)", None))
        self.bacteria_doxycycline_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Doxycycline(DO)", None))
        self.bacteria_optocin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Optocin(OP)", None))
        self.bacteria_tobramycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Tobramycin(TOB)", None))
        self.bacteria_kanamycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Kanamycin(K)", None))
        self.bacteria_nitrofurantoin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Nitrofurantoin(F)", None))
        self.bacteria_cephazolin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Cephazolin(KZ)", None))
        self.bacteria_penicillin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Penicillin(P)", None))
        self.bacteria_clindamicin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Clindamicin(DA)", None))
        self.bacteria_fosfomycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Fosfomycin(FOS)", None))
        self.bacteria_amoxy_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Amoxy(AMC)", None))
        self.bacteria_streptomycin_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Streptomycin(S)", None))
        self.bacteria_clav_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Clav(AMC)", None))
        self.bacteria_ceftriaxone_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Ceftriaxone(CRO)", None))
        self.bacteria_other_sen_checkBox.setText("")
        self.bacteria_request_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"LABORATORY REQUEST FOR", None))
        self.bacteria_VITEK2_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"VITEK2 iden (550)", None))
        self.bacteria_MIC_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"MIC (550)", None))
        self.bacteria_Identification_and_sensitive__checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Bacterial identification and \n"
"drug sensirivity (250)", None))
        self.bacteria_fungal_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Fungal culture and identification (250)", None))
        self.bacteria_VITEK2_MIC_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"VITEK2 with MIC (950)", None))
        self.bacteria_klebsiella_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Klebsiella spp.", None))
        self.bacteria_streptococcus_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Streptococus spp.", None))
        self.bacteria_actinobacillus_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Actinobacillus spp.", None))
        self.bacteria_corynebacterium_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Corynebacterium spp.", None))
        self.bacteria_staphylococcus_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Staphylococcus spp.", None))
        self.bacteria_aeromonas_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Aeromonas spp.", None))
        self.bacteria_enterobacter_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Enterobacter spp.", None))
        self.bacteria_pasteurella_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Pasteurella spp.", None))
        self.bacteria_bordetella_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Bordetella spp.", None))
        self.bacteria_escherichia_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Escherichia coli", None))
        self.bacteria_salmonella_checkBox.setText(QCoreApplication.translate("bacteria_MainWindow", u"Salmonella spp.", None))
        self.bacteria_other_iden_checkBox.setText("")
        self.bacteria_identification_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"BACTERIAL IDENTIFICATION (250)", None))
        self.bacteria_remark_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"REMARK", None))
        self.bacteria_cal_pushButton.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e04\u0e33\u0e19\u0e27\u0e19\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.bacteria_cancel_pushButton.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.bacteria_save_pushButton.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.bacteria_num_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.bacteria_list_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.bacteria_baht_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e1a\u0e32\u0e17", None))
        self.bacteria_cost_label.setText(QCoreApplication.translate("bacteria_MainWindow", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
    # retranslateUi

