# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'parasite.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QWidget)

class Ui_parasite_MainWindow(object):
    def setupUi(self, parasite_MainWindow):
        if not parasite_MainWindow.objectName():
            parasite_MainWindow.setObjectName(u"parasite_MainWindow")
        parasite_MainWindow.resize(1270, 890)
        parasite_MainWindow.setMinimumSize(QSize(1270, 890))
        parasite_MainWindow.setMaximumSize(QSize(1270, 890))
        self.centralwidget = QWidget(parasite_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.parasite_test_frame = QFrame(self.centralwidget)
        self.parasite_test_frame.setObjectName(u"parasite_test_frame")
        self.parasite_test_frame.setGeometry(QRect(10, 60, 931, 351))
        self.parasite_test_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.parasite_test_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.parasite_PCV_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_PCV_checkBox.setObjectName(u"parasite_PCV_checkBox")
        self.parasite_PCV_checkBox.setGeometry(QRect(20, 20, 100, 20))
        self.parasite_PCV_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_PCV_checkBox.setMaximumSize(QSize(100, 20))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        self.parasite_PCV_checkBox.setFont(font)
        self.parasite_floatation_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_floatation_checkBox.setObjectName(u"parasite_floatation_checkBox")
        self.parasite_floatation_checkBox.setGeometry(QRect(20, 60, 141, 20))
        self.parasite_floatation_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_floatation_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_floatation_checkBox.setFont(font)
        self.parasite_parasite_identification_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_parasite_identification_checkBox.setObjectName(u"parasite_parasite_identification_checkBox")
        self.parasite_parasite_identification_checkBox.setGeometry(QRect(20, 140, 241, 20))
        self.parasite_parasite_identification_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_parasite_identification_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_parasite_identification_checkBox.setFont(font)
        self.parasite_parasite_in_meat_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_parasite_in_meat_checkBox.setObjectName(u"parasite_parasite_in_meat_checkBox")
        self.parasite_parasite_in_meat_checkBox.setGeometry(QRect(20, 100, 201, 20))
        self.parasite_parasite_in_meat_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_parasite_in_meat_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_parasite_in_meat_checkBox.setFont(font)
        self.parasite_stained_Woo_PCV_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_stained_Woo_PCV_checkBox.setObjectName(u"parasite_stained_Woo_PCV_checkBox")
        self.parasite_stained_Woo_PCV_checkBox.setGeometry(QRect(20, 220, 361, 20))
        self.parasite_stained_Woo_PCV_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_stained_Woo_PCV_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_stained_Woo_PCV_checkBox.setFont(font)
        self.parasite_centrifugal_dog_cat_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_centrifugal_dog_cat_checkBox.setObjectName(u"parasite_centrifugal_dog_cat_checkBox")
        self.parasite_centrifugal_dog_cat_checkBox.setGeometry(QRect(20, 260, 401, 20))
        self.parasite_centrifugal_dog_cat_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_centrifugal_dog_cat_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_centrifugal_dog_cat_checkBox.setFont(font)
        self.parasite_floatation_centrifugal_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_floatation_centrifugal_checkBox.setObjectName(u"parasite_floatation_centrifugal_checkBox")
        self.parasite_floatation_centrifugal_checkBox.setGeometry(QRect(20, 300, 531, 20))
        self.parasite_floatation_centrifugal_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_floatation_centrifugal_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_floatation_centrifugal_checkBox.setFont(font)
        self.parasite_floatation_dog_cat_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_floatation_dog_cat_checkBox.setObjectName(u"parasite_floatation_dog_cat_checkBox")
        self.parasite_floatation_dog_cat_checkBox.setGeometry(QRect(20, 180, 271, 20))
        self.parasite_floatation_dog_cat_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_floatation_dog_cat_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_floatation_dog_cat_checkBox.setFont(font)
        self.parasite_stained_blood_smear_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_stained_blood_smear_checkBox.setObjectName(u"parasite_stained_blood_smear_checkBox")
        self.parasite_stained_blood_smear_checkBox.setGeometry(QRect(370, 20, 241, 20))
        self.parasite_stained_blood_smear_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_stained_blood_smear_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_stained_blood_smear_checkBox.setFont(font)
        self.parasite_sedimentation_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_sedimentation_checkBox.setObjectName(u"parasite_sedimentation_checkBox")
        self.parasite_sedimentation_checkBox.setGeometry(QRect(370, 60, 181, 20))
        self.parasite_sedimentation_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_sedimentation_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_sedimentation_checkBox.setFont(font)
        self.parasite_Woo_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_Woo_checkBox.setObjectName(u"parasite_Woo_checkBox")
        self.parasite_Woo_checkBox.setGeometry(QRect(670, 20, 141, 20))
        self.parasite_Woo_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_Woo_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_Woo_checkBox.setFont(font)
        self.parasite_mc_master_egg_count_checkBox = QCheckBox(self.parasite_test_frame)
        self.parasite_mc_master_egg_count_checkBox.setObjectName(u"parasite_mc_master_egg_count_checkBox")
        self.parasite_mc_master_egg_count_checkBox.setGeometry(QRect(670, 60, 241, 20))
        self.parasite_mc_master_egg_count_checkBox.setMinimumSize(QSize(80, 20))
        self.parasite_mc_master_egg_count_checkBox.setMaximumSize(QSize(1000, 20))
        self.parasite_mc_master_egg_count_checkBox.setFont(font)
        self.parasite_pay_frame = QFrame(self.centralwidget)
        self.parasite_pay_frame.setObjectName(u"parasite_pay_frame")
        self.parasite_pay_frame.setGeometry(QRect(950, 10, 311, 401))
        self.parasite_pay_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.parasite_pay_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.parasite_summary_frame = QFrame(self.parasite_pay_frame)
        self.parasite_summary_frame.setObjectName(u"parasite_summary_frame")
        self.parasite_summary_frame.setGeometry(QRect(10, 70, 291, 201))
        self.parasite_summary_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.parasite_summary_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.parasite_num_lineEdit = QLineEdit(self.parasite_summary_frame)
        self.parasite_num_lineEdit.setObjectName(u"parasite_num_lineEdit")
        self.parasite_num_lineEdit.setGeometry(QRect(20, 40, 191, 40))
        self.parasite_num_lineEdit.setFont(font)
        self.parasite_list_label = QLabel(self.parasite_summary_frame)
        self.parasite_list_label.setObjectName(u"parasite_list_label")
        self.parasite_list_label.setGeometry(QRect(220, 50, 71, 21))
        self.parasite_list_label.setFont(font)
        self.parasite_num_label = QLabel(self.parasite_summary_frame)
        self.parasite_num_label.setObjectName(u"parasite_num_label")
        self.parasite_num_label.setGeometry(QRect(20, 10, 71, 31))
        self.parasite_num_label.setFont(font)
        self.parasite_cost_label = QLabel(self.parasite_summary_frame)
        self.parasite_cost_label.setObjectName(u"parasite_cost_label")
        self.parasite_cost_label.setGeometry(QRect(20, 110, 81, 30))
        self.parasite_cost_label.setFont(font)
        self.parasit_cost_lineEdit = QLineEdit(self.parasite_summary_frame)
        self.parasit_cost_lineEdit.setObjectName(u"parasit_cost_lineEdit")
        self.parasit_cost_lineEdit.setGeometry(QRect(20, 140, 191, 40))
        self.parasit_cost_lineEdit.setFont(font)
        self.parasite_baht_label = QLabel(self.parasite_summary_frame)
        self.parasite_baht_label.setObjectName(u"parasite_baht_label")
        self.parasite_baht_label.setGeometry(QRect(220, 145, 71, 21))
        self.parasite_baht_label.setFont(font)
        self.parasite_save_pushButton = QPushButton(self.parasite_pay_frame)
        self.parasite_save_pushButton.setObjectName(u"parasite_save_pushButton")
        self.parasite_save_pushButton.setGeometry(QRect(10, 280, 291, 51))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.parasite_save_pushButton.setFont(font1)
        self.parasite_cancel_pushButton = QPushButton(self.parasite_pay_frame)
        self.parasite_cancel_pushButton.setObjectName(u"parasite_cancel_pushButton")
        self.parasite_cancel_pushButton.setGeometry(QRect(10, 340, 291, 51))
        self.parasite_cancel_pushButton.setFont(font1)
        self.parasite_pay_pushButton = QPushButton(self.parasite_pay_frame)
        self.parasite_pay_pushButton.setObjectName(u"parasite_pay_pushButton")
        self.parasite_pay_pushButton.setGeometry(QRect(10, 10, 291, 51))
        self.parasite_pay_pushButton.setFont(font1)
        self.parasite_test_label = QLabel(self.centralwidget)
        self.parasite_test_label.setObjectName(u"parasite_test_label")
        self.parasite_test_label.setGeometry(QRect(10, 10, 931, 51))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(20)
        font2.setBold(True)
        font2.setUnderline(False)
        self.parasite_test_label.setFont(font2)
        self.parasite_test_label.setAutoFillBackground(False)
        self.parasite_test_label.setFrameShape(QFrame.Shape.Box)
        self.parasite_test_label.setLineWidth(2)
        self.parasite_test_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.parasite_test_label.setWordWrap(False)
        parasite_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(parasite_MainWindow)

        QMetaObject.connectSlotsByName(parasite_MainWindow)
    # setupUi

    def retranslateUi(self, parasite_MainWindow):
        parasite_MainWindow.setWindowTitle(QCoreApplication.translate("parasite_MainWindow", u"MainWindow", None))
        self.parasite_PCV_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"PCV (50)", None))
        self.parasite_floatation_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Floatation (50)", None))
        self.parasite_parasite_identification_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Parasite identification (100)", None))
        self.parasite_parasite_in_meat_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Parasite in meat (300)", None))
        self.parasite_stained_Woo_PCV_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Stained blood smear + Woo's + PCV (150)", None))
        self.parasite_centrifugal_dog_cat_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Centrifugal sedimentation for dog and cat (150)", None))
        self.parasite_floatation_centrifugal_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Floatation test + Centrifugal sedimentation for dog and cat (200)", None))
        self.parasite_floatation_dog_cat_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Floatation for dog and cat (100)", None))
        self.parasite_stained_blood_smear_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Stained blood smear (100)", None))
        self.parasite_sedimentation_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Sedimentation (50)", None))
        self.parasite_Woo_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Woo's (50)", None))
        self.parasite_mc_master_egg_count_checkBox.setText(QCoreApplication.translate("parasite_MainWindow", u"Mc Master egg count (100)", None))
        self.parasite_list_label.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.parasite_num_label.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.parasite_cost_label.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.parasite_baht_label.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e1a\u0e32\u0e17", None))
        self.parasite_save_pushButton.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.parasite_cancel_pushButton.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
        self.parasite_pay_pushButton.setText(QCoreApplication.translate("parasite_MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.parasite_test_label.setText(QCoreApplication.translate("parasite_MainWindow", u"TEST", None))
    # retranslateUi

