# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'register_new_customer.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QTextEdit, QWidget)

class Ui_register_new_customer_MainWindow(object):
    def setupUi(self, register_new_customer_MainWindow):
        if not register_new_customer_MainWindow.objectName():
            register_new_customer_MainWindow.setObjectName(u"register_new_customer_MainWindow")
        register_new_customer_MainWindow.resize(1270, 890)
        register_new_customer_MainWindow.setMinimumSize(QSize(1270, 890))
        register_new_customer_MainWindow.setMaximumSize(QSize(1270, 890))
        self.centralwidget = QWidget(register_new_customer_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1080, 0, 191, 41))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.Add_new_costumer_frame = QFrame(self.centralwidget)
        self.Add_new_costumer_frame.setObjectName(u"Add_new_costumer_frame")
        self.Add_new_costumer_frame.setGeometry(QRect(5, 5, 1061, 881))
        self.Add_new_costumer_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Add_new_costumer_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Add_new_costumer_private_radioButton = QRadioButton(self.Add_new_costumer_frame)
        self.Add_new_costumer_private_radioButton.setObjectName(u"Add_new_costumer_private_radioButton")
        self.Add_new_costumer_private_radioButton.setGeometry(QRect(30, 30, 151, 31))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.Add_new_costumer_private_radioButton.setFont(font1)
        self.Add_new_costumer_public_radioButton = QRadioButton(self.Add_new_costumer_frame)
        self.Add_new_costumer_public_radioButton.setObjectName(u"Add_new_costumer_public_radioButton")
        self.Add_new_costumer_public_radioButton.setGeometry(QRect(240, 30, 111, 31))
        self.Add_new_costumer_public_radioButton.setFont(font1)
        self.Add_new_costumer_internal_radioButton = QRadioButton(self.Add_new_costumer_frame)
        self.Add_new_costumer_internal_radioButton.setObjectName(u"Add_new_costumer_internal_radioButton")
        self.Add_new_costumer_internal_radioButton.setGeometry(QRect(420, 30, 171, 31))
        self.Add_new_costumer_internal_radioButton.setFont(font1)
        self.Add_new_costumer_professor_radioButton = QRadioButton(self.Add_new_costumer_frame)
        self.Add_new_costumer_professor_radioButton.setObjectName(u"Add_new_costumer_professor_radioButton")
        self.Add_new_costumer_professor_radioButton.setEnabled(True)
        self.Add_new_costumer_professor_radioButton.setGeometry(QRect(660, 30, 161, 31))
        self.Add_new_costumer_professor_radioButton.setFont(font1)
        self.Add_new_costumer_professor_radioButton.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Add_new_costumer_professor_radioButton.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Add_new_costumer_professor_radioButton.setAutoFillBackground(False)
        self.Add_new_costumer_student_radioButton = QRadioButton(self.Add_new_costumer_frame)
        self.Add_new_costumer_student_radioButton.setObjectName(u"Add_new_costumer_student_radioButton")
        self.Add_new_costumer_student_radioButton.setGeometry(QRect(880, 30, 151, 31))
        self.Add_new_costumer_student_radioButton.setFont(font1)
        self.register_add_new_customer_frame = QFrame(self.Add_new_costumer_frame)
        self.register_add_new_customer_frame.setObjectName(u"register_add_new_customer_frame")
        self.register_add_new_customer_frame.setGeometry(QRect(10, 100, 1041, 771))
        self.register_add_new_customer_frame.setFrameShape(QFrame.Shape.Box)
        self.register_add_new_customer_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.name_label = QLabel(self.register_add_new_customer_frame)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(330, 20, 81, 41))
        self.name_label.setFont(font1)
        self.name_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.name_lineEdit.setObjectName(u"name_lineEdit")
        self.name_lineEdit.setGeometry(QRect(420, 20, 611, 41))
        self.name_lineEdit.setFont(font1)
        self.name_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_name_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.title_name_lineEdit.setObjectName(u"title_name_lineEdit")
        self.title_name_lineEdit.setGeometry(QRect(140, 20, 171, 41))
        self.title_name_lineEdit.setFont(font1)
        self.title_name_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_name_label = QLabel(self.register_add_new_customer_frame)
        self.title_name_label.setObjectName(u"title_name_label")
        self.title_name_label.setGeometry(QRect(10, 20, 111, 41))
        self.title_name_label.setFont(font1)
        self.sure_name_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.sure_name_lineEdit.setObjectName(u"sure_name_lineEdit")
        self.sure_name_lineEdit.setGeometry(QRect(140, 80, 421, 41))
        self.sure_name_lineEdit.setFont(font1)
        self.sure_name_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sure_name_label = QLabel(self.register_add_new_customer_frame)
        self.sure_name_label.setObjectName(u"sure_name_label")
        self.sure_name_label.setGeometry(QRect(10, 80, 121, 41))
        self.sure_name_label.setFont(font1)
        self.tax_id_label = QLabel(self.register_add_new_customer_frame)
        self.tax_id_label.setObjectName(u"tax_id_label")
        self.tax_id_label.setGeometry(QRect(10, 140, 241, 41))
        self.tax_id_label.setFont(font1)
        self.tax_id_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.tax_id_lineEdit.setObjectName(u"tax_id_lineEdit")
        self.tax_id_lineEdit.setGeometry(QRect(10, 190, 561, 41))
        self.tax_id_lineEdit.setFont(font1)
        self.tax_id_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.not_tax_id_radioButton = QRadioButton(self.register_add_new_customer_frame)
        self.not_tax_id_radioButton.setObjectName(u"not_tax_id_radioButton")
        self.not_tax_id_radioButton.setGeometry(QRect(250, 140, 281, 41))
        self.not_tax_id_radioButton.setFont(font1)
        self.email_label = QLabel(self.register_add_new_customer_frame)
        self.email_label.setObjectName(u"email_label")
        self.email_label.setGeometry(QRect(10, 250, 61, 41))
        self.email_label.setFont(font1)
        self.email_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.email_lineEdit.setObjectName(u"email_lineEdit")
        self.email_lineEdit.setGeometry(QRect(90, 250, 481, 41))
        self.email_lineEdit.setFont(font1)
        self.email_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_id_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.line_id_lineEdit.setObjectName(u"line_id_lineEdit")
        self.line_id_lineEdit.setGeometry(QRect(660, 140, 371, 41))
        self.line_id_lineEdit.setFont(font1)
        self.line_id_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_id_label = QLabel(self.register_add_new_customer_frame)
        self.line_id_label.setObjectName(u"line_id_label")
        self.line_id_label.setGeometry(QRect(580, 140, 61, 41))
        self.line_id_label.setFont(font1)
        self.phone_label = QLabel(self.register_add_new_customer_frame)
        self.phone_label.setObjectName(u"phone_label")
        self.phone_label.setGeometry(QRect(580, 80, 81, 41))
        self.phone_label.setFont(font1)
        self.phone_lineEdit = QLineEdit(self.register_add_new_customer_frame)
        self.phone_lineEdit.setObjectName(u"phone_lineEdit")
        self.phone_lineEdit.setGeometry(QRect(660, 80, 371, 41))
        self.phone_lineEdit.setFont(font1)
        self.phone_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.address_contact_label = QLabel(self.register_add_new_customer_frame)
        self.address_contact_label.setObjectName(u"address_contact_label")
        self.address_contact_label.setGeometry(QRect(10, 310, 151, 41))
        self.address_contact_label.setFont(font1)
        self.address_contact_textEdit = QTextEdit(self.register_add_new_customer_frame)
        self.address_contact_textEdit.setObjectName(u"address_contact_textEdit")
        self.address_contact_textEdit.setGeometry(QRect(10, 360, 1021, 121))
        self.address_contact_textEdit.setFrameShape(QFrame.Shape.Box)
        self.address_billing_label = QLabel(self.register_add_new_customer_frame)
        self.address_billing_label.setObjectName(u"address_billing_label")
        self.address_billing_label.setGeometry(QRect(10, 500, 201, 41))
        self.address_billing_label.setFont(font1)
        self.address_billing_textEdit = QTextEdit(self.register_add_new_customer_frame)
        self.address_billing_textEdit.setObjectName(u"address_billing_textEdit")
        self.address_billing_textEdit.setGeometry(QRect(10, 550, 1021, 121))
        self.address_billing_textEdit.setFrameShape(QFrame.Shape.Box)
        self.address_same_contack_checkBox = QCheckBox(self.register_add_new_customer_frame)
        self.address_same_contack_checkBox.setObjectName(u"address_same_contack_checkBox")
        self.address_same_contack_checkBox.setGeometry(QRect(220, 505, 241, 31))
        self.address_same_contack_checkBox.setFont(font1)
        self.register_add_new_customer_frame.raise_()
        self.Add_new_costumer_private_radioButton.raise_()
        self.Add_new_costumer_public_radioButton.raise_()
        self.Add_new_costumer_internal_radioButton.raise_()
        self.Add_new_costumer_professor_radioButton.raise_()
        self.Add_new_costumer_student_radioButton.raise_()
        self.Add_new_costumer_save_pushButton = QPushButton(self.centralwidget)
        self.Add_new_costumer_save_pushButton.setObjectName(u"Add_new_costumer_save_pushButton")
        self.Add_new_costumer_save_pushButton.setGeometry(QRect(1080, 60, 181, 61))
        font2 = QFont()
        font2.setPointSize(22)
        self.Add_new_costumer_save_pushButton.setFont(font2)
        self.Add_new_costumer_cancel_pushButton = QPushButton(self.centralwidget)
        self.Add_new_costumer_cancel_pushButton.setObjectName(u"Add_new_costumer_cancel_pushButton")
        self.Add_new_costumer_cancel_pushButton.setGeometry(QRect(1080, 160, 181, 61))
        self.Add_new_costumer_cancel_pushButton.setFont(font2)
        register_new_customer_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_new_customer_MainWindow)

        QMetaObject.connectSlotsByName(register_new_customer_MainWindow)
    # setupUi

    def retranslateUi(self, register_new_customer_MainWindow):
        register_new_customer_MainWindow.setWindowTitle(QCoreApplication.translate("register_new_customer_MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e25\u0e07\u0e17\u0e30\u0e40\u0e1a\u0e35\u0e22\u0e19\u0e25\u0e39\u0e01\u0e04\u0e49\u0e32\u0e43\u0e2b\u0e21\u0e48", None))
        self.Add_new_costumer_private_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e1a\u0e38\u0e04\u0e04\u0e25\u0e18\u0e23\u0e23\u0e21\u0e14\u0e32", None))
        self.Add_new_costumer_public_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e19\u0e34\u0e15\u0e34\u0e1a\u0e38\u0e04\u0e04\u0e25", None))
        self.Add_new_costumer_internal_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e2b\u0e19\u0e48\u0e27\u0e22\u0e07\u0e32\u0e19\u0e20\u0e32\u0e22\u0e43\u0e19", None))
        self.Add_new_costumer_professor_radioButton.setAccessibleIdentifier("")
        self.Add_new_costumer_professor_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e2d\u0e32\u0e08\u0e32\u0e23\u0e22\u0e4c\u0e43\u0e19\u0e04\u0e13\u0e30", None))
        self.Add_new_costumer_student_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e19\u0e31\u0e01\u0e28\u0e36\u0e01\u0e29\u0e32", None))
        self.name_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d\u0e25\u0e39\u0e01\u0e04\u0e49\u0e32", None))
        self.title_name_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e04\u0e33\u0e19\u0e33\u0e2b\u0e19\u0e49\u0e32\u0e0a\u0e37\u0e48\u0e2d", None))
        self.sure_name_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25\u0e25\u0e39\u0e01\u0e04\u0e49\u0e32", None))
        self.tax_id_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e40\u0e25\u0e02\u0e1b\u0e23\u0e30\u0e08\u0e33\u0e15\u0e31\u0e27\u0e1c\u0e39\u0e49\u0e40\u0e2a\u0e35\u0e22\u0e20\u0e32\u0e29\u0e35", None))
        self.not_tax_id_radioButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e44\u0e21\u0e48\u0e23\u0e30\u0e1a\u0e38 \u0e40\u0e25\u0e02\u0e1b\u0e23\u0e30\u0e08\u0e33\u0e15\u0e31\u0e27\u0e1c\u0e39\u0e49\u0e40\u0e2a\u0e35\u0e22\u0e20\u0e32\u0e29\u0e35", None))
        self.email_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"EMAIL", None))
        self.line_id_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"Line ID", None))
        self.phone_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e40\u0e1a\u0e2d\u0e23\u0e4c\u0e42\u0e17\u0e23", None))
        self.address_contact_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e17\u0e35\u0e48\u0e2d\u0e22\u0e39\u0e48\u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e15\u0e34\u0e14\u0e15\u0e48\u0e2d", None))
        self.address_billing_label.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e17\u0e35\u0e48\u0e2d\u0e22\u0e39\u0e48\u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e2d\u0e2d\u0e01\u0e43\u0e1a\u0e40\u0e2a\u0e23\u0e47\u0e08", None))
        self.address_same_contack_checkBox.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e17\u0e35\u0e48\u0e2d\u0e22\u0e39\u0e48\u0e40\u0e14\u0e35\u0e22\u0e27\u0e01\u0e31\u0e19\u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e15\u0e34\u0e14\u0e15\u0e48\u0e2d", None))
        self.Add_new_costumer_save_pushButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.Add_new_costumer_cancel_pushButton.setText(QCoreApplication.translate("register_new_customer_MainWindow", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
    # retranslateUi

