# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'specimen.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDateTimeEdit, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_specimen_MainWindow(object):
    def setupUi(self, specimen_MainWindow):
        if not specimen_MainWindow.objectName():
            specimen_MainWindow.setObjectName(u"specimen_MainWindow")
        specimen_MainWindow.resize(1270, 890)
        specimen_MainWindow.setMinimumSize(QSize(1270, 890))
        specimen_MainWindow.setMaximumSize(QSize(1270, 890))
        self.centralwidget = QWidget(specimen_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.specimen_frame = QFrame(self.centralwidget)
        self.specimen_frame.setObjectName(u"specimen_frame")
        self.specimen_frame.setGeometry(QRect(0, 10, 1260, 870))
        self.specimen_frame.setMinimumSize(QSize(1260, 870))
        self.specimen_frame.setMaximumSize(QSize(1260, 870))
        self.specimen_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.specimen_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.specimen_name_label = QLabel(self.specimen_frame)
        self.specimen_name_label.setObjectName(u"specimen_name_label")
        self.specimen_name_label.setGeometry(QRect(20, 10, 60, 40))
        self.specimen_name_label.setMinimumSize(QSize(60, 40))
        self.specimen_name_label.setMaximumSize(QSize(60, 40))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        self.specimen_name_label.setFont(font)
        self.specimen_ID_label = QLabel(self.specimen_frame)
        self.specimen_ID_label.setObjectName(u"specimen_ID_label")
        self.specimen_ID_label.setGeometry(QRect(20, 80, 150, 40))
        self.specimen_ID_label.setMinimumSize(QSize(150, 40))
        self.specimen_ID_label.setMaximumSize(QSize(150, 40))
        self.specimen_ID_label.setFont(font)
        self.specimen_name_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_name_lineEdit.setObjectName(u"specimen_name_lineEdit")
        self.specimen_name_lineEdit.setGeometry(QRect(190, 10, 270, 40))
        self.specimen_name_lineEdit.setMinimumSize(QSize(270, 40))
        self.specimen_name_lineEdit.setMaximumSize(QSize(270, 40))
        self.specimen_name_lineEdit.setFont(font)
        self.specimen_name_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_ID_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_ID_lineEdit.setObjectName(u"specimen_ID_lineEdit")
        self.specimen_ID_lineEdit.setGeometry(QRect(190, 80, 260, 40))
        self.specimen_ID_lineEdit.setMinimumSize(QSize(260, 40))
        self.specimen_ID_lineEdit.setMaximumSize(QSize(260, 40))
        self.specimen_ID_lineEdit.setFont(font)
        self.specimen_ID_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_sex_label = QLabel(self.specimen_frame)
        self.specimen_sex_label.setObjectName(u"specimen_sex_label")
        self.specimen_sex_label.setGeometry(QRect(490, 10, 90, 40))
        self.specimen_sex_label.setMinimumSize(QSize(90, 40))
        self.specimen_sex_label.setMaximumSize(QSize(90, 40))
        self.specimen_sex_label.setFont(font)
        self.specimen_sex_comboBox = QComboBox(self.specimen_frame)
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.addItem("")
        self.specimen_sex_comboBox.setObjectName(u"specimen_sex_comboBox")
        self.specimen_sex_comboBox.setGeometry(QRect(590, 10, 180, 40))
        self.specimen_sex_comboBox.setMinimumSize(QSize(180, 40))
        self.specimen_sex_comboBox.setMaximumSize(QSize(180, 40))
        self.specimen_sex_comboBox.setFont(font)
        self.specimen_age_label = QLabel(self.specimen_frame)
        self.specimen_age_label.setObjectName(u"specimen_age_label")
        self.specimen_age_label.setGeometry(QRect(490, 80, 90, 40))
        self.specimen_age_label.setMinimumSize(QSize(90, 40))
        self.specimen_age_label.setMaximumSize(QSize(90, 40))
        self.specimen_age_label.setFont(font)
        self.specimen_ageYear_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_ageYear_lineEdit.setObjectName(u"specimen_ageYear_lineEdit")
        self.specimen_ageYear_lineEdit.setGeometry(QRect(590, 80, 70, 40))
        self.specimen_ageYear_lineEdit.setMinimumSize(QSize(70, 40))
        self.specimen_ageYear_lineEdit.setMaximumSize(QSize(70, 40))
        self.specimen_ageYear_lineEdit.setFont(font)
        self.specimen_ageYear_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_ageYear_label = QLabel(self.specimen_frame)
        self.specimen_ageYear_label.setObjectName(u"specimen_ageYear_label")
        self.specimen_ageYear_label.setGeometry(QRect(680, 80, 20, 40))
        self.specimen_ageYear_label.setMinimumSize(QSize(20, 40))
        self.specimen_ageYear_label.setMaximumSize(QSize(20, 40))
        self.specimen_ageYear_label.setFont(font)
        self.specimen_ageMonth_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_ageMonth_lineEdit.setObjectName(u"specimen_ageMonth_lineEdit")
        self.specimen_ageMonth_lineEdit.setGeometry(QRect(710, 80, 70, 40))
        self.specimen_ageMonth_lineEdit.setMinimumSize(QSize(70, 40))
        self.specimen_ageMonth_lineEdit.setMaximumSize(QSize(70, 40))
        self.specimen_ageMonth_lineEdit.setFont(font)
        self.specimen_ageMonth_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_ageMonth_label = QLabel(self.specimen_frame)
        self.specimen_ageMonth_label.setObjectName(u"specimen_ageMonth_label")
        self.specimen_ageMonth_label.setGeometry(QRect(790, 80, 50, 40))
        self.specimen_ageMonth_label.setMinimumSize(QSize(50, 40))
        self.specimen_ageMonth_label.setMaximumSize(QSize(50, 40))
        self.specimen_ageMonth_label.setFont(font)
        self.specimen_ageDay_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_ageDay_lineEdit.setObjectName(u"specimen_ageDay_lineEdit")
        self.specimen_ageDay_lineEdit.setGeometry(QRect(840, 80, 70, 40))
        self.specimen_ageDay_lineEdit.setMinimumSize(QSize(70, 40))
        self.specimen_ageDay_lineEdit.setMaximumSize(QSize(70, 40))
        self.specimen_ageDay_lineEdit.setFont(font)
        self.specimen_ageDay_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_ageDay_label = QLabel(self.specimen_frame)
        self.specimen_ageDay_label.setObjectName(u"specimen_ageDay_label")
        self.specimen_ageDay_label.setGeometry(QRect(920, 80, 30, 40))
        self.specimen_ageDay_label.setMinimumSize(QSize(30, 40))
        self.specimen_ageDay_label.setMaximumSize(QSize(30, 40))
        self.specimen_ageDay_label.setFont(font)
        self.specimen_ageUnknown_checkBox = QCheckBox(self.specimen_frame)
        self.specimen_ageUnknown_checkBox.setObjectName(u"specimen_ageUnknown_checkBox")
        self.specimen_ageUnknown_checkBox.setGeometry(QRect(970, 80, 120, 40))
        self.specimen_ageUnknown_checkBox.setMinimumSize(QSize(120, 40))
        self.specimen_ageUnknown_checkBox.setMaximumSize(QSize(120, 40))
        self.specimen_ageUnknown_checkBox.setFont(font)
        self.specimen_speedStatus_frame = QFrame(self.specimen_frame)
        self.specimen_speedStatus_frame.setObjectName(u"specimen_speedStatus_frame")
        self.specimen_speedStatus_frame.setGeometry(QRect(1100, 10, 150, 160))
        self.specimen_speedStatus_frame.setMinimumSize(QSize(150, 160))
        self.specimen_speedStatus_frame.setMaximumSize(QSize(150, 160))
        self.specimen_speedStatus_frame.setFrameShape(QFrame.Shape.Box)
        self.specimen_speedStatus_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.specimen_status_label = QLabel(self.specimen_speedStatus_frame)
        self.specimen_status_label.setObjectName(u"specimen_status_label")
        self.specimen_status_label.setGeometry(QRect(10, 10, 120, 40))
        self.specimen_status_label.setMinimumSize(QSize(120, 40))
        self.specimen_status_label.setMaximumSize(QSize(120, 40))
        self.specimen_status_label.setFont(font)
        self.specimen_normal_radioButton = QRadioButton(self.specimen_speedStatus_frame)
        self.specimen_normal_radioButton.setObjectName(u"specimen_normal_radioButton")
        self.specimen_normal_radioButton.setGeometry(QRect(10, 50, 90, 40))
        self.specimen_normal_radioButton.setMinimumSize(QSize(90, 40))
        self.specimen_normal_radioButton.setMaximumSize(QSize(90, 40))
        self.specimen_normal_radioButton.setFont(font)
        self.specimen_most_urgent_radioButton = QRadioButton(self.specimen_speedStatus_frame)
        self.specimen_most_urgent_radioButton.setObjectName(u"specimen_most_urgent_radioButton")
        self.specimen_most_urgent_radioButton.setGeometry(QRect(10, 100, 100, 40))
        self.specimen_most_urgent_radioButton.setMinimumSize(QSize(100, 40))
        self.specimen_most_urgent_radioButton.setMaximumSize(QSize(100, 40))
        self.specimen_most_urgent_radioButton.setFont(font)
        self.specimen_death_label = QLabel(self.specimen_frame)
        self.specimen_death_label.setObjectName(u"specimen_death_label")
        self.specimen_death_label.setGeometry(QRect(780, 10, 150, 40))
        self.specimen_death_label.setMinimumSize(QSize(150, 40))
        self.specimen_death_label.setMaximumSize(QSize(150, 40))
        self.specimen_death_label.setFont(font)
        self.specimen_death_comboBox = QComboBox(self.specimen_frame)
        self.specimen_death_comboBox.addItem("")
        self.specimen_death_comboBox.addItem("")
        self.specimen_death_comboBox.addItem("")
        self.specimen_death_comboBox.addItem("")
        self.specimen_death_comboBox.setObjectName(u"specimen_death_comboBox")
        self.specimen_death_comboBox.setGeometry(QRect(930, 10, 160, 40))
        self.specimen_death_comboBox.setMinimumSize(QSize(160, 40))
        self.specimen_death_comboBox.setMaximumSize(QSize(160, 40))
        self.specimen_death_comboBox.setFont(font)
        self.specimen_animal_type_frame = QFrame(self.specimen_frame)
        self.specimen_animal_type_frame.setObjectName(u"specimen_animal_type_frame")
        self.specimen_animal_type_frame.setGeometry(QRect(10, 130, 940, 120))
        self.specimen_animal_type_frame.setMinimumSize(QSize(940, 120))
        self.specimen_animal_type_frame.setMaximumSize(QSize(940, 120))
        self.specimen_animal_type_frame.setFrameShape(QFrame.Shape.Box)
        self.specimen_animal_type_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.specimen_animal_type_label = QLabel(self.specimen_animal_type_frame)
        self.specimen_animal_type_label.setObjectName(u"specimen_animal_type_label")
        self.specimen_animal_type_label.setGeometry(QRect(10, 10, 70, 40))
        self.specimen_animal_type_label.setMinimumSize(QSize(70, 40))
        self.specimen_animal_type_label.setMaximumSize(QSize(70, 40))
        self.specimen_animal_type_label.setFont(font)
        self.specimen_swine_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_swine_radioButton.setObjectName(u"specimen_swine_radioButton")
        self.specimen_swine_radioButton.setGeometry(QRect(120, 10, 120, 40))
        self.specimen_swine_radioButton.setMinimumSize(QSize(120, 40))
        self.specimen_swine_radioButton.setMaximumSize(QSize(120, 40))
        self.specimen_swine_radioButton.setFont(font)
        self.specimen_elephant_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_elephant_radioButton.setObjectName(u"specimen_elephant_radioButton")
        self.specimen_elephant_radioButton.setGeometry(QRect(120, 70, 140, 40))
        self.specimen_elephant_radioButton.setMinimumSize(QSize(140, 40))
        self.specimen_elephant_radioButton.setMaximumSize(QSize(140, 40))
        self.specimen_elephant_radioButton.setFont(font)
        self.specimen_felin_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_felin_radioButton.setObjectName(u"specimen_felin_radioButton")
        self.specimen_felin_radioButton.setGeometry(QRect(290, 70, 110, 40))
        self.specimen_felin_radioButton.setMinimumSize(QSize(110, 40))
        self.specimen_felin_radioButton.setMaximumSize(QSize(110, 40))
        self.specimen_felin_radioButton.setFont(font)
        self.specimen_avian_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_avian_radioButton.setObjectName(u"specimen_avian_radioButton")
        self.specimen_avian_radioButton.setGeometry(QRect(290, 10, 140, 40))
        self.specimen_avian_radioButton.setMinimumSize(QSize(140, 40))
        self.specimen_avian_radioButton.setMaximumSize(QSize(140, 40))
        self.specimen_avian_radioButton.setFont(font)
        self.specimen_bovine_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_bovine_radioButton.setObjectName(u"specimen_bovine_radioButton")
        self.specimen_bovine_radioButton.setGeometry(QRect(460, 10, 120, 40))
        self.specimen_bovine_radioButton.setMinimumSize(QSize(120, 40))
        self.specimen_bovine_radioButton.setMaximumSize(QSize(120, 40))
        self.specimen_bovine_radioButton.setFont(font)
        self.specimen_equine_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_equine_radioButton.setObjectName(u"specimen_equine_radioButton")
        self.specimen_equine_radioButton.setGeometry(QRect(630, 10, 120, 40))
        self.specimen_equine_radioButton.setMinimumSize(QSize(120, 40))
        self.specimen_equine_radioButton.setMaximumSize(QSize(120, 40))
        self.specimen_equine_radioButton.setFont(font)
        self.specimen_conine_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_conine_radioButton.setObjectName(u"specimen_conine_radioButton")
        self.specimen_conine_radioButton.setGeometry(QRect(800, 10, 130, 40))
        self.specimen_conine_radioButton.setMinimumSize(QSize(130, 40))
        self.specimen_conine_radioButton.setMaximumSize(QSize(130, 40))
        self.specimen_conine_radioButton.setFont(font)
        self.specimen_unknown_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_unknown_radioButton.setObjectName(u"specimen_unknown_radioButton")
        self.specimen_unknown_radioButton.setGeometry(QRect(800, 70, 120, 40))
        self.specimen_unknown_radioButton.setMinimumSize(QSize(120, 40))
        self.specimen_unknown_radioButton.setMaximumSize(QSize(120, 40))
        self.specimen_unknown_radioButton.setFont(font)
        self.specimen_animal_other_radioButton = QRadioButton(self.specimen_animal_type_frame)
        self.specimen_animal_other_radioButton.setObjectName(u"specimen_animal_other_radioButton")
        self.specimen_animal_other_radioButton.setGeometry(QRect(460, 70, 70, 40))
        self.specimen_animal_other_radioButton.setMinimumSize(QSize(70, 40))
        self.specimen_animal_other_radioButton.setMaximumSize(QSize(70, 40))
        self.specimen_animal_other_radioButton.setFont(font)
        self.specimen_animal_other_lineEdit = QLineEdit(self.specimen_animal_type_frame)
        self.specimen_animal_other_lineEdit.setObjectName(u"specimen_animal_other_lineEdit")
        self.specimen_animal_other_lineEdit.setGeometry(QRect(520, 70, 260, 40))
        self.specimen_animal_other_lineEdit.setMinimumSize(QSize(260, 40))
        self.specimen_animal_other_lineEdit.setMaximumSize(QSize(260, 40))
        self.specimen_animal_other_lineEdit.setFont(font)
        self.specimen_sample_frame = QFrame(self.specimen_frame)
        self.specimen_sample_frame.setObjectName(u"specimen_sample_frame")
        self.specimen_sample_frame.setGeometry(QRect(960, 180, 290, 200))
        self.specimen_sample_frame.setMinimumSize(QSize(290, 200))
        self.specimen_sample_frame.setMaximumSize(QSize(290, 200))
        self.specimen_sample_frame.setFrameShape(QFrame.Shape.Box)
        self.specimen_sample_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.specimen_sample_label = QLabel(self.specimen_sample_frame)
        self.specimen_sample_label.setObjectName(u"specimen_sample_label")
        self.specimen_sample_label.setGeometry(QRect(10, 10, 270, 70))
        self.specimen_sample_label.setMinimumSize(QSize(270, 70))
        self.specimen_sample_label.setMaximumSize(QSize(270, 70))
        self.specimen_sample_label.setFont(font)
        self.specimen_sample_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_sample_label.setWordWrap(True)
        self.specimen_sample_comboBox = QComboBox(self.specimen_sample_frame)
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.addItem("")
        self.specimen_sample_comboBox.setObjectName(u"specimen_sample_comboBox")
        self.specimen_sample_comboBox.setGeometry(QRect(10, 90, 270, 40))
        self.specimen_sample_comboBox.setMinimumSize(QSize(270, 40))
        self.specimen_sample_comboBox.setMaximumSize(QSize(270, 40))
        self.specimen_sample_comboBox.setFont(font)
        self.specimen_sample_other_radioButton = QRadioButton(self.specimen_sample_frame)
        self.specimen_sample_other_radioButton.setObjectName(u"specimen_sample_other_radioButton")
        self.specimen_sample_other_radioButton.setGeometry(QRect(10, 150, 70, 40))
        self.specimen_sample_other_radioButton.setMinimumSize(QSize(70, 40))
        self.specimen_sample_other_radioButton.setMaximumSize(QSize(70, 40))
        self.specimen_sample_other_radioButton.setFont(font)
        self.specimen_sample_other_lineEdit = QLineEdit(self.specimen_sample_frame)
        self.specimen_sample_other_lineEdit.setObjectName(u"specimen_sample_other_lineEdit")
        self.specimen_sample_other_lineEdit.setGeometry(QRect(70, 150, 210, 40))
        self.specimen_sample_other_lineEdit.setMinimumSize(QSize(210, 40))
        self.specimen_sample_other_lineEdit.setMaximumSize(QSize(210, 40))
        self.specimen_sample_other_lineEdit.setFont(font)
        self.specimen_sample_other_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_breed_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_breed_lineEdit.setObjectName(u"specimen_breed_lineEdit")
        self.specimen_breed_lineEdit.setGeometry(QRect(160, 260, 370, 40))
        self.specimen_breed_lineEdit.setMinimumSize(QSize(370, 40))
        self.specimen_breed_lineEdit.setMaximumSize(QSize(370, 40))
        self.specimen_breed_lineEdit.setFont(font)
        self.specimen_breed_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_breed_label = QLabel(self.specimen_frame)
        self.specimen_breed_label.setObjectName(u"specimen_breed_label")
        self.specimen_breed_label.setGeometry(QRect(20, 260, 110, 40))
        self.specimen_breed_label.setMinimumSize(QSize(110, 40))
        self.specimen_breed_label.setMaximumSize(QSize(110, 40))
        self.specimen_breed_label.setFont(font)
        self.specimen_weight_lineEdit = QLineEdit(self.specimen_frame)
        self.specimen_weight_lineEdit.setObjectName(u"specimen_weight_lineEdit")
        self.specimen_weight_lineEdit.setGeometry(QRect(620, 260, 150, 40))
        self.specimen_weight_lineEdit.setMinimumSize(QSize(150, 40))
        self.specimen_weight_lineEdit.setMaximumSize(QSize(150, 40))
        self.specimen_weight_lineEdit.setFont(font)
        self.specimen_weight_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_weight_label = QLabel(self.specimen_frame)
        self.specimen_weight_label.setObjectName(u"specimen_weight_label")
        self.specimen_weight_label.setGeometry(QRect(550, 260, 60, 40))
        self.specimen_weight_label.setMinimumSize(QSize(60, 40))
        self.specimen_weight_label.setMaximumSize(QSize(60, 40))
        self.specimen_weight_label.setFont(font)
        self.specimen_kilogram_label = QLabel(self.specimen_frame)
        self.specimen_kilogram_label.setObjectName(u"specimen_kilogram_label")
        self.specimen_kilogram_label.setGeometry(QRect(790, 260, 70, 40))
        self.specimen_kilogram_label.setMinimumSize(QSize(70, 40))
        self.specimen_kilogram_label.setMaximumSize(QSize(70, 40))
        self.specimen_kilogram_label.setFont(font)
        self.specimen_day_of_death_label = QLabel(self.specimen_frame)
        self.specimen_day_of_death_label.setObjectName(u"specimen_day_of_death_label")
        self.specimen_day_of_death_label.setGeometry(QRect(20, 320, 110, 40))
        self.specimen_day_of_death_label.setMinimumSize(QSize(110, 40))
        self.specimen_day_of_death_label.setMaximumSize(QSize(110, 40))
        self.specimen_day_of_death_label.setFont(font)
        self.specimen_day_of_death_dateTimeEdit = QDateTimeEdit(self.specimen_frame)
        self.specimen_day_of_death_dateTimeEdit.setObjectName(u"specimen_day_of_death_dateTimeEdit")
        self.specimen_day_of_death_dateTimeEdit.setGeometry(QRect(160, 320, 170, 40))
        self.specimen_day_of_death_dateTimeEdit.setMinimumSize(QSize(170, 40))
        self.specimen_day_of_death_dateTimeEdit.setMaximumSize(QSize(170, 40))
        self.specimen_day_of_death_dateTimeEdit.setFont(font)
        self.specimen_day_of_death_dateTimeEdit.setLocale(QLocale(QLocale.Thai, QLocale.Thailand))
        self.specimen_day_of_death_dateTimeEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.specimen_day_of_death_dateTimeEdit.setCalendarPopup(True)
        self.specimen_day_keep_sample_label = QLabel(self.specimen_frame)
        self.specimen_day_keep_sample_label.setObjectName(u"specimen_day_keep_sample_label")
        self.specimen_day_keep_sample_label.setGeometry(QRect(20, 380, 130, 40))
        self.specimen_day_keep_sample_label.setMinimumSize(QSize(130, 40))
        self.specimen_day_keep_sample_label.setMaximumSize(QSize(130, 40))
        self.specimen_day_keep_sample_label.setFont(font)
        self.specimen_day_keep_sample_dateTimeEdit = QDateTimeEdit(self.specimen_frame)
        self.specimen_day_keep_sample_dateTimeEdit.setObjectName(u"specimen_day_keep_sample_dateTimeEdit")
        self.specimen_day_keep_sample_dateTimeEdit.setGeometry(QRect(160, 380, 170, 40))
        self.specimen_day_keep_sample_dateTimeEdit.setMinimumSize(QSize(170, 40))
        self.specimen_day_keep_sample_dateTimeEdit.setMaximumSize(QSize(170, 40))
        self.specimen_day_keep_sample_dateTimeEdit.setFont(font)
        self.specimen_day_keep_sample_dateTimeEdit.setLocale(QLocale(QLocale.Thai, QLocale.Thailand))
        self.specimen_day_keep_sample_dateTimeEdit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.specimen_day_keep_sample_dateTimeEdit.setCalendarPopup(True)
        self.specimen_keeping_frame = QFrame(self.specimen_frame)
        self.specimen_keeping_frame.setObjectName(u"specimen_keeping_frame")
        self.specimen_keeping_frame.setGeometry(QRect(340, 320, 610, 100))
        self.specimen_keeping_frame.setMinimumSize(QSize(610, 100))
        self.specimen_keeping_frame.setMaximumSize(QSize(610, 100))
        self.specimen_keeping_frame.setFrameShape(QFrame.Shape.Box)
        self.specimen_keeping_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.specimen_keeping_label = QLabel(self.specimen_keeping_frame)
        self.specimen_keeping_label.setObjectName(u"specimen_keeping_label")
        self.specimen_keeping_label.setGeometry(QRect(10, 0, 170, 40))
        self.specimen_keeping_label.setMinimumSize(QSize(170, 40))
        self.specimen_keeping_label.setMaximumSize(QSize(170, 40))
        self.specimen_keeping_label.setFont(font)
        self.specimen_chill_radioButton = QRadioButton(self.specimen_keeping_frame)
        self.specimen_chill_radioButton.setObjectName(u"specimen_chill_radioButton")
        self.specimen_chill_radioButton.setGeometry(QRect(10, 45, 130, 40))
        self.specimen_chill_radioButton.setMinimumSize(QSize(130, 40))
        self.specimen_chill_radioButton.setMaximumSize(QSize(130, 40))
        self.specimen_chill_radioButton.setFont(font)
        self.specimen_freeze_radioButton = QRadioButton(self.specimen_keeping_frame)
        self.specimen_freeze_radioButton.setObjectName(u"specimen_freeze_radioButton")
        self.specimen_freeze_radioButton.setGeometry(QRect(190, 45, 150, 40))
        self.specimen_freeze_radioButton.setMinimumSize(QSize(150, 40))
        self.specimen_freeze_radioButton.setMaximumSize(QSize(150, 40))
        self.specimen_freeze_radioButton.setFont(font)
        self.specimen_room_temperature_radioButton = QRadioButton(self.specimen_keeping_frame)
        self.specimen_room_temperature_radioButton.setObjectName(u"specimen_room_temperature_radioButton")
        self.specimen_room_temperature_radioButton.setGeometry(QRect(370, 45, 230, 40))
        self.specimen_room_temperature_radioButton.setMinimumSize(QSize(230, 40))
        self.specimen_room_temperature_radioButton.setMaximumSize(QSize(230, 40))
        self.specimen_room_temperature_radioButton.setFont(font)
        self.specimen_record_heal_label = QLabel(self.specimen_frame)
        self.specimen_record_heal_label.setObjectName(u"specimen_record_heal_label")
        self.specimen_record_heal_label.setGeometry(QRect(20, 440, 130, 40))
        self.specimen_record_heal_label.setMinimumSize(QSize(130, 40))
        self.specimen_record_heal_label.setMaximumSize(QSize(130, 40))
        self.specimen_record_heal_label.setFont(font)
        self.specimen_record_heal_textEdit = QTextEdit(self.specimen_frame)
        self.specimen_record_heal_textEdit.setObjectName(u"specimen_record_heal_textEdit")
        self.specimen_record_heal_textEdit.setGeometry(QRect(160, 440, 320, 90))
        self.specimen_record_heal_textEdit.setMinimumSize(QSize(320, 90))
        self.specimen_record_heal_textEdit.setMaximumSize(QSize(320, 90))
        self.specimen_record_heal_textEdit.setFont(font)
        self.specimen_record_antibiotics_textEdit = QTextEdit(self.specimen_frame)
        self.specimen_record_antibiotics_textEdit.setObjectName(u"specimen_record_antibiotics_textEdit")
        self.specimen_record_antibiotics_textEdit.setGeometry(QRect(630, 440, 320, 90))
        self.specimen_record_antibiotics_textEdit.setMinimumSize(QSize(320, 90))
        self.specimen_record_antibiotics_textEdit.setMaximumSize(QSize(320, 90))
        self.specimen_record_antibiotics_textEdit.setFont(font)
        self.specimen_record_antibiotics_label = QLabel(self.specimen_frame)
        self.specimen_record_antibiotics_label.setObjectName(u"specimen_record_antibiotics_label")
        self.specimen_record_antibiotics_label.setGeometry(QRect(490, 440, 140, 60))
        self.specimen_record_antibiotics_label.setMinimumSize(QSize(140, 60))
        self.specimen_record_antibiotics_label.setMaximumSize(QSize(140, 60))
        self.specimen_record_antibiotics_label.setFont(font)
        self.specimen_record_antibiotics_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.specimen_record_antibiotics_label.setWordWrap(True)
        self.specimen_save_pushButton = QPushButton(self.specimen_frame)
        self.specimen_save_pushButton.setObjectName(u"specimen_save_pushButton")
        self.specimen_save_pushButton.setGeometry(QRect(970, 440, 130, 60))
        self.specimen_save_pushButton.setMinimumSize(QSize(130, 60))
        self.specimen_save_pushButton.setMaximumSize(QSize(130, 60))
        self.specimen_save_pushButton.setFont(font)
        self.specimen_cancel_pushButton = QPushButton(self.specimen_frame)
        self.specimen_cancel_pushButton.setObjectName(u"specimen_cancel_pushButton")
        self.specimen_cancel_pushButton.setGeometry(QRect(1110, 440, 130, 60))
        self.specimen_cancel_pushButton.setMinimumSize(QSize(130, 60))
        self.specimen_cancel_pushButton.setMaximumSize(QSize(130, 60))
        self.specimen_cancel_pushButton.setFont(font)
        self.specimen_lab_frame = QFrame(self.specimen_frame)
        self.specimen_lab_frame.setObjectName(u"specimen_lab_frame")
        self.specimen_lab_frame.setGeometry(QRect(0, 540, 1260, 330))
        self.specimen_lab_frame.setMinimumSize(QSize(1260, 330))
        self.specimen_lab_frame.setMaximumSize(QSize(1260, 330))
        self.specimen_lab_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.specimen_lab_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.specimen_lab_label = QLabel(self.specimen_lab_frame)
        self.specimen_lab_label.setObjectName(u"specimen_lab_label")
        self.specimen_lab_label.setGeometry(QRect(10, 10, 260, 40))
        self.specimen_lab_label.setMinimumSize(QSize(260, 40))
        self.specimen_lab_label.setMaximumSize(QSize(260, 40))
        self.specimen_lab_label.setFont(font)
        self.specimen_fungal_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_fungal_pushButton.setObjectName(u"specimen_fungal_pushButton")
        self.specimen_fungal_pushButton.setGeometry(QRect(10, 50, 390, 40))
        self.specimen_fungal_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_fungal_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_fungal_pushButton.setFont(font)
        self.specimen_serology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_serology_pushButton.setObjectName(u"specimen_serology_pushButton")
        self.specimen_serology_pushButton.setGeometry(QRect(10, 95, 390, 40))
        self.specimen_serology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_serology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_serology_pushButton.setFont(font)
        self.specimen_water_quality_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_water_quality_pushButton.setObjectName(u"specimen_water_quality_pushButton")
        self.specimen_water_quality_pushButton.setGeometry(QRect(10, 140, 390, 40))
        self.specimen_water_quality_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_water_quality_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_water_quality_pushButton.setFont(font)
        self.specimen_immunohistochemistry_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_immunohistochemistry_pushButton.setObjectName(u"specimen_immunohistochemistry_pushButton")
        self.specimen_immunohistochemistry_pushButton.setGeometry(QRect(10, 185, 390, 40))
        self.specimen_immunohistochemistry_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_immunohistochemistry_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_immunohistochemistry_pushButton.setFont(font)
        self.specimen_necropsy_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_necropsy_pushButton.setObjectName(u"specimen_necropsy_pushButton")
        self.specimen_necropsy_pushButton.setGeometry(QRect(10, 230, 390, 40))
        self.specimen_necropsy_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_necropsy_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_necropsy_pushButton.setFont(font)
        self.specimen_histopathology_research_recut_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_histopathology_research_recut_pushButton.setObjectName(u"specimen_histopathology_research_recut_pushButton")
        self.specimen_histopathology_research_recut_pushButton.setGeometry(QRect(10, 275, 390, 40))
        self.specimen_histopathology_research_recut_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_histopathology_research_recut_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_histopathology_research_recut_pushButton.setFont(font)
        self.specimen_microbiology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_microbiology_pushButton.setObjectName(u"specimen_microbiology_pushButton")
        self.specimen_microbiology_pushButton.setGeometry(QRect(430, 50, 390, 40))
        self.specimen_microbiology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_microbiology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_microbiology_pushButton.setFont(font)
        self.specimen_cytology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_cytology_pushButton.setObjectName(u"specimen_cytology_pushButton")
        self.specimen_cytology_pushButton.setGeometry(QRect(430, 230, 390, 40))
        self.specimen_cytology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_cytology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_cytology_pushButton.setFont(font)
        self.specimen_parasitology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_parasitology_pushButton.setObjectName(u"specimen_parasitology_pushButton")
        self.specimen_parasitology_pushButton.setGeometry(QRect(430, 95, 390, 40))
        self.specimen_parasitology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_parasitology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_parasitology_pushButton.setFont(font)
        self.specimen_molecular_biology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_molecular_biology_pushButton.setObjectName(u"specimen_molecular_biology_pushButton")
        self.specimen_molecular_biology_pushButton.setGeometry(QRect(430, 140, 390, 40))
        self.specimen_molecular_biology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_molecular_biology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_molecular_biology_pushButton.setFont(font)
        self.specimen_histopathology_research_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_histopathology_research_pushButton.setObjectName(u"specimen_histopathology_research_pushButton")
        self.specimen_histopathology_research_pushButton.setGeometry(QRect(430, 275, 390, 40))
        self.specimen_histopathology_research_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_histopathology_research_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_histopathology_research_pushButton.setFont(font)
        self.specimen_surgical_biopsy_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_surgical_biopsy_pushButton.setObjectName(u"specimen_surgical_biopsy_pushButton")
        self.specimen_surgical_biopsy_pushButton.setGeometry(QRect(430, 185, 390, 40))
        self.specimen_surgical_biopsy_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_surgical_biopsy_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_surgical_biopsy_pushButton.setFont(font)
        self.specimen_food_safety_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_food_safety_pushButton.setObjectName(u"specimen_food_safety_pushButton")
        self.specimen_food_safety_pushButton.setGeometry(QRect(850, 230, 390, 40))
        self.specimen_food_safety_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_food_safety_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_food_safety_pushButton.setFont(font)
        self.specimen_service_after_death_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_service_after_death_pushButton.setObjectName(u"specimen_service_after_death_pushButton")
        self.specimen_service_after_death_pushButton.setGeometry(QRect(850, 275, 390, 40))
        self.specimen_service_after_death_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_service_after_death_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_service_after_death_pushButton.setFont(font)
        self.specimen_virology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_virology_pushButton.setObjectName(u"specimen_virology_pushButton")
        self.specimen_virology_pushButton.setGeometry(QRect(850, 50, 390, 40))
        self.specimen_virology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_virology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_virology_pushButton.setFont(font)
        self.specimen_histopathology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_histopathology_pushButton.setObjectName(u"specimen_histopathology_pushButton")
        self.specimen_histopathology_pushButton.setGeometry(QRect(850, 185, 390, 40))
        self.specimen_histopathology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_histopathology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_histopathology_pushButton.setFont(font)
        self.specimen_feed_analysis_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_feed_analysis_pushButton.setObjectName(u"specimen_feed_analysis_pushButton")
        self.specimen_feed_analysis_pushButton.setGeometry(QRect(850, 95, 390, 40))
        self.specimen_feed_analysis_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_feed_analysis_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_feed_analysis_pushButton.setFont(font)
        self.specimen_hematology_pushButton = QPushButton(self.specimen_lab_frame)
        self.specimen_hematology_pushButton.setObjectName(u"specimen_hematology_pushButton")
        self.specimen_hematology_pushButton.setGeometry(QRect(850, 140, 390, 40))
        self.specimen_hematology_pushButton.setMinimumSize(QSize(390, 40))
        self.specimen_hematology_pushButton.setMaximumSize(QSize(390, 40))
        self.specimen_hematology_pushButton.setFont(font)
        specimen_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(specimen_MainWindow)

        QMetaObject.connectSlotsByName(specimen_MainWindow)
    # setupUi

    def retranslateUi(self, specimen_MainWindow):
        specimen_MainWindow.setWindowTitle(QCoreApplication.translate("specimen_MainWindow", u"MainWindow", None))
        self.specimen_name_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e0a\u0e37\u0e48\u0e2d\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.specimen_ID_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2b\u0e21\u0e32\u0e22\u0e40\u0e25\u0e02 (ID/OPD)", None))
        self.specimen_sex_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e1e\u0e28 (SEX)", None))
        self.specimen_sex_comboBox.setItemText(0, QCoreApplication.translate("specimen_MainWindow", u"\u0e1c\u0e39\u0e49 (Male)", None))
        self.specimen_sex_comboBox.setItemText(1, QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e21\u0e35\u0e22 (Female)", None))
        self.specimen_sex_comboBox.setItemText(2, QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a (Unknow)", None))
        self.specimen_sex_comboBox.setItemText(3, QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Foal)", None))
        self.specimen_sex_comboBox.setItemText(4, QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Filly)", None))
        self.specimen_sex_comboBox.setItemText(5, QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Mare)", None))
        self.specimen_sex_comboBox.setItemText(6, QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Gelding)", None))
        self.specimen_sex_comboBox.setItemText(7, QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Stallion)", None))

        self.specimen_age_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e32\u0e22\u0e38 (Age)", None))
        self.specimen_ageYear_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e35", None))
        self.specimen_ageMonth_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e14\u0e37\u0e2d\u0e19", None))
        self.specimen_ageDay_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e27\u0e31\u0e19", None))
        self.specimen_ageUnknown_checkBox.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e2d\u0e32\u0e22\u0e38", None))
        self.specimen_status_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e16\u0e32\u0e19\u0e30\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.specimen_normal_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e01\u0e15\u0e34", None))
        self.specimen_most_urgent_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e14\u0e48\u0e27\u0e19\u0e17\u0e35\u0e48\u0e2a\u0e38\u0e14", None))
        self.specimen_death_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e32\u0e40\u0e2b\u0e15\u0e38\u0e01\u0e32\u0e23\u0e40\u0e2a\u0e35\u0e22\u0e0a\u0e35\u0e27\u0e34\u0e15", None))
        self.specimen_death_comboBox.setItemText(0, QCoreApplication.translate("specimen_MainWindow", u"\u0e22\u0e31\u0e07\u0e21\u0e35\u0e0a\u0e35\u0e27\u0e34\u0e15 (Alive)", None))
        self.specimen_death_comboBox.setItemText(1, QCoreApplication.translate("specimen_MainWindow", u"\u0e42\u0e23\u0e04\u0e0a\u0e23\u0e32 (Senile)", None))
        self.specimen_death_comboBox.setItemText(2, QCoreApplication.translate("specimen_MainWindow", u"\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d (Infectious Disease)", None))
        self.specimen_death_comboBox.setItemText(3, QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e2a\u0e32\u0e40\u0e2b\u0e15\u0e38 (Unknow)", None))

        self.specimen_animal_type_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e0a\u0e19\u0e34\u0e14\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.specimen_swine_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e38\u0e01\u0e23 (Swine)", None))
        self.specimen_elephant_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e0a\u0e49\u0e32\u0e07 (Elephant)", None))
        self.specimen_felin_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e41\u0e21\u0e27 (Felin)", None))
        self.specimen_avian_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e31\u0e15\u0e27\u0e4c\u0e1b\u0e35\u0e01 (Avian)", None))
        self.specimen_bovine_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e42\u0e04 (\u0e3aBovine)", None))
        self.specimen_equine_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e21\u0e49\u0e32 (Equine)", None))
        self.specimen_conine_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e38\u0e19\u0e31\u0e02 (Conine)", None))
        self.specimen_unknown_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e0a\u0e19\u0e34\u0e14", None))
        self.specimen_animal_other_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.specimen_sample_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e2a\u0e34\u0e48\u0e07\u0e2a\u0e48\u0e07\u0e15\u0e23\u0e27\u0e08 (SAMPLE)", None))
        self.specimen_sample_comboBox.setItemText(0, QCoreApplication.translate("specimen_MainWindow", u"\u0e0b\u0e32\u0e01\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.specimen_sample_comboBox.setItemText(1, QCoreApplication.translate("specimen_MainWindow", u"\u0e0a\u0e34\u0e49\u0e19\u0e40\u0e19\u0e37\u0e49\u0e2d\u0e43\u0e19\u0e19\u0e49\u0e33\u0e22\u0e32 10% \u0e1f\u0e2d\u0e23\u0e4c\u0e21\u0e32\u0e25\u0e34\u0e19", None))
        self.specimen_sample_comboBox.setItemText(2, QCoreApplication.translate("specimen_MainWindow", u"\u0e1a\u0e25\u0e47\u0e2d\u0e04\u0e1e\u0e32\u0e23\u0e32\u0e1f\u0e34\u0e19", None))
        self.specimen_sample_comboBox.setItemText(3, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e43\u0e19\u0e0a\u0e48\u0e2d\u0e07\u0e17\u0e49\u0e2d\u0e07", None))
        self.specimen_sample_comboBox.setItemText(4, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e43\u0e19\u0e0a\u0e48\u0e2d\u0e07\u0e2d\u0e01", None))
        self.specimen_sample_comboBox.setItemText(5, QCoreApplication.translate("specimen_MainWindow", u"FNA slide(s)", None))
        self.specimen_sample_comboBox.setItemText(6, QCoreApplication.translate("specimen_MainWindow", u"Slide(s)", None))
        self.specimen_sample_comboBox.setItemText(7, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e31\u0e2a\u0e2a\u0e32\u0e27\u0e30", None))
        self.specimen_sample_comboBox.setItemText(8, QCoreApplication.translate("specimen_MainWindow", u"\u0e02\u0e2d\u0e07\u0e40\u0e2b\u0e25\u0e27\u0e08\u0e32\u0e01\u0e41\u0e1c\u0e25", None))
        self.specimen_sample_comboBox.setItemText(9, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e44\u0e02\u0e02\u0e49\u0e2d\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01", None))
        self.specimen_sample_comboBox.setItemText(10, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e44\u0e02\u0e2a\u0e31\u0e19\u0e2b\u0e25\u0e31\u0e07", None))
        self.specimen_sample_comboBox.setItemText(11, QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e02\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01", None))
        self.specimen_sample_comboBox.setItemText(12, QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e25\u0e37\u0e2d\u0e14", None))
        self.specimen_sample_comboBox.setItemText(13, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e31\u0e2a\u0e2a\u0e32\u0e27\u0e30 (Cystocentesis)", None))
        self.specimen_sample_comboBox.setItemText(14, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e31\u0e2a\u0e2a\u0e32\u0e27\u0e30 (Catheterization)", None))
        self.specimen_sample_comboBox.setItemText(15, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e31\u0e2a\u0e2a\u0e32\u0e27\u0e30 (Voiding)", None))
        self.specimen_sample_comboBox.setItemText(16, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e25\u0e32\u0e22\u0e2a\u0e32\u0e22 Catheter", None))
        self.specimen_sample_comboBox.setItemText(17, QCoreApplication.translate("specimen_MainWindow", u"Ascitic fluid", None))
        self.specimen_sample_comboBox.setItemText(18, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e16\u0e38\u0e07\u0e2b\u0e38\u0e49\u0e21\u0e2b\u0e31\u0e27\u0e43\u0e08", None))
        self.specimen_sample_comboBox.setItemText(19, QCoreApplication.translate("specimen_MainWindow", u"Bronchiolar lavage", None))
        self.specimen_sample_comboBox.setItemText(20, QCoreApplication.translate("specimen_MainWindow", u"Gastric lavage", None))
        self.specimen_sample_comboBox.setItemText(21, QCoreApplication.translate("specimen_MainWindow", u"\u0e2b\u0e19\u0e2d\u0e07", None))
        self.specimen_sample_comboBox.setItemText(22, QCoreApplication.translate("specimen_MainWindow", u"Swab \u0e43\u0e19 Stuart transport medium", None))
        self.specimen_sample_comboBox.setItemText(23, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e25\u0e32\u0e22", None))
        self.specimen_sample_comboBox.setItemText(24, QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e38\u0e08\u0e08\u0e32\u0e23\u0e30", None))
        self.specimen_sample_comboBox.setItemText(25, QCoreApplication.translate("specimen_MainWindow", u"\u0e02\u0e19", None))
        self.specimen_sample_comboBox.setItemText(26, QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e25\u0e47\u0e1a", None))
        self.specimen_sample_comboBox.setItemText(27, QCoreApplication.translate("specimen_MainWindow", u"\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01", None))
        self.specimen_sample_comboBox.setItemText(28, QCoreApplication.translate("specimen_MainWindow", u"\u0e0a\u0e34\u0e49\u0e19\u0e40\u0e19\u0e37\u0e49\u0e2d", None))
        self.specimen_sample_comboBox.setItemText(29, QCoreApplication.translate("specimen_MainWindow", u"Isolate bacterial colony", None))
        self.specimen_sample_comboBox.setItemText(30, QCoreApplication.translate("specimen_MainWindow", u"Agar plate", None))
        self.specimen_sample_comboBox.setItemText(31, QCoreApplication.translate("specimen_MainWindow", u"\u0e2b\u0e19\u0e2d\u0e19\u0e1e\u0e22\u0e32\u0e18\u0e34", None))
        self.specimen_sample_comboBox.setItemText(32, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33", None))
        self.specimen_sample_comboBox.setItemText(33, QCoreApplication.translate("specimen_MainWindow", u"\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.specimen_sample_comboBox.setItemText(34, QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e32\u0e2b\u0e32\u0e23\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.specimen_sample_comboBox.setItemText(35, QCoreApplication.translate("specimen_MainWindow", u"Semen", None))
        self.specimen_sample_comboBox.setItemText(36, QCoreApplication.translate("specimen_MainWindow", u"\u0e0b\u0e35\u0e23\u0e31\u0e21", None))
        self.specimen_sample_comboBox.setItemText(37, QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e22\u0e32\u0e06\u0e48\u0e32\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.specimen_sample_comboBox.setItemText(38, QCoreApplication.translate("specimen_MainWindow", u"\u0e2a\u0e32\u0e23\u0e40\u0e04\u0e21\u0e35", None))
        self.specimen_sample_comboBox.setItemText(39, QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e23\u0e2a\u0e34\u0e15", None))
        self.specimen_sample_comboBox.setItemText(40, QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e38\u0e1b\u0e01\u0e23\u0e13\u0e4c", None))

        self.specimen_sample_other_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.specimen_breed_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c (Breed)", None))
        self.specimen_weight_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.specimen_kilogram_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e01\u0e34\u0e42\u0e25\u0e01\u0e23\u0e31\u0e21", None))
        self.specimen_day_of_death_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e40\u0e2a\u0e35\u0e22\u0e0a\u0e35\u0e27\u0e34\u0e15", None))
        self.specimen_day_of_death_dateTimeEdit.setDisplayFormat(QCoreApplication.translate("specimen_MainWindow", u"d/M/yyyy h:mm ", None))
        self.specimen_day_keep_sample_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e40\u0e01\u0e47\u0e1a\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.specimen_day_keep_sample_dateTimeEdit.setDisplayFormat(QCoreApplication.translate("specimen_MainWindow", u"d/M/yyyy h:mm ", None))
        self.specimen_keeping_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e01\u0e32\u0e23\u0e40\u0e01\u0e47\u0e1a\u0e23\u0e31\u0e01\u0e29\u0e32\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.specimen_chill_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e41\u0e0a\u0e48\u0e40\u0e22\u0e47\u0e19 (Chill)", None))
        self.specimen_freeze_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e41\u0e0a\u0e48\u0e41\u0e02\u0e47\u0e07 (Freeze)", None))
        self.specimen_room_temperature_radioButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e21\u0e48\u0e41\u0e0a\u0e48 (Room Temperature)", None))
        self.specimen_record_heal_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e23\u0e31\u0e01\u0e29\u0e32", None))
        self.specimen_record_antibiotics_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23 \u0e43\u0e2b\u0e49\u0e22\u0e32\u0e1b\u0e0f\u0e34\u0e0a\u0e35\u0e27\u0e19\u0e30", None))
        self.specimen_save_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.specimen_cancel_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e22\u0e49\u0e2d\u0e19\u0e01\u0e25\u0e31\u0e1a", None))
        self.specimen_lab_label.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2a\u0e48\u0e07\u0e15\u0e23\u0e27\u0e08", None))
        self.specimen_fungal_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e23\u0e32\u0e27\u0e34\u0e17\u0e22\u0e32 (Fungal)", None))
        self.specimen_serology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e0b\u0e35\u0e23\u0e31\u0e21\u0e27\u0e34\u0e17\u0e22\u0e32 (Serology)", None))
        self.specimen_water_quality_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e15\u0e23\u0e27\u0e08\u0e04\u0e38\u0e13\u0e20\u0e32\u0e1e\u0e19\u0e49\u0e33 (Water quality)", None))
        self.specimen_immunohistochemistry_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Immunohistochemistry)", None))
        self.specimen_necropsy_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Necropsy)", None))
        self.specimen_histopathology_research_recut_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology Research Recut)", None))
        self.specimen_microbiology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e08\u0e38\u0e25\u0e0a\u0e35\u0e27\u0e27\u0e34\u0e17\u0e22\u0e32 (Microbiology)", None))
        self.specimen_cytology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Cytology)", None))
        self.specimen_parasitology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1b\u0e23\u0e2a\u0e34\u0e15\u0e27\u0e34\u0e17\u0e22\u0e32 (Parasitology)", None))
        self.specimen_molecular_biology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e13\u0e39\u0e0a\u0e35\u0e27\u0e27\u0e34\u0e17\u0e22\u0e32 (Molecular biology)", None))
        self.specimen_histopathology_research_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology Research)", None))
        self.specimen_surgical_biopsy_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Surgical biopsy)", None))
        self.specimen_food_safety_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e2d\u0e32\u0e2b\u0e32\u0e23\u0e1b\u0e25\u0e2d\u0e14\u0e20\u0e31\u0e22 (Food safty)", None))
        self.specimen_service_after_death_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e07\u0e32\u0e19\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e2b\u0e25\u0e31\u0e07\u0e04\u0e27\u0e32\u0e21\u0e15\u0e32\u0e22", None))
        self.specimen_virology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e44\u0e27\u0e23\u0e31\u0e2a\u0e27\u0e34\u0e17\u0e22\u0e32 (Virology)", None))
        self.specimen_histopathology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology)", None))
        self.specimen_feed_analysis_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e40\u0e04\u0e21\u0e35\u0e27\u0e34\u0e40\u0e04\u0e23\u0e32\u0e30\u0e2b\u0e4c (Feed analysis)", None))
        self.specimen_hematology_pushButton.setText(QCoreApplication.translate("specimen_MainWindow", u"\u0e42\u0e25\u0e2b\u0e34\u0e15\u0e27\u0e34\u0e17\u0e22\u0e32 (Hematology)", None))
    # retranslateUi

